package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaActivityLimitId generated by hbm2java
 */
public class TaActivityLimitId  implements java.io.Serializable {


     private String calgroupId;
     private String caltransactionId;
     private String calaplicacion;

    public TaActivityLimitId() {
    }

    public TaActivityLimitId(String calgroupId, String caltransactionId, String calaplicacion) {
       this.calgroupId = calgroupId;
       this.caltransactionId = caltransactionId;
       this.calaplicacion = calaplicacion;
    }
   
    public String getCalgroupId() {
        return this.calgroupId;
    }
    
    public void setCalgroupId(String calgroupId) {
        this.calgroupId = calgroupId;
    }
    public String getCaltransactionId() {
        return this.caltransactionId;
    }
    
    public void setCaltransactionId(String caltransactionId) {
        this.caltransactionId = caltransactionId;
    }
    public String getCalaplicacion() {
        return this.calaplicacion;
    }
    
    public void setCalaplicacion(String calaplicacion) {
        this.calaplicacion = calaplicacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaActivityLimitId) ) return false;
		 TaActivityLimitId castOther = ( TaActivityLimitId ) other; 
         
		 return ( (this.getCalgroupId()==castOther.getCalgroupId()) || ( this.getCalgroupId()!=null && castOther.getCalgroupId()!=null && this.getCalgroupId().equals(castOther.getCalgroupId()) ) )
 && ( (this.getCaltransactionId()==castOther.getCaltransactionId()) || ( this.getCaltransactionId()!=null && castOther.getCaltransactionId()!=null && this.getCaltransactionId().equals(castOther.getCaltransactionId()) ) )
 && ( (this.getCalaplicacion()==castOther.getCalaplicacion()) || ( this.getCalaplicacion()!=null && castOther.getCalaplicacion()!=null && this.getCalaplicacion().equals(castOther.getCalaplicacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCalgroupId() == null ? 0 : this.getCalgroupId().hashCode() );
         result = 37 * result + ( getCaltransactionId() == null ? 0 : this.getCaltransactionId().hashCode() );
         result = 37 * result + ( getCalaplicacion() == null ? 0 : this.getCalaplicacion().hashCode() );
         return result;
   }   


}


