package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaAprobadorServicioId generated by hbm2java
 */
public class TaAprobadorServicioId  implements java.io.Serializable {


     private String casidAprobador;
     private long csemIdServicioEmpresa; 
     private long cascodigo;

    public TaAprobadorServicioId() {
    }

    public TaAprobadorServicioId(String casidAprobador, long csemIdServicioEmpresa, long cascodigo) {
       this.casidAprobador = casidAprobador;
       this.csemIdServicioEmpresa = csemIdServicioEmpresa;
       this.cascodigo = cascodigo;
    }
   
    public String getCasidAprobador() {
        return this.casidAprobador;
    }
    
    public void setCasidAprobador(String casidAprobador) {
        this.casidAprobador = casidAprobador;
    }
    public long getCsemIdServicioEmpresa() {
        return this.csemIdServicioEmpresa;
    }
    
    public void setCsemIdServicioEmpresa(long csemIdServicioEmpresa) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }
    public long getCascodigo() {
        return this.cascodigo;
    }
    
    public void setCascodigo(long cascodigo) {
        this.cascodigo = cascodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaAprobadorServicioId) ) return false;
		 TaAprobadorServicioId castOther = ( TaAprobadorServicioId ) other; 
         
		 return ( (this.getCasidAprobador()==castOther.getCasidAprobador()) || ( this.getCasidAprobador()!=null && castOther.getCasidAprobador()!=null && this.getCasidAprobador().equals(castOther.getCasidAprobador()) ) )
 && (this.getCsemIdServicioEmpresa()==castOther.getCsemIdServicioEmpresa())
 && (this.getCascodigo()==castOther.getCascodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCasidAprobador() == null ? 0 : this.getCasidAprobador().hashCode() );
         result = 37 * result + (int) this.getCsemIdServicioEmpresa();
         result = 37 * result + (int) this.getCascodigo();
         return result;
   }   


}


