package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaAprobadorServicio generated by hbm2java
 */
public class TaAprobadorServicio  implements java.io.Serializable {


     private TaAprobadorServicioId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private Character casestado;
     private String dasdescripcion;
     private String casmodifyUser;
     private String fasmodifyDate;
     private String hasmodifyTime;

    public TaAprobadorServicio() {
    }

	
    public TaAprobadorServicio(TaAprobadorServicioId id, TaServicioxEmpresa taServicioxEmpresa) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public TaAprobadorServicio(TaAprobadorServicioId id, TaServicioxEmpresa taServicioxEmpresa, Character casestado, String dasdescripcion, String casmodifyUser, String fasmodifyDate, String hasmodifyTime) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.casestado = casestado;
       this.dasdescripcion = dasdescripcion;
       this.casmodifyUser = casmodifyUser;
       this.fasmodifyDate = fasmodifyDate;
       this.hasmodifyTime = hasmodifyTime;
    }
   
    public TaAprobadorServicioId getId() {
        return this.id;
    }
    
    public void setId(TaAprobadorServicioId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public Character getCasestado() {
        return this.casestado;
    }
    
    public void setCasestado(Character casestado) {
        this.casestado = casestado;
    }
    public String getDasdescripcion() {
        return this.dasdescripcion;
    }
    
    public void setDasdescripcion(String dasdescripcion) {
        this.dasdescripcion = dasdescripcion;
    }
    public String getCasmodifyUser() {
        return this.casmodifyUser;
    }
    
    public void setCasmodifyUser(String casmodifyUser) {
        this.casmodifyUser = casmodifyUser;
    }
    public String getFasmodifyDate() {
        return this.fasmodifyDate;
    }
    
    public void setFasmodifyDate(String fasmodifyDate) {
        this.fasmodifyDate = fasmodifyDate;
    }
    public String getHasmodifyTime() {
        return this.hasmodifyTime;
    }
    
    public void setHasmodifyTime(String hasmodifyTime) {
        this.hasmodifyTime = hasmodifyTime;
    }




}


