package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaAprobacionOrdenId generated by hbm2java
 */
public class TaAprobacionOrdenId  implements java.io.Serializable {


     private long caoidAprobacion;
     private long caoidOrden;
     private long caoidServEmp;

    public TaAprobacionOrdenId() {
    }

    public TaAprobacionOrdenId(long caoidAprobacion, long caoidOrden, long caoidServEmp) {
       this.caoidAprobacion = caoidAprobacion;
       this.caoidOrden = caoidOrden;
       this.caoidServEmp = caoidServEmp;
    }
   
    public long getCaoidAprobacion() {
        return this.caoidAprobacion;
    }
    
    public void setCaoidAprobacion(long caoidAprobacion) {
        this.caoidAprobacion = caoidAprobacion;
    }
    public long getCaoidOrden() {
        return this.caoidOrden;
    }
    
    public void setCaoidOrden(long caoidOrden) {
        this.caoidOrden = caoidOrden;
    }
    public long getCaoidServEmp() {
        return this.caoidServEmp;
    }
    
    public void setCaoidServEmp(long caoidServEmp) {
        this.caoidServEmp = caoidServEmp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaAprobacionOrdenId) ) return false;
		 TaAprobacionOrdenId castOther = ( TaAprobacionOrdenId ) other; 
         
		 return (this.getCaoidAprobacion()==castOther.getCaoidAprobacion())
 && (this.getCaoidOrden()==castOther.getCaoidOrden())
 && (this.getCaoidServEmp()==castOther.getCaoidServEmp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCaoidAprobacion();
         result = 37 * result + (int) this.getCaoidOrden();
         result = 37 * result + (int) this.getCaoidServEmp();
         return result;
   }   


}


