package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TaBuzonEnvio generated by hbm2java
 */
public class TaBuzonEnvio  implements java.io.Serializable {


     private long cbenIdEnvio;
     private String fbenFechaCreacion;
     private String fbenFechaInicioVig;
     private String fbenFechaFinVig;
     private String hbenHoraInicio;
     private String dbenTipoCuenta;
     private String nbenCuentaCargo;
     private Character cbenTipoIngreso;
     private String dbenReferencia;
     private Character cbenEstado;
     private String cbenUsuario;
     private long cbenIdOrden;
     private Long cbenIdServEmp;
     private Set tpDetalleBuzons = new HashSet(0);

    public TaBuzonEnvio() {
    }

	
    public TaBuzonEnvio(long cbenIdEnvio, long cbenIdOrden) {
        this.cbenIdEnvio = cbenIdEnvio;
        this.cbenIdOrden = cbenIdOrden;
    }
    public TaBuzonEnvio(long cbenIdEnvio, String fbenFechaCreacion, String fbenFechaInicioVig, String fbenFechaFinVig, String hbenHoraInicio, String dbenTipoCuenta, String nbenCuentaCargo, Character cbenTipoIngreso, String dbenReferencia, Character cbenEstado, String cbenUsuario, long cbenIdOrden, Long cbenIdServEmp, Set tpDetalleBuzons) {
       this.cbenIdEnvio = cbenIdEnvio;
       this.fbenFechaCreacion = fbenFechaCreacion;
       this.fbenFechaInicioVig = fbenFechaInicioVig;
       this.fbenFechaFinVig = fbenFechaFinVig;
       this.hbenHoraInicio = hbenHoraInicio;
       this.dbenTipoCuenta = dbenTipoCuenta;
       this.nbenCuentaCargo = nbenCuentaCargo;
       this.cbenTipoIngreso = cbenTipoIngreso;
       this.dbenReferencia = dbenReferencia;
       this.cbenEstado = cbenEstado;
       this.cbenUsuario = cbenUsuario;
       this.cbenIdOrden = cbenIdOrden;
       this.cbenIdServEmp = cbenIdServEmp;
       this.tpDetalleBuzons = tpDetalleBuzons;
    }
   
    public long getCbenIdEnvio() {
        return this.cbenIdEnvio;
    }
    
    public void setCbenIdEnvio(long cbenIdEnvio) {
        this.cbenIdEnvio = cbenIdEnvio;
    }
    public String getFbenFechaCreacion() {
        return this.fbenFechaCreacion;
    }
    
    public void setFbenFechaCreacion(String fbenFechaCreacion) {
        this.fbenFechaCreacion = fbenFechaCreacion;
    }
    public String getFbenFechaInicioVig() {
        return this.fbenFechaInicioVig;
    }
    
    public void setFbenFechaInicioVig(String fbenFechaInicioVig) {
        this.fbenFechaInicioVig = fbenFechaInicioVig;
    }
    public String getFbenFechaFinVig() {
        return this.fbenFechaFinVig;
    }
    
    public void setFbenFechaFinVig(String fbenFechaFinVig) {
        this.fbenFechaFinVig = fbenFechaFinVig;
    }
    public String getHbenHoraInicio() {
        return this.hbenHoraInicio;
    }
    
    public void setHbenHoraInicio(String hbenHoraInicio) {
        this.hbenHoraInicio = hbenHoraInicio;
    }
    public String getDbenTipoCuenta() {
        return this.dbenTipoCuenta;
    }
    
    public void setDbenTipoCuenta(String dbenTipoCuenta) {
        this.dbenTipoCuenta = dbenTipoCuenta;
    }
    public String getNbenCuentaCargo() {
        return this.nbenCuentaCargo;
    }
    
    public void setNbenCuentaCargo(String nbenCuentaCargo) {
        this.nbenCuentaCargo = nbenCuentaCargo;
    }
    public Character getCbenTipoIngreso() {
        return this.cbenTipoIngreso;
    }
    
    public void setCbenTipoIngreso(Character cbenTipoIngreso) {
        this.cbenTipoIngreso = cbenTipoIngreso;
    }
    public String getDbenReferencia() {
        return this.dbenReferencia;
    }
    
    public void setDbenReferencia(String dbenReferencia) {
        this.dbenReferencia = dbenReferencia;
    }
    public Character getCbenEstado() {
        return this.cbenEstado;
    }
    
    public void setCbenEstado(Character cbenEstado) {
        this.cbenEstado = cbenEstado;
    }
    public String getCbenUsuario() {
        return this.cbenUsuario;
    }
    
    public void setCbenUsuario(String cbenUsuario) {
        this.cbenUsuario = cbenUsuario;
    }
    public long getCbenIdOrden() {
        return this.cbenIdOrden;
    }
    
    public void setCbenIdOrden(long cbenIdOrden) {
        this.cbenIdOrden = cbenIdOrden;
    }
    public Long getCbenIdServEmp() {
        return this.cbenIdServEmp;
    }
    
    public void setCbenIdServEmp(Long cbenIdServEmp) {
        this.cbenIdServEmp = cbenIdServEmp;
    }
    public Set getTpDetalleBuzons() {
        return this.tpDetalleBuzons;
    }
    
    public void setTpDetalleBuzons(Set tpDetalleBuzons) {
        this.tpDetalleBuzons = tpDetalleBuzons;
    }




}


