package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaCamposRequeridos generated by hbm2java
 */
public class TaCamposRequeridos  implements java.io.Serializable {


     private TaCamposRequeridosId id;
     private TaTipoPagoServicio taTipoPagoServicio;
     private String dcretiqueta;
     private String dcrnomVariable;
     private String dcrdescripcion;
     private Character ccrflagObligatorio;
     private String dcrcontrolGui;
     private String dcrtipoDato;

    public TaCamposRequeridos() {
    }

	
    public TaCamposRequeridos(TaCamposRequeridosId id, TaTipoPagoServicio taTipoPagoServicio) {
        this.id = id;
        this.taTipoPagoServicio = taTipoPagoServicio;
    }
    public TaCamposRequeridos(TaCamposRequeridosId id, TaTipoPagoServicio taTipoPagoServicio, String dcretiqueta, String dcrnomVariable, String dcrdescripcion, Character ccrflagObligatorio, String dcrcontrolGui, String dcrtipoDato) {
       this.id = id;
       this.taTipoPagoServicio = taTipoPagoServicio;
       this.dcretiqueta = dcretiqueta;
       this.dcrnomVariable = dcrnomVariable;
       this.dcrdescripcion = dcrdescripcion;
       this.ccrflagObligatorio = ccrflagObligatorio;
       this.dcrcontrolGui = dcrcontrolGui;
       this.dcrtipoDato = dcrtipoDato;
    }
   
    public TaCamposRequeridosId getId() {
        return this.id;
    }
    
    public void setId(TaCamposRequeridosId id) {
        this.id = id;
    }
    public TaTipoPagoServicio getTaTipoPagoServicio() {
        return this.taTipoPagoServicio;
    }
    
    public void setTaTipoPagoServicio(TaTipoPagoServicio taTipoPagoServicio) {
        this.taTipoPagoServicio = taTipoPagoServicio;
    }
    public String getDcretiqueta() {
        return this.dcretiqueta;
    }
    
    public void setDcretiqueta(String dcretiqueta) {
        this.dcretiqueta = dcretiqueta;
    }
    public String getDcrnomVariable() {
        return this.dcrnomVariable;
    }
    
    public void setDcrnomVariable(String dcrnomVariable) {
        this.dcrnomVariable = dcrnomVariable;
    }
    public String getDcrdescripcion() {
        return this.dcrdescripcion;
    }
    
    public void setDcrdescripcion(String dcrdescripcion) {
        this.dcrdescripcion = dcrdescripcion;
    }
    public Character getCcrflagObligatorio() {
        return this.ccrflagObligatorio;
    }
    
    public void setCcrflagObligatorio(Character ccrflagObligatorio) {
        this.ccrflagObligatorio = ccrflagObligatorio;
    }
    public String getDcrcontrolGui() {
        return this.dcrcontrolGui;
    }
    
    public void setDcrcontrolGui(String dcrcontrolGui) {
        this.dcrcontrolGui = dcrcontrolGui;
    }
    public String getDcrtipoDato() {
        return this.dcrtipoDato;
    }
    
    public void setDcrtipoDato(String dcrtipoDato) {
        this.dcrtipoDato = dcrtipoDato;
    }




}


