package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaContactoEmpresaId generated by hbm2java
 */
public class TaContactoEmpresaId  implements java.io.Serializable {


     private int cceidContacto;
     private String cceidEmpresa; 

    public TaContactoEmpresaId() {
    }

    public TaContactoEmpresaId(int cceidContacto, String cceidEmpresa) {
       this.cceidContacto = cceidContacto;
       this.cceidEmpresa = cceidEmpresa;
    }
   
    public int getCceidContacto() {
        return this.cceidContacto;
    }
    
    public void setCceidContacto(int cceidContacto) {
        this.cceidContacto = cceidContacto;
    }
    public String getCceidEmpresa() {
        return this.cceidEmpresa;
    }
    
    public void setCceidEmpresa(String cceidEmpresa) {
        this.cceidEmpresa = cceidEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaContactoEmpresaId) ) return false;
		 TaContactoEmpresaId castOther = ( TaContactoEmpresaId ) other; 
         
		 return (this.getCceidContacto()==castOther.getCceidContacto())
 && ( (this.getCceidEmpresa()==castOther.getCceidEmpresa()) || ( this.getCceidEmpresa()!=null && castOther.getCceidEmpresa()!=null && this.getCceidEmpresa().equals(castOther.getCceidEmpresa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCceidContacto();
         result = 37 * result + ( getCceidEmpresa() == null ? 0 : this.getCceidEmpresa().hashCode() );
         return result;
   }   


}


