package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaContactoEmpresa generated by hbm2java
 */
public class TaContactoEmpresa  implements java.io.Serializable {


     private TaContactoEmpresaId id;
     private TmEmpresa tmEmpresa;
     private String dcenombre;
     private String dceemail;
     private String ccetipo;
     private String ccemodifyUser;
     private String ccemodifyDate;
     private String hcemodifyTime;

    public TaContactoEmpresa() {
    }

	
    public TaContactoEmpresa(TaContactoEmpresaId id, TmEmpresa tmEmpresa) {
        this.id = id;
        this.tmEmpresa = tmEmpresa;
    }
    public TaContactoEmpresa(TaContactoEmpresaId id, TmEmpresa tmEmpresa, String dcenombre, String dceemail, String ccetipo, String ccemodifyUser, String ccemodifyDate, String hcemodifyTime) {
       this.id = id;
       this.tmEmpresa = tmEmpresa;
       this.dcenombre = dcenombre;
       this.dceemail = dceemail;
       this.ccetipo = ccetipo;
       this.ccemodifyUser = ccemodifyUser;
       this.ccemodifyDate = ccemodifyDate;
       this.hcemodifyTime = hcemodifyTime;
    }
   
    public TaContactoEmpresaId getId() {
        return this.id;
    }
    
    public void setId(TaContactoEmpresaId id) {
        this.id = id;
    }
    public TmEmpresa getTmEmpresa() {
        return this.tmEmpresa;
    }
    
    public void setTmEmpresa(TmEmpresa tmEmpresa) {
        this.tmEmpresa = tmEmpresa;
    }
    public String getDcenombre() {
        return this.dcenombre;
    }
    
    public void setDcenombre(String dcenombre) {
        this.dcenombre = dcenombre;
    }
    public String getDceemail() {
        return this.dceemail;
    }
    
    public void setDceemail(String dceemail) {
        this.dceemail = dceemail;
    }
    public String getCcetipo() {
        return this.ccetipo;
    }
    
    public void setCcetipo(String ccetipo) {
        this.ccetipo = ccetipo;
    }
    public String getCcemodifyUser() {
        return this.ccemodifyUser;
    }
    
    public void setCcemodifyUser(String ccemodifyUser) {
        this.ccemodifyUser = ccemodifyUser;
    }
    public String getCcemodifyDate() {
        return this.ccemodifyDate;
    }
    
    public void setCcemodifyDate(String ccemodifyDate) {
        this.ccemodifyDate = ccemodifyDate;
    }
    public String getHcemodifyTime() {
        return this.hcemodifyTime;
    }
    
    public void setHcemodifyTime(String hcemodifyTime) {
        this.hcemodifyTime = hcemodifyTime;
    }




}


