package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaCuentasServicioEmpresaId generated by hbm2java
 */
public class TaCuentasServicioEmpresaId  implements java.io.Serializable {


     private String dcsemNumeroCuenta;
     private long csemIdServicioEmpresa;

    public TaCuentasServicioEmpresaId() {
    }

    public TaCuentasServicioEmpresaId(String dcsemNumeroCuenta, long csemIdServicioEmpresa) {
       this.dcsemNumeroCuenta = dcsemNumeroCuenta;
       this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }
   
    public String getDcsemNumeroCuenta() {
        return this.dcsemNumeroCuenta;
    }
    
    public void setDcsemNumeroCuenta(String dcsemNumeroCuenta) {
        this.dcsemNumeroCuenta = dcsemNumeroCuenta;
    }
    public long getCsemIdServicioEmpresa() {
        return this.csemIdServicioEmpresa;
    }
    
    public void setCsemIdServicioEmpresa(long csemIdServicioEmpresa) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaCuentasServicioEmpresaId) ) return false;
		 TaCuentasServicioEmpresaId castOther = ( TaCuentasServicioEmpresaId ) other; 
         
		 return ( (this.getDcsemNumeroCuenta()==castOther.getDcsemNumeroCuenta()) || ( this.getDcsemNumeroCuenta()!=null && castOther.getDcsemNumeroCuenta()!=null && this.getDcsemNumeroCuenta().equals(castOther.getDcsemNumeroCuenta()) ) )
 && (this.getCsemIdServicioEmpresa()==castOther.getCsemIdServicioEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDcsemNumeroCuenta() == null ? 0 : this.getDcsemNumeroCuenta().hashCode() );
         result = 37 * result + (int) this.getCsemIdServicioEmpresa();
         return result;
   }   


}


