package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaCuentasServicioEmpresa generated by hbm2java
 */
public class TaCuentasServicioEmpresa  implements java.io.Serializable {


     private TaCuentasServicioEmpresaId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private String dcsemTipoCuenta;
     private String dcsemDescripcion;
     private Character ccsemEstado;
     private String ccsemMoneda;
     private String ccsemModifyUser;
     private String fcsemModifyDate;
     private String hcsemModifyTime;

    public TaCuentasServicioEmpresa() {
    }

	
    public TaCuentasServicioEmpresa(TaCuentasServicioEmpresaId id, TaServicioxEmpresa taServicioxEmpresa) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public TaCuentasServicioEmpresa(TaCuentasServicioEmpresaId id, TaServicioxEmpresa taServicioxEmpresa, String dcsemTipoCuenta, String dcsemDescripcion, Character ccsemEstado, String ccsemMoneda, String ccsemModifyUser, String fcsemModifyDate, String hcsemModifyTime) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.dcsemTipoCuenta = dcsemTipoCuenta;
       this.dcsemDescripcion = dcsemDescripcion;
       this.ccsemEstado = ccsemEstado;
       this.ccsemMoneda = ccsemMoneda;
       this.ccsemModifyUser = ccsemModifyUser;
       this.fcsemModifyDate = fcsemModifyDate;
       this.hcsemModifyTime = hcsemModifyTime;
    }
   
    public TaCuentasServicioEmpresaId getId() {
        return this.id;
    }
    
    public void setId(TaCuentasServicioEmpresaId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public String getDcsemTipoCuenta() {
        return this.dcsemTipoCuenta;
    }
    
    public void setDcsemTipoCuenta(String dcsemTipoCuenta) {
        this.dcsemTipoCuenta = dcsemTipoCuenta;
    }
    public String getDcsemDescripcion() {
        return this.dcsemDescripcion;
    }
    
    public void setDcsemDescripcion(String dcsemDescripcion) {
        this.dcsemDescripcion = dcsemDescripcion;
    }
    public Character getCcsemEstado() {
        return this.ccsemEstado;
    }
    
    public void setCcsemEstado(Character ccsemEstado) {
        this.ccsemEstado = ccsemEstado;
    }
    public String getCcsemMoneda() {
        return this.ccsemMoneda;
    }
    
    public void setCcsemMoneda(String ccsemMoneda) {
        this.ccsemMoneda = ccsemMoneda;
    }
    public String getCcsemModifyUser() {
        return this.ccsemModifyUser;
    }
    
    public void setCcsemModifyUser(String ccsemModifyUser) {
        this.ccsemModifyUser = ccsemModifyUser;
    }
    public String getFcsemModifyDate() {
        return this.fcsemModifyDate;
    }
    
    public void setFcsemModifyDate(String fcsemModifyDate) {
        this.fcsemModifyDate = fcsemModifyDate;
    }
    public String getHcsemModifyTime() {
        return this.hcsemModifyTime;
    }
    
    public void setHcsemModifyTime(String hcsemModifyTime) {
        this.hcsemModifyTime = hcsemModifyTime;
    }




}


