package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaDetalleMapaCamposId generated by hbm2java
 */
public class TaDetalleMapaCamposId  implements java.io.Serializable {


     private int cdmidMapaCampos;
     private int cdmposicion;

    public TaDetalleMapaCamposId() {
    }

    public TaDetalleMapaCamposId(int cdmidMapaCampos, int cdmposicion) {
       this.cdmidMapaCampos = cdmidMapaCampos;
       this.cdmposicion = cdmposicion;
    }
   
    public int getCdmidMapaCampos() {
        return this.cdmidMapaCampos;
    }
    
    public void setCdmidMapaCampos(int cdmidMapaCampos) {
        this.cdmidMapaCampos = cdmidMapaCampos;
    }
    public int getCdmposicion() {
        return this.cdmposicion;
    }
    
    public void setCdmposicion(int cdmposicion) {
        this.cdmposicion = cdmposicion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaDetalleMapaCamposId) ) return false;
		 TaDetalleMapaCamposId castOther = ( TaDetalleMapaCamposId ) other; 
         
		 return (this.getCdmidMapaCampos()==castOther.getCdmidMapaCampos())
 && (this.getCdmposicion()==castOther.getCdmposicion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCdmidMapaCampos();
         result = 37 * result + this.getCdmposicion();
         return result;
   }   


}


