package com.hiper.cash.domain;

// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA

/**
 * TaDetalleFormato generated by hbm2java
 */
public class TaDetalleFormato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3157291751883007397L;
	private TaDetalleFormatoId id;
	private TmFormato tmFormato;
	private String ddfnombreCampo;
	private String ddftipoCampo;
	private int ndflongitudCampo;
	private String ddfformatoCampo;
	private String ddfvaloresCampo;
	private String ddfnombreCampoRef;
	private String ddfcondicional;
	private String ddfvaloresCond;
	private String descripcion;

	public TaDetalleFormato() {
	}

	public TaDetalleFormato(TaDetalleFormatoId id, TmFormato tmFormato,
			String ddfnombreCampo, String ddftipoCampo, int ndflongitudCampo) {
		this.id = id;
		this.tmFormato = tmFormato;
		this.ddfnombreCampo = ddfnombreCampo;
		this.ddftipoCampo = ddftipoCampo;
		this.ndflongitudCampo = ndflongitudCampo;
	}

	public TaDetalleFormato(TaDetalleFormatoId id, TmFormato tmFormato,
			String ddfnombreCampo, String ddftipoCampo, int ndflongitudCampo,
			String ddfformatoCampo, String ddfvaloresCampo,
			String ddfnombreCampoRef, String ddfcondicional,
			String ddfvaloresCond) {
		this.id = id;
		this.tmFormato = tmFormato;
		this.ddfnombreCampo = ddfnombreCampo;
		this.ddftipoCampo = ddftipoCampo;
		this.ndflongitudCampo = ndflongitudCampo;
		this.ddfformatoCampo = ddfformatoCampo;
		this.ddfvaloresCampo = ddfvaloresCampo;
		this.ddfnombreCampoRef = ddfnombreCampoRef;
		this.ddfcondicional = ddfcondicional;
		this.ddfvaloresCond = ddfvaloresCond;
	}

	public TaDetalleFormatoId getId() {
		return this.id;
	}

	public void setId(TaDetalleFormatoId id) {
		this.id = id;
	}

	public TmFormato getTmFormato() {
		return this.tmFormato;
	}

	public void setTmFormato(TmFormato tmFormato) {
		this.tmFormato = tmFormato;
	}

	public String getDdfnombreCampo() {
		return this.ddfnombreCampo;
	}

	public void setDdfnombreCampo(String ddfnombreCampo) {
		this.ddfnombreCampo = ddfnombreCampo;
	}

	public String getDdftipoCampo() {
		return this.ddftipoCampo;
	}

	public void setDdftipoCampo(String ddftipoCampo) {
		this.ddftipoCampo = ddftipoCampo;
	}

	public int getNdflongitudCampo() {
		return this.ndflongitudCampo;
	}

	public void setNdflongitudCampo(int ndflongitudCampo) {
		this.ndflongitudCampo = ndflongitudCampo;
	}

	public String getDdfformatoCampo() {
		return this.ddfformatoCampo;
	}

	public void setDdfformatoCampo(String ddfformatoCampo) {
		this.ddfformatoCampo = ddfformatoCampo;
	}

	public String getDdfvaloresCampo() {
		return this.ddfvaloresCampo;
	}

	public void setDdfvaloresCampo(String ddfvaloresCampo) {
		this.ddfvaloresCampo = ddfvaloresCampo;
	}

	public String getDdfnombreCampoRef() {
		return this.ddfnombreCampoRef;
	}

	public void setDdfnombreCampoRef(String ddfnombreCampoRef) {
		this.ddfnombreCampoRef = ddfnombreCampoRef;
	}

	public String getDdfcondicional() {
		return this.ddfcondicional;
	}

	public void setDdfcondicional(String ddfcondicional) {
		this.ddfcondicional = ddfcondicional;
	}

	public String getDdfvaloresCond() {
		return this.ddfvaloresCond;
	}

	public void setDdfvaloresCond(String ddfvaloresCond) {
		this.ddfvaloresCond = ddfvaloresCond;
	}

	public String getDescripcion() {
		if(descripcion!=null){
			return descripcion.trim();
		}else{
			return null;
		}		
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
