package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaEmpresaDeServicio generated by hbm2java
 */
public class TaEmpresaDeServicio  implements java.io.Serializable {


     private int cesid;
     private String desnombre;
     private String cesgrupo;
     private Character cflagOffLine;
     private String desaccion;

    public TaEmpresaDeServicio() {
    }

	
    public TaEmpresaDeServicio(int cesid) {
        this.cesid = cesid;
    }
    public TaEmpresaDeServicio(int cesid, String desnombre, String cesgrupo, Character cflagOffLine, String desaccion) {
       this.cesid = cesid;
       this.desnombre = desnombre;
       this.cesgrupo = cesgrupo;
       this.cflagOffLine = cflagOffLine;
       this.desaccion = desaccion;
    }
   
    public int getCesid() {
        return this.cesid;
    }
    
    public void setCesid(int cesid) {
        this.cesid = cesid;
    }
    public String getDesnombre() {
        return this.desnombre;
    }
    
    public void setDesnombre(String desnombre) {
        this.desnombre = desnombre;
    }
    public String getCesgrupo() {
        return this.cesgrupo;
    }
    
    public void setCesgrupo(String cesgrupo) {
        this.cesgrupo = cesgrupo;
    }
    public Character getCflagOffLine() {
        return this.cflagOffLine;
    }
    
    public void setCflagOffLine(Character cflagOffLine) {
        this.cflagOffLine = cflagOffLine;
    }
    public String getDesaccion() {
        return this.desaccion;
    }
    
    public void setDesaccion(String desaccion) {
        this.desaccion = desaccion;
    }




}


