package com.hiper.cash.domain;
// Generated 05/01/2010 03:00:57 PM by Hibernate Tools 3.2.1.GA



/**
 * TaEmpresaFormato generated by hbm2java
 */
public class TaEmpresaFormato  implements java.io.Serializable {


     private String cefidEmpresa;
     private String defxmlent;
     private String defencent;
     private String defxmlsal;
     private String defencsal;

    public TaEmpresaFormato() {
    }

	
    public TaEmpresaFormato(String cefidEmpresa) {
        this.cefidEmpresa = cefidEmpresa;
    }
    public TaEmpresaFormato(String cefidEmpresa, String defxmlent, String defencent, String defxmlsal, String defencsal) {
       this.cefidEmpresa = cefidEmpresa;
       this.defxmlent = defxmlent;
       this.defencent = defencent;
       this.defxmlsal = defxmlsal;
       this.defencsal = defencsal;
    }
   
    public String getCefidEmpresa() {
        return this.cefidEmpresa;
    }
    
    public void setCefidEmpresa(String cefidEmpresa) {
        this.cefidEmpresa = cefidEmpresa;
    }
    public String getDefxmlent() {
        return this.defxmlent;
    }
    
    public void setDefxmlent(String defxmlent) {
        this.defxmlent = defxmlent;
    }
    public String getDefencent() {
        return this.defencent;
    }
    
    public void setDefencent(String defencent) {
        this.defencent = defencent;
    }
    public String getDefxmlsal() {
        return this.defxmlsal;
    }
    
    public void setDefxmlsal(String defxmlsal) {
        this.defxmlsal = defxmlsal;
    }
    public String getDefencsal() {
        return this.defencsal;
    }
    
    public void setDefencsal(String defencsal) {
        this.defencsal = defencsal;
    }




}


