package com.hiper.cash.domain;
// Generated 23/12/2009 01:49:55 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * TaEntidadEmpresa generated by hbm2java
 */
public class TaEntidadEmpresa  implements java.io.Serializable {


     private TaEntidadEmpresaId id;
     private TaServicioEntidad taServicioEntidad;
     private String cemIdEmpresa;
     private String deenombre;
     private String deeemail;
     private String deetelefono;
     private String deedescripcion;
     private String ceetipoDocumento;
     private String neenumDocumento;
     private String deecontrapartida;
     private String deenomContrapartida;
     private String ceemodifyUser;
     private String feemodifyDate;
     private String heemodifyTime;
     private Set taServicioEntidads = new HashSet(0);
	 //jwong 11/02/2009 nuevos atributos
     private String descripcionTipoDocumento;
     private String descripcionTipoPago;

    public TaEntidadEmpresa() {
    }

	
    public TaEntidadEmpresa(TaEntidadEmpresaId id, TaServicioEntidad taServicioEntidad, String cemIdEmpresa) {
        this.id = id;
        this.taServicioEntidad = taServicioEntidad;
        this.cemIdEmpresa = cemIdEmpresa;
    }
    public TaEntidadEmpresa(TaEntidadEmpresaId id, TaServicioEntidad taServicioEntidad, String cemIdEmpresa, String deenombre, String deeemail, String deetelefono, String deedescripcion, String ceetipoDocumento, String neenumDocumento, String deecontrapartida, String deenomContrapartida, String ceemodifyUser, String feemodifyDate, String heemodifyTime,Set taServicioEntidads) {
       this.id = id;
       this.taServicioEntidad = taServicioEntidad;
       this.cemIdEmpresa = cemIdEmpresa;
       this.deenombre = deenombre;
       this.deeemail = deeemail;
       this.deetelefono = deetelefono;
       this.deedescripcion = deedescripcion;
       this.ceetipoDocumento = ceetipoDocumento;
       this.neenumDocumento = neenumDocumento;
       this.deecontrapartida = deecontrapartida;
       this.deenomContrapartida = deenomContrapartida;
       this.ceemodifyUser = ceemodifyUser;
       this.feemodifyDate = feemodifyDate;
       this.heemodifyTime = heemodifyTime;
       this.taServicioEntidads = taServicioEntidads;
    }
   
    public TaEntidadEmpresaId getId() {
        return this.id;
    }
    
    public void setId(TaEntidadEmpresaId id) {
        this.id = id;
    }
    public TaServicioEntidad getTaServicioEntidad() {
        return this.taServicioEntidad;
    }
    
    public void setTaServicioEntidad(TaServicioEntidad taServicioEntidad) {
        this.taServicioEntidad = taServicioEntidad;
    }
    public String getCemIdEmpresa() {
        return this.cemIdEmpresa;
    }
    
    public void setCemIdEmpresa(String cemIdEmpresa) {
        this.cemIdEmpresa = cemIdEmpresa;
    }
    public String getDeenombre() {
        return this.deenombre;
    }
    
    public void setDeenombre(String deenombre) {
        this.deenombre = deenombre;
    }
    public String getDeeemail() {
        return this.deeemail;
    }
    
    public void setDeeemail(String deeemail) {
        this.deeemail = deeemail;
    }
    public String getDeetelefono() {
        return this.deetelefono;
    }
    
    public void setDeetelefono(String deetelefono) {
        this.deetelefono = deetelefono;
    }
    public String getDeedescripcion() {
        return this.deedescripcion;
    }
    
    public void setDeedescripcion(String deedescripcion) {
        this.deedescripcion = deedescripcion;
    }
    public String getCeetipoDocumento() {
        return this.ceetipoDocumento;
    }
    
    public void setCeetipoDocumento(String ceetipoDocumento) {
        this.ceetipoDocumento = ceetipoDocumento;
    }
    public String getNeenumDocumento() {
        return this.neenumDocumento;
    }
    
    public void setNeenumDocumento(String neenumDocumento) {
        this.neenumDocumento = neenumDocumento;
    }
    public String getDeecontrapartida() {
        return this.deecontrapartida;
    }
    
    public void setDeecontrapartida(String deecontrapartida) {
        this.deecontrapartida = deecontrapartida;
    }
    public String getDeenomContrapartida() {
        return this.deenomContrapartida;
    }
    
    public void setDeenomContrapartida(String deenomContrapartida) {
        this.deenomContrapartida = deenomContrapartida;
    }
    public String getCeemodifyUser() {
        return this.ceemodifyUser;
    }
    
    public void setCeemodifyUser(String ceemodifyUser) {
        this.ceemodifyUser = ceemodifyUser;
    }
    public String getFeemodifyDate() {
        return this.feemodifyDate;
    }
    
    public void setFeemodifyDate(String feemodifyDate) {
        this.feemodifyDate = feemodifyDate;
    }
    public String getHeemodifyTime() {
        return this.heemodifyTime;
    }
    
    public void setHeemodifyTime(String heemodifyTime) {
        this.heemodifyTime = heemodifyTime;
    }
    public Set getTaServicioEntidads() {
        return this.taServicioEntidads;
    }

    public void setTaServicioEntidads(Set taServicioEntidads) {
        this.taServicioEntidads = taServicioEntidads;
    }
	 public String getDescripcionTipoDocumento() {
        return descripcionTipoDocumento;
    }

    public void setDescripcionTipoDocumento(String descripcionTipoDocumento) {
        this.descripcionTipoDocumento = descripcionTipoDocumento;
    }

    public String getDescripcionTipoPago() {
        return descripcionTipoPago;
    }

    public void setDescripcionTipoPago(String descripcionTipoPago) {
        this.descripcionTipoPago = descripcionTipoPago;
    }

    //jwong 12/02/2009
    public java.util.Map getParametrosUrl(){
        java.util.Map parametros = new java.util.HashMap();
        parametros.put("m_Empresa",this.cemIdEmpresa);
        parametros.put("m_IdServEmp",this.id.getCeeidServEmpresa());
        parametros.put("m_IdProveedor",this.id.getCeeidEntidad());
        parametros.put("m_IdEmpleado",this.id.getCeeidEntidad());
        parametros.put("m_IdTipo",this.id.getDeetipo());
        return parametros;
    }
}


