package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaFloorLimitId generated by hbm2java
 */
public class TaFloorLimitId  implements java.io.Serializable {


     private String cflmrProfileId;
     private String cfltransactionId;
     private String cflaplicacion;

    public TaFloorLimitId() {
    }

    public TaFloorLimitId(String cflmrProfileId, String cfltransactionId, String cflaplicacion) {
       this.cflmrProfileId = cflmrProfileId;
       this.cfltransactionId = cfltransactionId;
       this.cflaplicacion = cflaplicacion;
    }
   
    public String getCflmrProfileId() {
        return this.cflmrProfileId;
    }
    
    public void setCflmrProfileId(String cflmrProfileId) {
        this.cflmrProfileId = cflmrProfileId;
    }
    public String getCfltransactionId() {
        return this.cfltransactionId;
    }
    
    public void setCfltransactionId(String cfltransactionId) {
        this.cfltransactionId = cfltransactionId;
    }
    public String getCflaplicacion() {
        return this.cflaplicacion;
    }
    
    public void setCflaplicacion(String cflaplicacion) {
        this.cflaplicacion = cflaplicacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaFloorLimitId) ) return false;
		 TaFloorLimitId castOther = ( TaFloorLimitId ) other; 
         
		 return ( (this.getCflmrProfileId()==castOther.getCflmrProfileId()) || ( this.getCflmrProfileId()!=null && castOther.getCflmrProfileId()!=null && this.getCflmrProfileId().equals(castOther.getCflmrProfileId()) ) )
 && ( (this.getCfltransactionId()==castOther.getCfltransactionId()) || ( this.getCfltransactionId()!=null && castOther.getCfltransactionId()!=null && this.getCfltransactionId().equals(castOther.getCfltransactionId()) ) )
 && ( (this.getCflaplicacion()==castOther.getCflaplicacion()) || ( this.getCflaplicacion()!=null && castOther.getCflaplicacion()!=null && this.getCflaplicacion().equals(castOther.getCflaplicacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCflmrProfileId() == null ? 0 : this.getCflmrProfileId().hashCode() );
         result = 37 * result + ( getCfltransactionId() == null ? 0 : this.getCfltransactionId().hashCode() );
         result = 37 * result + ( getCflaplicacion() == null ? 0 : this.getCflaplicacion().hashCode() );
         return result;
   }   


}


