package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TaFloorLimit generated by hbm2java
 */
public class TaFloorLimit  implements java.io.Serializable {


     private TaFloorLimitId id;
     private TmMerchantProfile tmMerchantProfile;
     private TmTransactionType tmTransactionType;
     private BigDecimal nflfloorLimit;
     private String cflstatus;
     private BigDecimal nflfloorLimitDollar;
     private String cflmodifyUser;
     private String fflmodifyDate;
     private String hflmodifyTime;

    public TaFloorLimit() {
    }

	
    public TaFloorLimit(TaFloorLimitId id, TmMerchantProfile tmMerchantProfile, TmTransactionType tmTransactionType) {
        this.id = id;
        this.tmMerchantProfile = tmMerchantProfile;
        this.tmTransactionType = tmTransactionType;
    }
    public TaFloorLimit(TaFloorLimitId id, TmMerchantProfile tmMerchantProfile, TmTransactionType tmTransactionType, BigDecimal nflfloorLimit, String cflstatus, BigDecimal nflfloorLimitDollar, String cflmodifyUser, String fflmodifyDate, String hflmodifyTime) {
       this.id = id;
       this.tmMerchantProfile = tmMerchantProfile;
       this.tmTransactionType = tmTransactionType;
       this.nflfloorLimit = nflfloorLimit;
       this.cflstatus = cflstatus;
       this.nflfloorLimitDollar = nflfloorLimitDollar;
       this.cflmodifyUser = cflmodifyUser;
       this.fflmodifyDate = fflmodifyDate;
       this.hflmodifyTime = hflmodifyTime;
    }
   
    public TaFloorLimitId getId() {
        return this.id;
    }
    
    public void setId(TaFloorLimitId id) {
        this.id = id;
    }
    public TmMerchantProfile getTmMerchantProfile() {
        return this.tmMerchantProfile;
    }
    
    public void setTmMerchantProfile(TmMerchantProfile tmMerchantProfile) {
        this.tmMerchantProfile = tmMerchantProfile;
    }
    public TmTransactionType getTmTransactionType() {
        return this.tmTransactionType;
    }
    
    public void setTmTransactionType(TmTransactionType tmTransactionType) {
        this.tmTransactionType = tmTransactionType;
    }
    public BigDecimal getNflfloorLimit() {
        return this.nflfloorLimit;
    }
    
    public void setNflfloorLimit(BigDecimal nflfloorLimit) {
        this.nflfloorLimit = nflfloorLimit;
    }
    public String getCflstatus() {
        return this.cflstatus;
    }
    
    public void setCflstatus(String cflstatus) {
        this.cflstatus = cflstatus;
    }
    public BigDecimal getNflfloorLimitDollar() {
        return this.nflfloorLimitDollar;
    }
    
    public void setNflfloorLimitDollar(BigDecimal nflfloorLimitDollar) {
        this.nflfloorLimitDollar = nflfloorLimitDollar;
    }
    public String getCflmodifyUser() {
        return this.cflmodifyUser;
    }
    
    public void setCflmodifyUser(String cflmodifyUser) {
        this.cflmodifyUser = cflmodifyUser;
    }
    public String getFflmodifyDate() {
        return this.fflmodifyDate;
    }
    
    public void setFflmodifyDate(String fflmodifyDate) {
        this.fflmodifyDate = fflmodifyDate;
    }
    public String getHflmodifyTime() {
        return this.hflmodifyTime;
    }
    
    public void setHflmodifyTime(String hflmodifyTime) {
        this.hflmodifyTime = hflmodifyTime;
    }




}


