package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaFuncionarioEmpresa generated by hbm2java
 */
public class TaFuncionarioEmpresa  implements java.io.Serializable {


     private TaFuncionarioEmpresaId id;
     private TmEmpresa tmEmpresa;
     private TmFuncionario tmFuncionario;
     private String cfemModifyUser;
     private String ffemModifyDate;
     private String hfemModifyHour;

    public TaFuncionarioEmpresa() {
    }

	
    public TaFuncionarioEmpresa(TaFuncionarioEmpresaId id, TmEmpresa tmEmpresa, TmFuncionario tmFuncionario) {
        this.id = id;
        this.tmEmpresa = tmEmpresa;
        this.tmFuncionario = tmFuncionario;
    }
    public TaFuncionarioEmpresa(TaFuncionarioEmpresaId id, TmEmpresa tmEmpresa, TmFuncionario tmFuncionario, String cfemModifyUser, String ffemModifyDate, String hfemModifyHour) {
       this.id = id;
       this.tmEmpresa = tmEmpresa;
       this.tmFuncionario = tmFuncionario;
       this.cfemModifyUser = cfemModifyUser;
       this.ffemModifyDate = ffemModifyDate;
       this.hfemModifyHour = hfemModifyHour;
    }
   
    public TaFuncionarioEmpresaId getId() {
        return this.id;
    }
    
    public void setId(TaFuncionarioEmpresaId id) {
        this.id = id;
    }
    public TmEmpresa getTmEmpresa() {
        return this.tmEmpresa;
    }
    
    public void setTmEmpresa(TmEmpresa tmEmpresa) {
        this.tmEmpresa = tmEmpresa;
    }
    public TmFuncionario getTmFuncionario() {
        return this.tmFuncionario;
    }
    
    public void setTmFuncionario(TmFuncionario tmFuncionario) {
        this.tmFuncionario = tmFuncionario;
    }
    public String getCfemModifyUser() {
        return this.cfemModifyUser;
    }
    
    public void setCfemModifyUser(String cfemModifyUser) {
        this.cfemModifyUser = cfemModifyUser;
    }
    public String getFfemModifyDate() {
        return this.ffemModifyDate;
    }
    
    public void setFfemModifyDate(String ffemModifyDate) {
        this.ffemModifyDate = ffemModifyDate;
    }
    public String getHfemModifyHour() {
        return this.hfemModifyHour;
    }
    
    public void setHfemModifyHour(String hfemModifyHour) {
        this.hfemModifyHour = hfemModifyHour;
    }




}


