package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaFuncionarioEmpresaId generated by hbm2java
 */
public class TaFuncionarioEmpresaId  implements java.io.Serializable {


     private String cfemIdEmpresa;
     private String cfemIdFuncionario;
     private String cfemTipo;

    public TaFuncionarioEmpresaId() {
    }

    public TaFuncionarioEmpresaId(String cfemIdEmpresa, String cfemIdFuncionario, String cfemTipo) {
       this.cfemIdEmpresa = cfemIdEmpresa;
       this.cfemIdFuncionario = cfemIdFuncionario;
       this.cfemTipo = cfemTipo;
    }
   
    public String getCfemIdEmpresa() {
        return this.cfemIdEmpresa;
    }
    
    public void setCfemIdEmpresa(String cfemIdEmpresa) {
        this.cfemIdEmpresa = cfemIdEmpresa;
    }
    public String getCfemIdFuncionario() {
        return this.cfemIdFuncionario;
    }
    
    public void setCfemIdFuncionario(String cfemIdFuncionario) {
        this.cfemIdFuncionario = cfemIdFuncionario;
    }
    public String getCfemTipo() {
        return this.cfemTipo;
    }
    
    public void setCfemTipo(String cfemTipo) {
        this.cfemTipo = cfemTipo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaFuncionarioEmpresaId) ) return false;
		 TaFuncionarioEmpresaId castOther = ( TaFuncionarioEmpresaId ) other; 
         
		 return ( (this.getCfemIdEmpresa()==castOther.getCfemIdEmpresa()) || ( this.getCfemIdEmpresa()!=null && castOther.getCfemIdEmpresa()!=null && this.getCfemIdEmpresa().equals(castOther.getCfemIdEmpresa()) ) )
 && ( (this.getCfemIdFuncionario()==castOther.getCfemIdFuncionario()) || ( this.getCfemIdFuncionario()!=null && castOther.getCfemIdFuncionario()!=null && this.getCfemIdFuncionario().equals(castOther.getCfemIdFuncionario()) ) )
 && ( (this.getCfemTipo()==castOther.getCfemTipo()) || ( this.getCfemTipo()!=null && castOther.getCfemTipo()!=null && this.getCfemTipo().equals(castOther.getCfemTipo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCfemIdEmpresa() == null ? 0 : this.getCfemIdEmpresa().hashCode() );
         result = 37 * result + ( getCfemIdFuncionario() == null ? 0 : this.getCfemIdFuncionario().hashCode() );
         result = 37 * result + ( getCfemTipo() == null ? 0 : this.getCfemTipo().hashCode() );
         return result;
   }   


}


