package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaFuncionarioServicio generated by hbm2java
 */
public class TaFuncionarioServicio  implements java.io.Serializable {


     private TaFuncionarioServicioId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private TmFuncionario tmFuncionario;
     private String cfsmodifyUser;
     private String ffsmodifyDate;
     private String hfsmodifyHour;

    public TaFuncionarioServicio() {
    }

	
    public TaFuncionarioServicio(TaFuncionarioServicioId id, TaServicioxEmpresa taServicioxEmpresa, TmFuncionario tmFuncionario) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
        this.tmFuncionario = tmFuncionario;
    }
    public TaFuncionarioServicio(TaFuncionarioServicioId id, TaServicioxEmpresa taServicioxEmpresa, TmFuncionario tmFuncionario, String cfsmodifyUser, String ffsmodifyDate, String hfsmodifyHour) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.tmFuncionario = tmFuncionario;
       this.cfsmodifyUser = cfsmodifyUser;
       this.ffsmodifyDate = ffsmodifyDate;
       this.hfsmodifyHour = hfsmodifyHour;
    }
   
    public TaFuncionarioServicioId getId() {
        return this.id;
    }
    
    public void setId(TaFuncionarioServicioId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public TmFuncionario getTmFuncionario() {
        return this.tmFuncionario;
    }
    
    public void setTmFuncionario(TmFuncionario tmFuncionario) {
        this.tmFuncionario = tmFuncionario;
    }
    public String getCfsmodifyUser() {
        return this.cfsmodifyUser;
    }
    
    public void setCfsmodifyUser(String cfsmodifyUser) {
        this.cfsmodifyUser = cfsmodifyUser;
    }
    public String getFfsmodifyDate() {
        return this.ffsmodifyDate;
    }
    
    public void setFfsmodifyDate(String ffsmodifyDate) {
        this.ffsmodifyDate = ffsmodifyDate;
    }
    public String getHfsmodifyHour() {
        return this.hfsmodifyHour;
    }
    
    public void setHfsmodifyHour(String hfsmodifyHour) {
        this.hfsmodifyHour = hfsmodifyHour;
    }




}


