package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaGlosaCobroSinBdId generated by hbm2java
 */
public class TaGlosaCobroSinBdId  implements java.io.Serializable {


     private long csemIdServicioEmpresa;
     private int ngcoPosicion;

    public TaGlosaCobroSinBdId() {
    }

    public TaGlosaCobroSinBdId(long csemIdServicioEmpresa, int ngcoPosicion) {
       this.csemIdServicioEmpresa = csemIdServicioEmpresa;
       this.ngcoPosicion = ngcoPosicion;
    }
   
    public long getCsemIdServicioEmpresa() {
        return this.csemIdServicioEmpresa;
    }
    
    public void setCsemIdServicioEmpresa(long csemIdServicioEmpresa) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }
    public int getNgcoPosicion() {
        return this.ngcoPosicion;
    }
    
    public void setNgcoPosicion(int ngcoPosicion) {
        this.ngcoPosicion = ngcoPosicion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaGlosaCobroSinBdId) ) return false;
		 TaGlosaCobroSinBdId castOther = ( TaGlosaCobroSinBdId ) other; 
         
		 return (this.getCsemIdServicioEmpresa()==castOther.getCsemIdServicioEmpresa())
 && (this.getNgcoPosicion()==castOther.getNgcoPosicion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCsemIdServicioEmpresa();
         result = 37 * result + this.getNgcoPosicion();
         return result;
   }   


}


