package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaGlosaCobroSinBd generated by hbm2java
 */
public class TaGlosaCobroSinBd  implements java.io.Serializable {


     private TaGlosaCobroSinBdId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private String dgcoEtiqueta;
     private String dgcoNomVariable;
     private String dgcoDescripcion;
     private Integer ngcoLongitudCampo;
     private String dgcoTipoDato;
     private Character cgcoFlagObligatorio;
     private String dgcoControl;

    public TaGlosaCobroSinBd() {
    }

	
    public TaGlosaCobroSinBd(TaGlosaCobroSinBdId id, TaServicioxEmpresa taServicioxEmpresa) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public TaGlosaCobroSinBd(TaGlosaCobroSinBdId id, TaServicioxEmpresa taServicioxEmpresa, String dgcoEtiqueta, String dgcoNomVariable, String dgcoDescripcion, Integer ngcoLongitudCampo, String dgcoTipoDato, Character cgcoFlagObligatorio, String dgcoControl) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.dgcoEtiqueta = dgcoEtiqueta;
       this.dgcoNomVariable = dgcoNomVariable;
       this.dgcoDescripcion = dgcoDescripcion;
       this.ngcoLongitudCampo = ngcoLongitudCampo;
       this.dgcoTipoDato = dgcoTipoDato;
       this.cgcoFlagObligatorio = cgcoFlagObligatorio;
       this.dgcoControl = dgcoControl;
    }
   
    public TaGlosaCobroSinBdId getId() {
        return this.id;
    }
    
    public void setId(TaGlosaCobroSinBdId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public String getDgcoEtiqueta() {
        return this.dgcoEtiqueta;
    }
    
    public void setDgcoEtiqueta(String dgcoEtiqueta) {
        this.dgcoEtiqueta = dgcoEtiqueta;
    }
    public String getDgcoNomVariable() {
        return this.dgcoNomVariable;
    }
    
    public void setDgcoNomVariable(String dgcoNomVariable) {
        this.dgcoNomVariable = dgcoNomVariable;
    }
    public String getDgcoDescripcion() {
        return this.dgcoDescripcion;
    }
    
    public void setDgcoDescripcion(String dgcoDescripcion) {
        this.dgcoDescripcion = dgcoDescripcion;
    }
    public Integer getNgcoLongitudCampo() {
        return this.ngcoLongitudCampo;
    }
    
    public void setNgcoLongitudCampo(Integer ngcoLongitudCampo) {
        this.ngcoLongitudCampo = ngcoLongitudCampo;
    }
    public String getDgcoTipoDato() {
        return this.dgcoTipoDato;
    }
    
    public void setDgcoTipoDato(String dgcoTipoDato) {
        this.dgcoTipoDato = dgcoTipoDato;
    }
    public Character getCgcoFlagObligatorio() {
        return this.cgcoFlagObligatorio;
    }
    
    public void setCgcoFlagObligatorio(Character cgcoFlagObligatorio) {
        this.cgcoFlagObligatorio = cgcoFlagObligatorio;
    }
    public String getDgcoControl() {
        return this.dgcoControl;
    }
    
    public void setDgcoControl(String dgcoControl) {
        this.dgcoControl = dgcoControl;
    }




}


