package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaLogValidacionId generated by hbm2java
 */
public class TaLogValidacionId  implements java.io.Serializable {


     private int clvaIdEnvio;
     private long nlvaNumLinea;

    public TaLogValidacionId() {
    }

    public TaLogValidacionId(int clvaIdEnvio, long nlvaNumLinea) {
       this.clvaIdEnvio = clvaIdEnvio;
       this.nlvaNumLinea = nlvaNumLinea;
    }
   
    public int getClvaIdEnvio() {
        return this.clvaIdEnvio;
    }
    
    public void setClvaIdEnvio(int clvaIdEnvio) {
        this.clvaIdEnvio = clvaIdEnvio;
    }
    public long getNlvaNumLinea() {
        return this.nlvaNumLinea;
    }
    
    public void setNlvaNumLinea(long nlvaNumLinea) {
        this.nlvaNumLinea = nlvaNumLinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaLogValidacionId) ) return false;
		 TaLogValidacionId castOther = ( TaLogValidacionId ) other; 
         
		 return (this.getClvaIdEnvio()==castOther.getClvaIdEnvio())
 && (this.getNlvaNumLinea()==castOther.getNlvaNumLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClvaIdEnvio();
         result = 37 * result + (int) this.getNlvaNumLinea();
         return result;
   }   


}


