package com.hiper.cash.domain;

import org.apache.commons.lang.builder.ToStringBuilder;

// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA

/**
 * TaLogValidacion generated by hbm2java
 */
public class TaLogValidacion implements java.io.Serializable
{

    private TaLogValidacionId id;

    private String dlvaDescripcion;

    private String enlace;

    public TaLogValidacion()
    {
    }

    public TaLogValidacion(TaLogValidacionId id)
    {
        this.id = id;
    }

    public TaLogValidacion(TaLogValidacionId id, String dlvaDescripcion, String enlace)
    {
        this.id = id;
        this.dlvaDescripcion = dlvaDescripcion;
        this.enlace = enlace;
    }

    public TaLogValidacionId getId()
    {
        return this.id;
    }

    public void setId(TaLogValidacionId id)
    {
        this.id = id;
    }

    public String getDlvaDescripcion()
    {
        return this.dlvaDescripcion;
    }

    public void setDlvaDescripcion(String dlvaDescripcion)
    {
        this.dlvaDescripcion = dlvaDescripcion;
    }

    public String getEnlace()
    {
        return enlace;
    }

    public void setEnlace(String enlace)
    {
        this.enlace = enlace;
    }

    public String printValues()
    {
        String toPrint = "";
        if (id != null)
        {
            toPrint = new ToStringBuilder(this.id).append("clvaIdEnvio", id.getClvaIdEnvio())
                    .append("nlvaNumLinea", id.getNlvaNumLinea()).toString();
        }
        toPrint += new ToStringBuilder(this).append("dlvaDescripcion", dlvaDescripcion).toString();
        return toPrint;
    }

}
