package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TaMapaCampos generated by hbm2java
 */
public class TaMapaCampos  implements java.io.Serializable {


     private int cmcidMapaCampos;
     private String dmcnombre;
     private String cmcmodifyUser;
     private String fmcmodifyDate;
     private String hmcmodifyTime;
     private Set taServicioxEmpresas = new HashSet(0);
     private Set taDetalleMapaCamposes = new HashSet(0);

    public TaMapaCampos() {
    }

	
    public TaMapaCampos(int cmcidMapaCampos) {
        this.cmcidMapaCampos = cmcidMapaCampos;
    }
    public TaMapaCampos(int cmcidMapaCampos, String dmcnombre, String cmcmodifyUser, String fmcmodifyDate, String hmcmodifyTime, Set taServicioxEmpresas, Set taDetalleMapaCamposes) {
       this.cmcidMapaCampos = cmcidMapaCampos;
       this.dmcnombre = dmcnombre;
       this.cmcmodifyUser = cmcmodifyUser;
       this.fmcmodifyDate = fmcmodifyDate;
       this.hmcmodifyTime = hmcmodifyTime;
       this.taServicioxEmpresas = taServicioxEmpresas;
       this.taDetalleMapaCamposes = taDetalleMapaCamposes;
    }
   
    public int getCmcidMapaCampos() {
        return this.cmcidMapaCampos;
    }
    
    public void setCmcidMapaCampos(int cmcidMapaCampos) {
        this.cmcidMapaCampos = cmcidMapaCampos;
    }
    public String getDmcnombre() {
        return this.dmcnombre;
    }
    
    public void setDmcnombre(String dmcnombre) {
        this.dmcnombre = dmcnombre;
    }
    public String getCmcmodifyUser() {
        return this.cmcmodifyUser;
    }
    
    public void setCmcmodifyUser(String cmcmodifyUser) {
        this.cmcmodifyUser = cmcmodifyUser;
    }
    public String getFmcmodifyDate() {
        return this.fmcmodifyDate;
    }
    
    public void setFmcmodifyDate(String fmcmodifyDate) {
        this.fmcmodifyDate = fmcmodifyDate;
    }
    public String getHmcmodifyTime() {
        return this.hmcmodifyTime;
    }
    
    public void setHmcmodifyTime(String hmcmodifyTime) {
        this.hmcmodifyTime = hmcmodifyTime;
    }
    public Set getTaServicioxEmpresas() {
        return this.taServicioxEmpresas;
    }
    
    public void setTaServicioxEmpresas(Set taServicioxEmpresas) {
        this.taServicioxEmpresas = taServicioxEmpresas;
    }
    public Set getTaDetalleMapaCamposes() {
        return this.taDetalleMapaCamposes;
    }
    
    public void setTaDetalleMapaCamposes(Set taDetalleMapaCamposes) {
        this.taDetalleMapaCamposes = taDetalleMapaCamposes;
    }




}


