package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaMerchantProfileApplicationId generated by hbm2java
 */
public class TaMerchantProfileApplicationId  implements java.io.Serializable {


     private String cmamerchantProfileId;
     private String cmaapplicationId;

    public TaMerchantProfileApplicationId() {
    }

    public TaMerchantProfileApplicationId(String cmamerchantProfileId, String cmaapplicationId) {
       this.cmamerchantProfileId = cmamerchantProfileId;
       this.cmaapplicationId = cmaapplicationId;
    }
   
    public String getCmamerchantProfileId() {
        return this.cmamerchantProfileId;
    }
    
    public void setCmamerchantProfileId(String cmamerchantProfileId) {
        this.cmamerchantProfileId = cmamerchantProfileId;
    }
    public String getCmaapplicationId() {
        return this.cmaapplicationId;
    }
    
    public void setCmaapplicationId(String cmaapplicationId) {
        this.cmaapplicationId = cmaapplicationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaMerchantProfileApplicationId) ) return false;
		 TaMerchantProfileApplicationId castOther = ( TaMerchantProfileApplicationId ) other; 
         
		 return ( (this.getCmamerchantProfileId()==castOther.getCmamerchantProfileId()) || ( this.getCmamerchantProfileId()!=null && castOther.getCmamerchantProfileId()!=null && this.getCmamerchantProfileId().equals(castOther.getCmamerchantProfileId()) ) )
 && ( (this.getCmaapplicationId()==castOther.getCmaapplicationId()) || ( this.getCmaapplicationId()!=null && castOther.getCmaapplicationId()!=null && this.getCmaapplicationId().equals(castOther.getCmaapplicationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCmamerchantProfileId() == null ? 0 : this.getCmamerchantProfileId().hashCode() );
         result = 37 * result + ( getCmaapplicationId() == null ? 0 : this.getCmaapplicationId().hashCode() );
         return result;
   }   


}


