package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaOrdenId generated by hbm2java
 */
public class TaOrdenId  implements java.io.Serializable {


     private long corIdOrden;
     private long corIdServicioEmpresa;

    public TaOrdenId() {
    }

    public TaOrdenId(long corIdOrden, long corIdServicioEmpresa) {
       this.corIdOrden = corIdOrden;
       this.corIdServicioEmpresa = corIdServicioEmpresa;
    }
   
    public long getCorIdOrden() {
        return this.corIdOrden;
    }
    
    public void setCorIdOrden(long corIdOrden) {
        this.corIdOrden = corIdOrden;
    }
    public long getCorIdServicioEmpresa() {
        return this.corIdServicioEmpresa;
    }
    
    public void setCorIdServicioEmpresa(long corIdServicioEmpresa) {
        this.corIdServicioEmpresa = corIdServicioEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaOrdenId) ) return false;
		 TaOrdenId castOther = ( TaOrdenId ) other; 
         
		 return (this.getCorIdOrden()==castOther.getCorIdOrden())
 && (this.getCorIdServicioEmpresa()==castOther.getCorIdServicioEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCorIdOrden();
         result = 37 * result + (int) this.getCorIdServicioEmpresa();
         return result;
   }   


}


