package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TaOrden generated by hbm2java
 */
public class TaOrden  implements java.io.Serializable {


     private TaOrdenId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private String forFechaRegistro;
     private String forFechaInicio;
     private String horHoraInicio;
     private String forFechaFin;
     private char corEstado;
     private String dorReferencia;
     private Character dorTipoIngreso;
     private String dorTipoCuenta;
     private String norNumeroCuenta;
     private Integer norNumeroRegistros;
     private String corMoneda;
     private BigDecimal norMontoSoles;
     private char corEstadoMontoSoles;
     private BigDecimal norMontoDolares;
     private char corEstadoMontoDolares;
     private BigDecimal norMontoEuros;
     private char corEstadoMontoEuros;
     private BigDecimal norMontoA;
     private BigDecimal norMontoB;
     private Set taAprobacionOrdens = new HashSet(0);
  
     private List<TpDetalleOrden> tpDetalleOrdens = new ArrayList<TpDetalleOrden>();

     private String corcodRptaIbsSoles;
     private String corcodRptaIbsDolares;
     private String corcodRptaIbsEuros;
	 //Adicionales -esilva
     private String m_Empresa;
     private String m_Servicio;
     private String m_IdServicio;
     private String m_DescCuenta;
     private String m_DescHora;
     private Character m_FlagAprobAut;
     private String nombreEmpresa;
     private String nombreServicio;
     private String nombreEstado;
	 
    public TaOrden() {
    }

	
    public TaOrden(TaOrdenId id, TaServicioxEmpresa taServicioxEmpresa, String forFechaRegistro, String forFechaInicio, String forFechaFin, char corEstado, String norNumeroCuenta, char corEstadoMontoSoles, char corEstadoMontoDolares, char corEstadoMontoEuros) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
        this.forFechaRegistro = forFechaRegistro;
        this.forFechaInicio = forFechaInicio;
        this.forFechaFin = forFechaFin;
        this.corEstado = corEstado;
        this.norNumeroCuenta = norNumeroCuenta;
        this.corEstadoMontoSoles = corEstadoMontoSoles;
        this.corEstadoMontoDolares = corEstadoMontoDolares;
        this.corEstadoMontoEuros = corEstadoMontoEuros;
    }
    public TaOrden(TaOrdenId id, TaServicioxEmpresa taServicioxEmpresa, String forFechaRegistro, String forFechaInicio, String horHoraInicio, String forFechaFin, char corEstado, String dorReferencia, Character dorTipoIngreso, String dorTipoCuenta, String norNumeroCuenta, Integer norNumeroRegistros, String corMoneda, BigDecimal norMontoSoles, char corEstadoMontoSoles, BigDecimal norMontoDolares, char corEstadoMontoDolares, BigDecimal norMontoEuros, char corEstadoMontoEuros, BigDecimal norMontoA, BigDecimal norMontoB, Set taAprobacionOrdens, List<TpDetalleOrden> tpDetalleOrdens,
            String corcodRptaIbsSoles,String corcodRptaIbsDolares,String corcodRptaIbsEuros) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.forFechaRegistro = forFechaRegistro;
       this.forFechaInicio = forFechaInicio;
       this.horHoraInicio = horHoraInicio;
       this.forFechaFin = forFechaFin;
       this.corEstado = corEstado;
       this.dorReferencia = dorReferencia;
       this.dorTipoIngreso = dorTipoIngreso;
       this.dorTipoCuenta = dorTipoCuenta;
       this.norNumeroCuenta = norNumeroCuenta;
       this.norNumeroRegistros = norNumeroRegistros;
       this.corMoneda = corMoneda;
       this.norMontoSoles = norMontoSoles;
       this.corEstadoMontoSoles = corEstadoMontoSoles;
       this.norMontoDolares = norMontoDolares;
       this.corEstadoMontoDolares = corEstadoMontoDolares;
       this.norMontoEuros = norMontoEuros;
       this.corEstadoMontoEuros = corEstadoMontoEuros;
       this.norMontoA = norMontoA;
       this.norMontoB = norMontoB;
       this.taAprobacionOrdens = taAprobacionOrdens;
       this.tpDetalleOrdens = tpDetalleOrdens;
       this.corcodRptaIbsSoles = corcodRptaIbsSoles;
       this.corcodRptaIbsDolares = corcodRptaIbsDolares;
       this.corcodRptaIbsEuros = corcodRptaIbsEuros;
    }
   
    public TaOrdenId getId() {
        return this.id;
    }
    
    public void setId(TaOrdenId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public String getForFechaRegistro() {
        return this.forFechaRegistro;
    }
    
    public void setForFechaRegistro(String forFechaRegistro) {
        this.forFechaRegistro = forFechaRegistro;
    }
    public String getForFechaInicio() {
        return this.forFechaInicio;
    }
    
    public void setForFechaInicio(String forFechaInicio) {
        this.forFechaInicio = forFechaInicio;
    }
    public String getHorHoraInicio() {
        return this.horHoraInicio;
    }
    
    public void setHorHoraInicio(String horHoraInicio) {
        this.horHoraInicio = horHoraInicio;
    }
    public String getForFechaFin() {
        return this.forFechaFin;
    }
    
    public void setForFechaFin(String forFechaFin) {
        this.forFechaFin = forFechaFin;
    }
    public char getCorEstado() {
        return this.corEstado;
    }
    
    public void setCorEstado(char corEstado) {
        this.corEstado = corEstado;
    }
    public String getDorReferencia() {
        return this.dorReferencia;
    }
    
    public void setDorReferencia(String dorReferencia) {
        this.dorReferencia = dorReferencia;
    }
    public Character getDorTipoIngreso() {
        return this.dorTipoIngreso;
    }
    
    public void setDorTipoIngreso(Character dorTipoIngreso) {
        this.dorTipoIngreso = dorTipoIngreso;
    }
    public String getDorTipoCuenta() {
        return this.dorTipoCuenta;
    }
    
    public void setDorTipoCuenta(String dorTipoCuenta) {
        this.dorTipoCuenta = dorTipoCuenta;
    }
    public String getNorNumeroCuenta() {
        return this.norNumeroCuenta;
    }
    
    public void setNorNumeroCuenta(String norNumeroCuenta) {
        this.norNumeroCuenta = norNumeroCuenta;
    }
    public Integer getNorNumeroRegistros() {
        return this.norNumeroRegistros;
    }
    
    public void setNorNumeroRegistros(Integer norNumeroRegistros) {
        this.norNumeroRegistros = norNumeroRegistros;
    }
    public String getCorMoneda() {
        return this.corMoneda;
    }
    
    public void setCorMoneda(String corMoneda) {
        this.corMoneda = corMoneda;
    }
    public BigDecimal getNorMontoSoles() {
        return this.norMontoSoles;
    }
    
    public void setNorMontoSoles(BigDecimal norMontoSoles) {
        this.norMontoSoles = norMontoSoles;
    }
    public char getCorEstadoMontoSoles() {
        return this.corEstadoMontoSoles;
    }
    
    public void setCorEstadoMontoSoles(char corEstadoMontoSoles) {
        this.corEstadoMontoSoles = corEstadoMontoSoles;
    }
    public BigDecimal getNorMontoDolares() {
        return this.norMontoDolares;
    }
    
    public void setNorMontoDolares(BigDecimal norMontoDolares) {
        this.norMontoDolares = norMontoDolares;
    }
    public char getCorEstadoMontoDolares() {
        return this.corEstadoMontoDolares;
    }
    
    public void setCorEstadoMontoDolares(char corEstadoMontoDolares) {
        this.corEstadoMontoDolares = corEstadoMontoDolares;
    }
    public BigDecimal getNorMontoEuros() {
        return this.norMontoEuros;
    }
    
    public void setNorMontoEuros(BigDecimal norMontoEuros) {
        this.norMontoEuros = norMontoEuros;
    }
    public char getCorEstadoMontoEuros() {
        return this.corEstadoMontoEuros;
    }
    
    public void setCorEstadoMontoEuros(char corEstadoMontoEuros) {
        this.corEstadoMontoEuros = corEstadoMontoEuros;
    }
    public BigDecimal getNorMontoA() {
        return this.norMontoA;
    }
    
    public void setNorMontoA(BigDecimal norMontoA) {
        this.norMontoA = norMontoA;
    }
    public BigDecimal getNorMontoB() {
        return this.norMontoB;
    }
    
    public void setNorMontoB(BigDecimal norMontoB) {
        this.norMontoB = norMontoB;
    }
    public Set getTaAprobacionOrdens() {
        return this.taAprobacionOrdens;
    }
    
    public void setTaAprobacionOrdens(Set taAprobacionOrdens) {
        this.taAprobacionOrdens = taAprobacionOrdens;
    }
   
    public void setTpDetalleOrdens(List<TpDetalleOrden> tpDetalleOrdens) {
		this.tpDetalleOrdens = tpDetalleOrdens;
	}
    
    public List<TpDetalleOrden> getTpDetalleOrdens() {
		return tpDetalleOrdens;
	}

    public String getM_Empresa() {
        return m_Empresa;
    }

    public void setM_Empresa(String m_Empresa) {
        this.m_Empresa = m_Empresa;
    }

    public String getM_Servicio() {
        return m_Servicio;
    }

    public void setM_Servicio(String m_Servicio) {
        this.m_Servicio = m_Servicio;
    }

    public String getM_IdServicio() {
        return m_IdServicio;
    }

    public void setM_IdServicio(String m_IdServicio) {
        this.m_IdServicio = m_IdServicio;
    }

    public String getM_DescCuenta() {
        return m_DescCuenta;
    }

    public void setM_DescCuenta(String m_DescCuenta) {
        this.m_DescCuenta = m_DescCuenta;
    }

    public String getM_DescHora() {
        return m_DescHora;
    }

    public void setM_DescHora(String m_DescHora) {
        this.m_DescHora = m_DescHora;
    }

    public Character getM_FlagAprobAut() {
        return m_FlagAprobAut;
    }

    public void setM_FlagAprobAut(Character m_FlagAprobAut) {
        this.m_FlagAprobAut = m_FlagAprobAut;
    }

    public String getCorcodRptaIbsSoles() {
        return corcodRptaIbsSoles;
    }

    public void setCorcodRptaIbsSoles(String corcodRptaIbsSoles) {
        this.corcodRptaIbsSoles = corcodRptaIbsSoles;
    }

    public String getCorcodRptaIbsDolares() {
        return corcodRptaIbsDolares;
    }

    public void setCorcodRptaIbsDolares(String corcodRptaIbsDolares) {
        this.corcodRptaIbsDolares = corcodRptaIbsDolares;
    }

    public String getCorcodRptaIbsEuros() {
        return corcodRptaIbsEuros;
    }

    public void setCorcodRptaIbsEuros(String corcodRptaIbsEuros) {
        this.corcodRptaIbsEuros = corcodRptaIbsEuros;
    }       

    public String getNombreEmpresa() {
		return nombreEmpresa;
	}


	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}
		
	public String getNombreServicio() {
		return nombreServicio;
	}

	public void setNombreServicio(String nombreServicio) {
		this.nombreServicio = nombreServicio;
	}
		
	public String getNombreEstado() {
		return nombreEstado;
	}


	public void setNombreEstado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}


	@Override
    public String toString() {
    	return String.valueOf(this.getId().getCorIdOrden());
    }
}


