package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaSecuencial generated by hbm2java
 */
public class TaSecuencial  implements java.io.Serializable {


     private String cseId;
     private Integer nseUltValor;

    public TaSecuencial() {
    }

	
    public TaSecuencial(String cseId) {
        this.cseId = cseId;
    }
    public TaSecuencial(String cseId, Integer nseUltValor) {
       this.cseId = cseId;
       this.nseUltValor = nseUltValor;
    }
   
    public String getCseId() {
        return this.cseId;
    }
    
    public void setCseId(String cseId) {
        this.cseId = cseId;
    }
    public Integer getNseUltValor() {
        return this.nseUltValor;
    }
    
    public void setNseUltValor(Integer nseUltValor) {
        this.nseUltValor = nseUltValor;
    }




}


