package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaServicioOpcionId generated by hbm2java
 */
public class TaServicioOpcionId  implements java.io.Serializable {


     private String csoservicioId;
     private String csoproceso;
     private String csomodulo;

    public TaServicioOpcionId() {
    }

    public TaServicioOpcionId(String csoservicioId, String csoproceso, String csomodulo) {
       this.csoservicioId = csoservicioId;
       this.csoproceso = csoproceso;
       this.csomodulo = csomodulo;
    }
   
    public String getCsoservicioId() {
        return this.csoservicioId;
    }
    
    public void setCsoservicioId(String csoservicioId) {
        this.csoservicioId = csoservicioId;
    }
    public String getCsoproceso() {
        return this.csoproceso;
    }
    
    public void setCsoproceso(String csoproceso) {
        this.csoproceso = csoproceso;
    }
    public String getCsomodulo() {
        return this.csomodulo;
    }
    
    public void setCsomodulo(String csomodulo) {
        this.csomodulo = csomodulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaServicioOpcionId) ) return false;
		 TaServicioOpcionId castOther = ( TaServicioOpcionId ) other; 
         
		 return ( (this.getCsoservicioId()==castOther.getCsoservicioId()) || ( this.getCsoservicioId()!=null && castOther.getCsoservicioId()!=null && this.getCsoservicioId().equals(castOther.getCsoservicioId()) ) )
 && ( (this.getCsoproceso()==castOther.getCsoproceso()) || ( this.getCsoproceso()!=null && castOther.getCsoproceso()!=null && this.getCsoproceso().equals(castOther.getCsoproceso()) ) )
 && ( (this.getCsomodulo()==castOther.getCsomodulo()) || ( this.getCsomodulo()!=null && castOther.getCsomodulo()!=null && this.getCsomodulo().equals(castOther.getCsomodulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCsoservicioId() == null ? 0 : this.getCsoservicioId().hashCode() );
         result = 37 * result + ( getCsoproceso() == null ? 0 : this.getCsoproceso().hashCode() );
         result = 37 * result + ( getCsomodulo() == null ? 0 : this.getCsomodulo().hashCode() );
         return result;
   }   


}


