package com.hiper.cash.domain;
// Generated 23/12/2009 01:49:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TaServicioEntidadId generated by hbm2java
 */
public class TaServicioEntidadId  implements java.io.Serializable {


     private long csenIdServEmp;
     private String csenIdEntidad;
     private String csenTipoEntidad;

    public TaServicioEntidadId() {
    }

    public TaServicioEntidadId(long csenIdServEmp, String csenIdEntidad, String csenTipoEntidad) {
       this.csenIdServEmp = csenIdServEmp;
       this.csenIdEntidad = csenIdEntidad;
       this.csenTipoEntidad = csenTipoEntidad;
    }
   
    public long getCsenIdServEmp() {
        return this.csenIdServEmp;
    }
    
    public void setCsenIdServEmp(long csenIdServEmp) {
        this.csenIdServEmp = csenIdServEmp;
    }
    public String getCsenIdEntidad() {
        return this.csenIdEntidad;
    }
    
    public void setCsenIdEntidad(String csenIdEntidad) {
        this.csenIdEntidad = csenIdEntidad;
    }
    public String getCsenTipoEntidad() {
        return this.csenTipoEntidad;
    }
    
    public void setCsenTipoEntidad(String csenTipoEntidad) {
        this.csenTipoEntidad = csenTipoEntidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaServicioEntidadId) ) return false;
		 TaServicioEntidadId castOther = ( TaServicioEntidadId ) other; 
         
		 return (this.getCsenIdServEmp()==castOther.getCsenIdServEmp())
 && ( (this.getCsenIdEntidad()==castOther.getCsenIdEntidad()) || ( this.getCsenIdEntidad()!=null && castOther.getCsenIdEntidad()!=null && this.getCsenIdEntidad().equals(castOther.getCsenIdEntidad()) ) )
 && ( (this.getCsenTipoEntidad()==castOther.getCsenTipoEntidad()) || ( this.getCsenTipoEntidad()!=null && castOther.getCsenTipoEntidad()!=null && this.getCsenTipoEntidad().equals(castOther.getCsenTipoEntidad()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCsenIdServEmp();
         result = 37 * result + ( getCsenIdEntidad() == null ? 0 : this.getCsenIdEntidad().hashCode() );
         result = 37 * result + ( getCsenTipoEntidad() == null ? 0 : this.getCsenTipoEntidad().hashCode() );
         return result;
   }   


}


