package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TaServicioxEmpresa generated by hbm2java
 */
public class TaServicioxEmpresa  implements java.io.Serializable {


     private long csemIdServicioEmpresa;
     private TmEmpresa tmEmpresa;
     private TaTarifa taTarifa;
     private TmServicio tmServicio;
     private TaMapaCampos taMapaCampos;
     private String fsemFechaInicio;
     private String fsemFechaFin;
     private Character dsemRenovacionAut;
     private String dsemMotivo;
     private String dsemMoneda;
     private String dsemTipoAprobacion;
     private Integer nsemNumeroAprobadores;
     private char csemEstado;
     private String dsemFormatoArchivo;
     private Character csemFlagPagoParcial;
     private Character csemFlagEjecucion;
     private Character csemPeriodoCobro;
     private BigDecimal nsemMontoAbonado;
     private String fsemFechaVenc;
     private Integer cseformatoEntrada;
     private Integer cseformatoSalida;
     private String csemModifyUser;
     private String fsemModifyDate;
     private String hsemModifyTime;
     private Character csemFlagAprobAut;
     private Set tpDetalleCobroSinBds = new HashSet(0);
     private Set taOrdens = new HashSet(0);
     private Set taGlosaCobroSinBds = new HashSet(0);
     private Set taServicioEntidads = new HashSet(0);
     private Set taTipoPagoServicios = new HashSet(0);
     private Set taFuncionarioServicios = new HashSet(0);
     private Set taAprobadorServicios = new HashSet(0);
     private Set taCuentasServicioEmpresas = new HashSet(0);     
	//Adicionales
     private String tipoServicio;
     private String dsemDescripcion;
    public TaServicioxEmpresa() {
    }

	
    public TaServicioxEmpresa(long csemIdServicioEmpresa, TmEmpresa tmEmpresa, TmServicio tmServicio, char csemEstado) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
        this.tmEmpresa = tmEmpresa;
        this.tmServicio = tmServicio;
        this.csemEstado = csemEstado;
    }
    public TaServicioxEmpresa(long csemIdServicioEmpresa, TmEmpresa tmEmpresa, TaTarifa taTarifa, TmServicio tmServicio,
            TaMapaCampos taMapaCampos, String fsemFechaInicio, String fsemFechaFin, Character dsemRenovacionAut,
            String dsemMotivo, String dsemMoneda, String dsemTipoAprobacion, Integer nsemNumeroAprobadores,
            char csemEstado, String dsemFormatoArchivo, Character csemFlagPagoParcial, Character csemFlagEjecucion,
            Character csemPeriodoCobro, BigDecimal nsemMontoAbonado, String fsemFechaVenc, Integer cseformatoEntrada,
            Integer cseformatoSalida, String csemModifyUser, String fsemModifyDate, String hsemModifyTime,
            Character csemFlagAprobAut, Set tpDetalleCobroSinBds, Set taOrdens, Set taGlosaCobroSinBds,
            Set taServicioEntidads, Set taTipoPagoServicios, Set taFuncionarioServicios, Set taAprobadorServicios,
            Set taCuentasServicioEmpresas,String dsemDescripcion) {
       this.csemIdServicioEmpresa = csemIdServicioEmpresa;
       this.tmEmpresa = tmEmpresa;
       this.taTarifa = taTarifa;
       this.tmServicio = tmServicio;
       this.taMapaCampos = taMapaCampos;
       this.fsemFechaInicio = fsemFechaInicio;
       this.fsemFechaFin = fsemFechaFin;
       this.dsemRenovacionAut = dsemRenovacionAut;
       this.dsemMotivo = dsemMotivo;
       this.dsemMoneda = dsemMoneda;
       this.dsemTipoAprobacion = dsemTipoAprobacion;
       this.nsemNumeroAprobadores = nsemNumeroAprobadores;
       this.csemEstado = csemEstado;
       this.dsemFormatoArchivo = dsemFormatoArchivo;
       this.csemFlagPagoParcial = csemFlagPagoParcial;
       this.csemFlagEjecucion = csemFlagEjecucion;
       this.csemPeriodoCobro = csemPeriodoCobro;
       this.nsemMontoAbonado = nsemMontoAbonado;
       this.fsemFechaVenc = fsemFechaVenc;
       this.cseformatoEntrada = cseformatoEntrada;
       this.cseformatoSalida = cseformatoSalida;
       this.csemModifyUser = csemModifyUser;
       this.fsemModifyDate = fsemModifyDate;
       this.hsemModifyTime = hsemModifyTime;
       this.csemFlagAprobAut = csemFlagAprobAut;
       this.tpDetalleCobroSinBds = tpDetalleCobroSinBds;
       this.taOrdens = taOrdens;
       this.taGlosaCobroSinBds = taGlosaCobroSinBds;
       this.taServicioEntidads = taServicioEntidads;
       this.taTipoPagoServicios = taTipoPagoServicios;
       this.taFuncionarioServicios = taFuncionarioServicios;
       this.taAprobadorServicios = taAprobadorServicios;
       this.taCuentasServicioEmpresas = taCuentasServicioEmpresas;
       this.dsemDescripcion = dsemDescripcion;
    }
   
    public long getCsemIdServicioEmpresa() {
        return this.csemIdServicioEmpresa;
    }
    
    public void setCsemIdServicioEmpresa(long csemIdServicioEmpresa) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }
    public TmEmpresa getTmEmpresa() {
        return this.tmEmpresa;
    }
    
    public void setTmEmpresa(TmEmpresa tmEmpresa) {
        this.tmEmpresa = tmEmpresa;
    }
    public TaTarifa getTaTarifa() {
        return this.taTarifa;
    }
    
    public void setTaTarifa(TaTarifa taTarifa) {
        this.taTarifa = taTarifa;
    }
    public TmServicio getTmServicio() {
        return this.tmServicio;
    }
    
    public void setTmServicio(TmServicio tmServicio) {
        this.tmServicio = tmServicio;
    }
    public TaMapaCampos getTaMapaCampos() {
        return this.taMapaCampos;
    }
    
    public void setTaMapaCampos(TaMapaCampos taMapaCampos) {
        this.taMapaCampos = taMapaCampos;
    }
    public String getFsemFechaInicio() {
        return this.fsemFechaInicio;
    }
    
    public void setFsemFechaInicio(String fsemFechaInicio) {
        this.fsemFechaInicio = fsemFechaInicio;
    }
    public String getFsemFechaFin() {
        return this.fsemFechaFin;
    }
    
    public void setFsemFechaFin(String fsemFechaFin) {
        this.fsemFechaFin = fsemFechaFin;
    }
    public Character getDsemRenovacionAut() {
        return this.dsemRenovacionAut;
    }
    
    public void setDsemRenovacionAut(Character dsemRenovacionAut) {
        this.dsemRenovacionAut = dsemRenovacionAut;
    }
    public String getDsemMotivo() {
        return this.dsemMotivo;
    }
    
    public void setDsemMotivo(String dsemMotivo) {
        this.dsemMotivo = dsemMotivo;
    }
    public String getDsemMoneda() {
        return this.dsemMoneda;
    }
    
    public void setDsemMoneda(String dsemMoneda) {
        this.dsemMoneda = dsemMoneda;
    }
    public String getDsemTipoAprobacion() {
        return this.dsemTipoAprobacion;
    }
    
    public void setDsemTipoAprobacion(String dsemTipoAprobacion) {
        this.dsemTipoAprobacion = dsemTipoAprobacion;
    }
    public Integer getNsemNumeroAprobadores() {
        return this.nsemNumeroAprobadores;
    }
    
    public void setNsemNumeroAprobadores(Integer nsemNumeroAprobadores) {
        this.nsemNumeroAprobadores = nsemNumeroAprobadores;
    }
    public char getCsemEstado() {
        return this.csemEstado;
    }
    
    public void setCsemEstado(char csemEstado) {
        this.csemEstado = csemEstado;
    }
    public String getDsemFormatoArchivo() {
        return this.dsemFormatoArchivo;
    }
    
    public void setDsemFormatoArchivo(String dsemFormatoArchivo) {
        this.dsemFormatoArchivo = dsemFormatoArchivo;
    }
    public Character getCsemFlagPagoParcial() {
        return this.csemFlagPagoParcial;
    }
    
    public void setCsemFlagPagoParcial(Character csemFlagPagoParcial) {
        this.csemFlagPagoParcial = csemFlagPagoParcial;
    }
    public Character getCsemFlagEjecucion() {
        return this.csemFlagEjecucion;
    }
    
    public void setCsemFlagEjecucion(Character csemFlagEjecucion) {
        this.csemFlagEjecucion = csemFlagEjecucion;
    }
    public Character getCsemPeriodoCobro() {
        return this.csemPeriodoCobro;
    }
    
    public void setCsemPeriodoCobro(Character csemPeriodoCobro) {
        this.csemPeriodoCobro = csemPeriodoCobro;
    }
    public BigDecimal getNsemMontoAbonado() {
        return this.nsemMontoAbonado;
    }
    
    public void setNsemMontoAbonado(BigDecimal nsemMontoAbonado) {
        this.nsemMontoAbonado = nsemMontoAbonado;
    }
    public String getFsemFechaVenc() {
        return this.fsemFechaVenc;
    }
    
    public void setFsemFechaVenc(String fsemFechaVenc) {
        this.fsemFechaVenc = fsemFechaVenc;
    }
    public Integer getCseformatoEntrada() {
        return this.cseformatoEntrada;
    }
    
    public void setCseformatoEntrada(Integer cseformatoEntrada) {
        this.cseformatoEntrada = cseformatoEntrada;
    }
    public Integer getCseformatoSalida() {
        return this.cseformatoSalida;
    }
    
    public void setCseformatoSalida(Integer cseformatoSalida) {
        this.cseformatoSalida = cseformatoSalida;
    }
    public String getCsemModifyUser() {
        return this.csemModifyUser;
    }
    
    public void setCsemModifyUser(String csemModifyUser) {
        this.csemModifyUser = csemModifyUser;
    }
    public String getFsemModifyDate() {
        return this.fsemModifyDate;
    }
    
    public void setFsemModifyDate(String fsemModifyDate) {
        this.fsemModifyDate = fsemModifyDate;
    }
    public String getHsemModifyTime() {
        return this.hsemModifyTime;
    }
    
    public void setHsemModifyTime(String hsemModifyTime) {
        this.hsemModifyTime = hsemModifyTime;
    }
    public Character getCsemFlagAprobAut() {
        return this.csemFlagAprobAut;
    }
    
    public void setCsemFlagAprobAut(Character csemFlagAprobAut) {
        this.csemFlagAprobAut = csemFlagAprobAut;
    }
    public Set getTpDetalleCobroSinBds() {
        return this.tpDetalleCobroSinBds;
    }
    
    public void setTpDetalleCobroSinBds(Set tpDetalleCobroSinBds) {
        this.tpDetalleCobroSinBds = tpDetalleCobroSinBds;
    }
    public Set getTaOrdens() {
        return this.taOrdens;
    }
    
    public void setTaOrdens(Set taOrdens) {
        this.taOrdens = taOrdens;
    }
    public Set getTaGlosaCobroSinBds() {
        return this.taGlosaCobroSinBds;
    }
    
    public void setTaGlosaCobroSinBds(Set taGlosaCobroSinBds) {
        this.taGlosaCobroSinBds = taGlosaCobroSinBds;
    }
    public Set getTaServicioEntidads() {
        return this.taServicioEntidads;
    }
    
    public void setTaServicioEntidads(Set taServicioEntidads) {
        this.taServicioEntidads = taServicioEntidads;
    }
    public Set getTaTipoPagoServicios() {
        return this.taTipoPagoServicios;
    }
    
    public void setTaTipoPagoServicios(Set taTipoPagoServicios) {
        this.taTipoPagoServicios = taTipoPagoServicios;
    }
    public Set getTaFuncionarioServicios() {
        return this.taFuncionarioServicios;
    }
    
    public void setTaFuncionarioServicios(Set taFuncionarioServicios) {
        this.taFuncionarioServicios = taFuncionarioServicios;
    }
    public Set getTaAprobadorServicios() {
        return this.taAprobadorServicios;
    }
    
    public void setTaAprobadorServicios(Set taAprobadorServicios) {
        this.taAprobadorServicios = taAprobadorServicios;
    }
    public Set getTaCuentasServicioEmpresas() {
        return this.taCuentasServicioEmpresas;
    }
    
    public void setTaCuentasServicioEmpresas(Set taCuentasServicioEmpresas) {
        this.taCuentasServicioEmpresas = taCuentasServicioEmpresas;
    }

    public String getTipoServicio() {
        return tipoServicio;
    }

    public void setTipoServicio(String tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    public String getDsemDescripcion() {
        return dsemDescripcion;
    }

    public void setDsemDescripcion(String dsemDescripcion) {
        this.dsemDescripcion = dsemDescripcion;
    }

    @Override
    public String toString() {
    	return String.valueOf(csemIdServicioEmpresa);
    }

}


