package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaServicioOpcion generated by hbm2java
 */
public class TaServicioOpcion  implements java.io.Serializable {


     private TaServicioOpcionId id;
     private TmServicio tmServicio;

    public TaServicioOpcion() {
    }

    public TaServicioOpcion(TaServicioOpcionId id, TmServicio tmServicio) {
       this.id = id;
       this.tmServicio = tmServicio;
    }
   
    public TaServicioOpcionId getId() {
        return this.id;
    }
    
    public void setId(TaServicioOpcionId id) {
        this.id = id;
    }
    public TmServicio getTmServicio() {
        return this.tmServicio;
    }
    
    public void setTmServicio(TmServicio tmServicio) {
        this.tmServicio = tmServicio;
    }




}


