package com.hiper.cash.domain;
// Generated 23/12/2009 01:49:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TaServicioEntidad generated by hbm2java
 */
public class TaServicioEntidad  implements java.io.Serializable {


     private TaServicioEntidadId id;
     private TaServicioxEmpresa taServicioxEmpresa;
     private String csenIdEmpresa;
     private String nsenNumCuenta;
     private String csenTipoCuenta;
     private String csetipoPago;
     private BigDecimal nsenMonto;
     private String csenMoneda;
     private String csenCodigoOtroBanco;
     private String csenTipoCtaOtroBanco;
     private String csenNumCtaCci;
     private String csenModifyUser;
     private String fsenModifyDate;
     private String hsenModifyTime;
     private Set taEntidadEmpresas = new HashSet(0);

    public TaServicioEntidad() {
    }

	
    public TaServicioEntidad(TaServicioEntidadId id, TaServicioxEmpresa taServicioxEmpresa, String csenIdEmpresa) {
        this.id = id;
        this.taServicioxEmpresa = taServicioxEmpresa;
        this.csenIdEmpresa = csenIdEmpresa;
    }
    public TaServicioEntidad(TaServicioEntidadId id, TaServicioxEmpresa taServicioxEmpresa, String csenIdEmpresa, String nsenNumCuenta, String csenTipoCuenta, String csetipoPago, BigDecimal nsenMonto, String csenMoneda, String csenCodigoOtroBanco, String csenTipoCtaOtroBanco, String csenNumCtaCci, String csenModifyUser, String fsenModifyDate, String hsenModifyTime, Set taEntidadEmpresas) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
       this.csenIdEmpresa = csenIdEmpresa;
       this.nsenNumCuenta = nsenNumCuenta;
       this.csenTipoCuenta = csenTipoCuenta;
       this.csetipoPago = csetipoPago;
       this.nsenMonto = nsenMonto;
       this.csenMoneda = csenMoneda;
       this.csenCodigoOtroBanco = csenCodigoOtroBanco;
       this.csenTipoCtaOtroBanco = csenTipoCtaOtroBanco;
       this.csenNumCtaCci = csenNumCtaCci;
       this.csenModifyUser = csenModifyUser;
       this.fsenModifyDate = fsenModifyDate;
       this.hsenModifyTime = hsenModifyTime;
       this.taEntidadEmpresas = taEntidadEmpresas;
    }
   
    public TaServicioEntidadId getId() {
        return this.id;
    }
    
    public void setId(TaServicioEntidadId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }
    public String getCsenIdEmpresa() {
        return this.csenIdEmpresa;
    }
    
    public void setCsenIdEmpresa(String csenIdEmpresa) {
        this.csenIdEmpresa = csenIdEmpresa;
    }
    public String getNsenNumCuenta() {
        return this.nsenNumCuenta;
    }
    
    public void setNsenNumCuenta(String nsenNumCuenta) {
        this.nsenNumCuenta = nsenNumCuenta;
    }
    public String getCsenTipoCuenta() {
        return this.csenTipoCuenta;
    }
    
    public void setCsenTipoCuenta(String csenTipoCuenta) {
        this.csenTipoCuenta = csenTipoCuenta;
    }
    public String getCsetipoPago() {
        return this.csetipoPago;
    }
    
    public void setCsetipoPago(String csetipoPago) {
        this.csetipoPago = csetipoPago;
    }
    public BigDecimal getNsenMonto() {
        return this.nsenMonto;
    }
    
    public void setNsenMonto(BigDecimal nsenMonto) {
        this.nsenMonto = nsenMonto;
    }
    public String getCsenMoneda() {
        return this.csenMoneda;
    }
    
    public void setCsenMoneda(String csenMoneda) {
        this.csenMoneda = csenMoneda;
    }
    public String getCsenCodigoOtroBanco() {
        return this.csenCodigoOtroBanco;
    }
    
    public void setCsenCodigoOtroBanco(String csenCodigoOtroBanco) {
        this.csenCodigoOtroBanco = csenCodigoOtroBanco;
    }
    public String getCsenTipoCtaOtroBanco() {
        return this.csenTipoCtaOtroBanco;
    }
    
    public void setCsenTipoCtaOtroBanco(String csenTipoCtaOtroBanco) {
        this.csenTipoCtaOtroBanco = csenTipoCtaOtroBanco;
    }
    public String getCsenNumCtaCci() {
        return this.csenNumCtaCci;
    }
    
    public void setCsenNumCtaCci(String csenNumCtaCci) {
        this.csenNumCtaCci = csenNumCtaCci;
    }
    public String getCsenModifyUser() {
        return this.csenModifyUser;
    }
    
    public void setCsenModifyUser(String csenModifyUser) {
        this.csenModifyUser = csenModifyUser;
    }
    public String getFsenModifyDate() {
        return this.fsenModifyDate;
    }
    
    public void setFsenModifyDate(String fsenModifyDate) {
        this.fsenModifyDate = fsenModifyDate;
    }
    public String getHsenModifyTime() {
        return this.hsenModifyTime;
    }
    
    public void setHsenModifyTime(String hsenModifyTime) {
        this.hsenModifyTime = hsenModifyTime;
    }
    public Set getTaEntidadEmpresas() {
        return this.taEntidadEmpresas;
    }
    
    public void setTaEntidadEmpresas(Set taEntidadEmpresas) {
        this.taEntidadEmpresas = taEntidadEmpresas;
    }




}


