package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TaTarifa generated by hbm2java
 */
public class TaTarifa  implements java.io.Serializable {


     private long ctaIdTarifa;
     private String dtaDescripcion;
     private String dtaPeriodoCobroMora;
     private String dtaModalidadMora;
     private String ctaMonedaMora;
     private BigDecimal ntaValModalidadMora;
     private String ctaMonedaTrxComis;
     private BigDecimal ntaMontoUsuTrxComis;
     private String ctaAplicacionMoraDscto;
     private String ctaMonedaUsuTrxComis;
     private String dtaPeriodoDcto;
     private String dtaModalidadDcto;
     private String ctaMonedaDcto;
     private BigDecimal ntaValModalidadDcto;
     private char ctaEstado;
     private BigDecimal ntaMontoTrxComis;
     private String ctaModifyUser;
     private String ftaModifyDate;
     private String htaModifyTime;
     private Set taServicioxEmpresas = new HashSet(0);

    public TaTarifa() {
    }

	
    public TaTarifa(long ctaIdTarifa, char ctaEstado) {
        this.ctaIdTarifa = ctaIdTarifa;
        this.ctaEstado = ctaEstado;
    }
    public TaTarifa(long ctaIdTarifa, String dtaDescripcion, String dtaPeriodoCobroMora, String dtaModalidadMora, String ctaMonedaMora, BigDecimal ntaValModalidadMora, String ctaMonedaTrxComis, BigDecimal ntaMontoUsuTrxComis, String ctaAplicacionMoraDscto, String ctaMonedaUsuTrxComis, String dtaPeriodoDcto, String dtaModalidadDcto, String ctaMonedaDcto, BigDecimal ntaValModalidadDcto, char ctaEstado, BigDecimal ntaMontoTrxComis, String ctaModifyUser, String ftaModifyDate, String htaModifyTime, Set taServicioxEmpresas) {
       this.ctaIdTarifa = ctaIdTarifa;
       this.dtaDescripcion = dtaDescripcion;
       this.dtaPeriodoCobroMora = dtaPeriodoCobroMora;
       this.dtaModalidadMora = dtaModalidadMora;
       this.ctaMonedaMora = ctaMonedaMora;
       this.ntaValModalidadMora = ntaValModalidadMora;
       this.ctaMonedaTrxComis = ctaMonedaTrxComis;
       this.ntaMontoUsuTrxComis = ntaMontoUsuTrxComis;
       this.ctaAplicacionMoraDscto = ctaAplicacionMoraDscto;
       this.ctaMonedaUsuTrxComis = ctaMonedaUsuTrxComis;
       this.dtaPeriodoDcto = dtaPeriodoDcto;
       this.dtaModalidadDcto = dtaModalidadDcto;
       this.ctaMonedaDcto = ctaMonedaDcto;
       this.ntaValModalidadDcto = ntaValModalidadDcto;
       this.ctaEstado = ctaEstado;
       this.ntaMontoTrxComis = ntaMontoTrxComis;
       this.ctaModifyUser = ctaModifyUser;
       this.ftaModifyDate = ftaModifyDate;
       this.htaModifyTime = htaModifyTime;
       this.taServicioxEmpresas = taServicioxEmpresas;
    }
   
    public long getCtaIdTarifa() {
        return this.ctaIdTarifa;
    }
    
    public void setCtaIdTarifa(long ctaIdTarifa) {
        this.ctaIdTarifa = ctaIdTarifa;
    }
    public String getDtaDescripcion() {
        return this.dtaDescripcion;
    }
    
    public void setDtaDescripcion(String dtaDescripcion) {
        this.dtaDescripcion = dtaDescripcion;
    }
    public String getDtaPeriodoCobroMora() {
        return this.dtaPeriodoCobroMora;
    }
    
    public void setDtaPeriodoCobroMora(String dtaPeriodoCobroMora) {
        this.dtaPeriodoCobroMora = dtaPeriodoCobroMora;
    }
    public String getDtaModalidadMora() {
        return this.dtaModalidadMora;
    }
    
    public void setDtaModalidadMora(String dtaModalidadMora) {
        this.dtaModalidadMora = dtaModalidadMora;
    }
    public String getCtaMonedaMora() {
        return this.ctaMonedaMora;
    }
    
    public void setCtaMonedaMora(String ctaMonedaMora) {
        this.ctaMonedaMora = ctaMonedaMora;
    }
    public BigDecimal getNtaValModalidadMora() {
        return this.ntaValModalidadMora;
    }
    
    public void setNtaValModalidadMora(BigDecimal ntaValModalidadMora) {
        this.ntaValModalidadMora = ntaValModalidadMora;
    }
    public String getCtaMonedaTrxComis() {
        return this.ctaMonedaTrxComis;
    }
    
    public void setCtaMonedaTrxComis(String ctaMonedaTrxComis) {
        this.ctaMonedaTrxComis = ctaMonedaTrxComis; 
    }
    public BigDecimal getNtaMontoUsuTrxComis() {
        return this.ntaMontoUsuTrxComis;
    }
    
    public void setNtaMontoUsuTrxComis(BigDecimal ntaMontoUsuTrxComis) {
        this.ntaMontoUsuTrxComis = ntaMontoUsuTrxComis;
    }
    public String getCtaAplicacionMoraDscto() {
        return this.ctaAplicacionMoraDscto;
    }
    
    public void setCtaAplicacionMoraDscto(String ctaAplicacionMoraDscto) {
        this.ctaAplicacionMoraDscto = ctaAplicacionMoraDscto;
    }
    public String getCtaMonedaUsuTrxComis() {
        return this.ctaMonedaUsuTrxComis;
    }
    
    public void setCtaMonedaUsuTrxComis(String ctaMonedaUsuTrxComis) {
        this.ctaMonedaUsuTrxComis = ctaMonedaUsuTrxComis;
    }
    public String getDtaPeriodoDcto() {
        return this.dtaPeriodoDcto;
    }
    
    public void setDtaPeriodoDcto(String dtaPeriodoDcto) {
        this.dtaPeriodoDcto = dtaPeriodoDcto;
    }
    public String getDtaModalidadDcto() {
        return this.dtaModalidadDcto;
    }
    
    public void setDtaModalidadDcto(String dtaModalidadDcto) {
        this.dtaModalidadDcto = dtaModalidadDcto;
    }
    public String getCtaMonedaDcto() {
        return this.ctaMonedaDcto;
    }
    
    public void setCtaMonedaDcto(String ctaMonedaDcto) {
        this.ctaMonedaDcto = ctaMonedaDcto;
    }
    public BigDecimal getNtaValModalidadDcto() {
        return this.ntaValModalidadDcto;
    }
    
    public void setNtaValModalidadDcto(BigDecimal ntaValModalidadDcto) {
        this.ntaValModalidadDcto = ntaValModalidadDcto;
    }
    public char getCtaEstado() {
        return this.ctaEstado;
    }
    
    public void setCtaEstado(char ctaEstado) {
        this.ctaEstado = ctaEstado;
    }
    public BigDecimal getNtaMontoTrxComis() {
        return this.ntaMontoTrxComis;
    }
    
    public void setNtaMontoTrxComis(BigDecimal ntaMontoTrxComis) {
        this.ntaMontoTrxComis = ntaMontoTrxComis;
    }
    public String getCtaModifyUser() {
        return this.ctaModifyUser;
    }
    
    public void setCtaModifyUser(String ctaModifyUser) {
        this.ctaModifyUser = ctaModifyUser;
    }
    public String getFtaModifyDate() {
        return this.ftaModifyDate;
    }
    
    public void setFtaModifyDate(String ftaModifyDate) {
        this.ftaModifyDate = ftaModifyDate;
    }
    public String getHtaModifyTime() {
        return this.htaModifyTime;
    }
    
    public void setHtaModifyTime(String htaModifyTime) {
        this.htaModifyTime = htaModifyTime;
    }
    public Set getTaServicioxEmpresas() {
        return this.taServicioxEmpresas;
    }
    
    public void setTaServicioxEmpresas(Set taServicioxEmpresas) {
        this.taServicioxEmpresas = taServicioxEmpresas;
    }




}


