package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaTerminalApplTransactionId generated by hbm2java
 */
public class TaTerminalApplTransactionId  implements java.io.Serializable {


     private String ctatmerchantId;
     private String ctatterminalNum;
     private String ctatapplicationId;
     private String ctattransactionId;

    public TaTerminalApplTransactionId() {
    }

    public TaTerminalApplTransactionId(String ctatmerchantId, String ctatterminalNum, String ctatapplicationId, String ctattransactionId) {
       this.ctatmerchantId = ctatmerchantId;
       this.ctatterminalNum = ctatterminalNum;
       this.ctatapplicationId = ctatapplicationId;
       this.ctattransactionId = ctattransactionId;
    }
   
    public String getCtatmerchantId() {
        return this.ctatmerchantId;
    }
    
    public void setCtatmerchantId(String ctatmerchantId) {
        this.ctatmerchantId = ctatmerchantId;
    }
    public String getCtatterminalNum() {
        return this.ctatterminalNum;
    }
    
    public void setCtatterminalNum(String ctatterminalNum) {
        this.ctatterminalNum = ctatterminalNum;
    }
    public String getCtatapplicationId() {
        return this.ctatapplicationId;
    }
    
    public void setCtatapplicationId(String ctatapplicationId) {
        this.ctatapplicationId = ctatapplicationId;
    }
    public String getCtattransactionId() {
        return this.ctattransactionId;
    }
    
    public void setCtattransactionId(String ctattransactionId) {
        this.ctattransactionId = ctattransactionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaTerminalApplTransactionId) ) return false;
		 TaTerminalApplTransactionId castOther = ( TaTerminalApplTransactionId ) other; 
         
		 return ( (this.getCtatmerchantId()==castOther.getCtatmerchantId()) || ( this.getCtatmerchantId()!=null && castOther.getCtatmerchantId()!=null && this.getCtatmerchantId().equals(castOther.getCtatmerchantId()) ) )
 && ( (this.getCtatterminalNum()==castOther.getCtatterminalNum()) || ( this.getCtatterminalNum()!=null && castOther.getCtatterminalNum()!=null && this.getCtatterminalNum().equals(castOther.getCtatterminalNum()) ) )
 && ( (this.getCtatapplicationId()==castOther.getCtatapplicationId()) || ( this.getCtatapplicationId()!=null && castOther.getCtatapplicationId()!=null && this.getCtatapplicationId().equals(castOther.getCtatapplicationId()) ) )
 && ( (this.getCtattransactionId()==castOther.getCtattransactionId()) || ( this.getCtattransactionId()!=null && castOther.getCtattransactionId()!=null && this.getCtattransactionId().equals(castOther.getCtattransactionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCtatmerchantId() == null ? 0 : this.getCtatmerchantId().hashCode() );
         result = 37 * result + ( getCtatterminalNum() == null ? 0 : this.getCtatterminalNum().hashCode() );
         result = 37 * result + ( getCtatapplicationId() == null ? 0 : this.getCtatapplicationId().hashCode() );
         result = 37 * result + ( getCtattransactionId() == null ? 0 : this.getCtattransactionId().hashCode() );
         return result;
   }   


}


