package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaTerminalApplicationId generated by hbm2java
 */
public class TaTerminalApplicationId  implements java.io.Serializable {


     private String ctamerchantId;
     private String ctaterminalNum;
     private String ctaapplicationId;

    public TaTerminalApplicationId() {
    }

    public TaTerminalApplicationId(String ctamerchantId, String ctaterminalNum, String ctaapplicationId) {
       this.ctamerchantId = ctamerchantId;
       this.ctaterminalNum = ctaterminalNum;
       this.ctaapplicationId = ctaapplicationId;
    }
   
    public String getCtamerchantId() {
        return this.ctamerchantId;
    }
    
    public void setCtamerchantId(String ctamerchantId) {
        this.ctamerchantId = ctamerchantId;
    }
    public String getCtaterminalNum() {
        return this.ctaterminalNum;
    }
    
    public void setCtaterminalNum(String ctaterminalNum) {
        this.ctaterminalNum = ctaterminalNum;
    }
    public String getCtaapplicationId() {
        return this.ctaapplicationId;
    }
    
    public void setCtaapplicationId(String ctaapplicationId) {
        this.ctaapplicationId = ctaapplicationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaTerminalApplicationId) ) return false;
		 TaTerminalApplicationId castOther = ( TaTerminalApplicationId ) other; 
         
		 return ( (this.getCtamerchantId()==castOther.getCtamerchantId()) || ( this.getCtamerchantId()!=null && castOther.getCtamerchantId()!=null && this.getCtamerchantId().equals(castOther.getCtamerchantId()) ) )
 && ( (this.getCtaterminalNum()==castOther.getCtaterminalNum()) || ( this.getCtaterminalNum()!=null && castOther.getCtaterminalNum()!=null && this.getCtaterminalNum().equals(castOther.getCtaterminalNum()) ) )
 && ( (this.getCtaapplicationId()==castOther.getCtaapplicationId()) || ( this.getCtaapplicationId()!=null && castOther.getCtaapplicationId()!=null && this.getCtaapplicationId().equals(castOther.getCtaapplicationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCtamerchantId() == null ? 0 : this.getCtamerchantId().hashCode() );
         result = 37 * result + ( getCtaterminalNum() == null ? 0 : this.getCtaterminalNum().hashCode() );
         result = 37 * result + ( getCtaapplicationId() == null ? 0 : this.getCtaapplicationId().hashCode() );
         return result;
   }   


}


