package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TaTerminalApplTransaction generated by hbm2java
 */
public class TaTerminalApplTransaction  implements java.io.Serializable {


     private TaTerminalApplTransactionId id;
     private String ctatterminalSn;
     private String ctattransactionStatus;
     private BigDecimal ntatfloorLimit;
     private BigDecimal ntatfloorLimitDollar;
     private String ctatmodifyUser;
     private String ftatmodifyDate;
     private String htatmodifyTime;

    public TaTerminalApplTransaction() {
    }

	
    public TaTerminalApplTransaction(TaTerminalApplTransactionId id, String ctatterminalSn) {
        this.id = id;
        this.ctatterminalSn = ctatterminalSn;
    }
    public TaTerminalApplTransaction(TaTerminalApplTransactionId id, String ctatterminalSn, String ctattransactionStatus, BigDecimal ntatfloorLimit, BigDecimal ntatfloorLimitDollar, String ctatmodifyUser, String ftatmodifyDate, String htatmodifyTime) {
       this.id = id;
       this.ctatterminalSn = ctatterminalSn;
       this.ctattransactionStatus = ctattransactionStatus;
       this.ntatfloorLimit = ntatfloorLimit;
       this.ntatfloorLimitDollar = ntatfloorLimitDollar;
       this.ctatmodifyUser = ctatmodifyUser;
       this.ftatmodifyDate = ftatmodifyDate;
       this.htatmodifyTime = htatmodifyTime;
    }
   
    public TaTerminalApplTransactionId getId() {
        return this.id;
    }
    
    public void setId(TaTerminalApplTransactionId id) {
        this.id = id;
    }
    public String getCtatterminalSn() {
        return this.ctatterminalSn;
    }
    
    public void setCtatterminalSn(String ctatterminalSn) {
        this.ctatterminalSn = ctatterminalSn;
    }
    public String getCtattransactionStatus() {
        return this.ctattransactionStatus;
    }
    
    public void setCtattransactionStatus(String ctattransactionStatus) {
        this.ctattransactionStatus = ctattransactionStatus;
    }
    public BigDecimal getNtatfloorLimit() {
        return this.ntatfloorLimit;
    }
    
    public void setNtatfloorLimit(BigDecimal ntatfloorLimit) {
        this.ntatfloorLimit = ntatfloorLimit;
    }
    public BigDecimal getNtatfloorLimitDollar() {
        return this.ntatfloorLimitDollar;
    }
    
    public void setNtatfloorLimitDollar(BigDecimal ntatfloorLimitDollar) {
        this.ntatfloorLimitDollar = ntatfloorLimitDollar;
    }
    public String getCtatmodifyUser() {
        return this.ctatmodifyUser;
    }
    
    public void setCtatmodifyUser(String ctatmodifyUser) {
        this.ctatmodifyUser = ctatmodifyUser;
    }
    public String getFtatmodifyDate() {
        return this.ftatmodifyDate;
    }
    
    public void setFtatmodifyDate(String ftatmodifyDate) {
        this.ftatmodifyDate = ftatmodifyDate;
    }
    public String getHtatmodifyTime() {
        return this.htatmodifyTime;
    }
    
    public void setHtatmodifyTime(String htatmodifyTime) {
        this.htatmodifyTime = htatmodifyTime;
    }




}


