package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TaTipoPagoServicioId generated by hbm2java
 */
public class TaTipoPagoServicioId  implements java.io.Serializable {


     private long ctpsidTipoPagoServicio;
     private long csemIdServicioEmpresa;
     private String ctpaIdTipoPago;

    public TaTipoPagoServicioId() {
    }

    public TaTipoPagoServicioId(long ctpsidTipoPagoServicio, long csemIdServicioEmpresa, String ctpaIdTipoPago) {
       this.ctpsidTipoPagoServicio = ctpsidTipoPagoServicio;
       this.csemIdServicioEmpresa = csemIdServicioEmpresa;
       this.ctpaIdTipoPago = ctpaIdTipoPago;
    }
   
    public long getCtpsidTipoPagoServicio() {
        return this.ctpsidTipoPagoServicio;
    }
    
    public void setCtpsidTipoPagoServicio(long ctpsidTipoPagoServicio) {
        this.ctpsidTipoPagoServicio = ctpsidTipoPagoServicio;
    }
    public long getCsemIdServicioEmpresa() {
        return this.csemIdServicioEmpresa;
    }
    
    public void setCsemIdServicioEmpresa(long csemIdServicioEmpresa) {
        this.csemIdServicioEmpresa = csemIdServicioEmpresa;
    }
    public String getCtpaIdTipoPago() {
        return this.ctpaIdTipoPago;
    }
    
    public void setCtpaIdTipoPago(String ctpaIdTipoPago) {
        this.ctpaIdTipoPago = ctpaIdTipoPago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaTipoPagoServicioId) ) return false;
		 TaTipoPagoServicioId castOther = ( TaTipoPagoServicioId ) other; 
         
		 return (this.getCtpsidTipoPagoServicio()==castOther.getCtpsidTipoPagoServicio())
 && (this.getCsemIdServicioEmpresa()==castOther.getCsemIdServicioEmpresa())
 && ( (this.getCtpaIdTipoPago()==castOther.getCtpaIdTipoPago()) || ( this.getCtpaIdTipoPago()!=null && castOther.getCtpaIdTipoPago()!=null && this.getCtpaIdTipoPago().equals(castOther.getCtpaIdTipoPago()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCtpsidTipoPagoServicio();
         result = 37 * result + (int) this.getCsemIdServicioEmpresa();
         result = 37 * result + ( getCtpaIdTipoPago() == null ? 0 : this.getCtpaIdTipoPago().hashCode() );
         return result;
   }   


}


