package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmApplication generated by hbm2java
 */
public class TmApplication  implements java.io.Serializable {


     private String capApplicationId;
     private String dapApplicationName;
     private String dapApplicationFlow;
     private Long napApplicationFlowSize;
     private String capModifyUser;
     private String fapModifyDate;
     private String hapModifyTime;
     private Set taTerminalApplications = new HashSet(0);

    public TmApplication() {
    }

	
    public TmApplication(String capApplicationId) {
        this.capApplicationId = capApplicationId;
    }
    public TmApplication(String capApplicationId, String dapApplicationName, String dapApplicationFlow, Long napApplicationFlowSize, String capModifyUser, String fapModifyDate, String hapModifyTime, Set taTerminalApplications) {
       this.capApplicationId = capApplicationId;
       this.dapApplicationName = dapApplicationName;
       this.dapApplicationFlow = dapApplicationFlow;
       this.napApplicationFlowSize = napApplicationFlowSize;
       this.capModifyUser = capModifyUser;
       this.fapModifyDate = fapModifyDate;
       this.hapModifyTime = hapModifyTime;
       this.taTerminalApplications = taTerminalApplications;
    }
   
    public String getCapApplicationId() {
        return this.capApplicationId;
    }
    
    public void setCapApplicationId(String capApplicationId) {
        this.capApplicationId = capApplicationId;
    }
    public String getDapApplicationName() {
        return this.dapApplicationName;
    }
    
    public void setDapApplicationName(String dapApplicationName) {
        this.dapApplicationName = dapApplicationName;
    }
    public String getDapApplicationFlow() {
        return this.dapApplicationFlow;
    }
    
    public void setDapApplicationFlow(String dapApplicationFlow) {
        this.dapApplicationFlow = dapApplicationFlow;
    }
    public Long getNapApplicationFlowSize() {
        return this.napApplicationFlowSize;
    }
    
    public void setNapApplicationFlowSize(Long napApplicationFlowSize) {
        this.napApplicationFlowSize = napApplicationFlowSize;
    }
    public String getCapModifyUser() {
        return this.capModifyUser;
    }
    
    public void setCapModifyUser(String capModifyUser) {
        this.capModifyUser = capModifyUser;
    }
    public String getFapModifyDate() {
        return this.fapModifyDate;
    }
    
    public void setFapModifyDate(String fapModifyDate) {
        this.fapModifyDate = fapModifyDate;
    }
    public String getHapModifyTime() {
        return this.hapModifyTime;
    }
    
    public void setHapModifyTime(String hapModifyTime) {
        this.hapModifyTime = hapModifyTime;
    }
    public Set getTaTerminalApplications() {
        return this.taTerminalApplications;
    }
    
    public void setTaTerminalApplications(Set taTerminalApplications) {
        this.taTerminalApplications = taTerminalApplications;
    }




}


