package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TmBanco generated by hbm2java
 */
public class TmBanco  implements java.io.Serializable {   
	private static final long serialVersionUID = 5495936943899350946L;
	private int cbaIdBanco;
     private String cbaNombre;
     private String dbaCodigo;
     private String dbaPais;
     private String dbaCiudad;
     private String dbaCodigoSwift;
     private String dbaCodigoFed;
     private String dbaCodigoAba;
     private String dbaCuentaBce;
     private Character dbaIntercambioSwfit;
     private Character cbaEstado;
     private String dbaDireccion;
     private String cbaModifyUser;
     private String fbaModifyDate;
     private String hbaModifyTime;

    public TmBanco() {
    }

	
    public TmBanco(int cbaIdBanco, String dbaPais) {
        this.cbaIdBanco = cbaIdBanco;
        this.dbaPais = dbaPais;
    }
    public TmBanco(int cbaIdBanco, String cbaNombre, String dbaCodigo, String dbaPais, String dbaCiudad, String dbaCodigoSwift, String dbaCodigoFed, String dbaCodigoAba, String dbaCuentaBce, Character dbaIntercambioSwfit, Character cbaEstado, String dbaDireccion, String cbaModifyUser, String fbaModifyDate, String hbaModifyTime) {
       this.cbaIdBanco = cbaIdBanco;
       this.cbaNombre = cbaNombre;
       this.dbaCodigo = dbaCodigo;
       this.dbaPais = dbaPais;
       this.dbaCiudad = dbaCiudad;
       this.dbaCodigoSwift = dbaCodigoSwift;
       this.dbaCodigoFed = dbaCodigoFed;
       this.dbaCodigoAba = dbaCodigoAba;
       this.dbaCuentaBce = dbaCuentaBce;
       this.dbaIntercambioSwfit = dbaIntercambioSwfit;
       this.cbaEstado = cbaEstado;
       this.dbaDireccion = dbaDireccion;
       this.cbaModifyUser = cbaModifyUser;
       this.fbaModifyDate = fbaModifyDate;
       this.hbaModifyTime = hbaModifyTime;
    }
   
    public int getCbaIdBanco() {
        return this.cbaIdBanco;
    }
    
    public void setCbaIdBanco(int cbaIdBanco) {
        this.cbaIdBanco = cbaIdBanco;
    }
    public String getCbaNombre() {
        return this.cbaNombre;
    }
    
    public void setCbaNombre(String cbaNombre) {
        this.cbaNombre = cbaNombre;
    }
    public String getDbaCodigo() {
        return this.dbaCodigo;
    }
    
    public void setDbaCodigo(String dbaCodigo) {
        this.dbaCodigo = dbaCodigo;
    }
    public String getDbaPais() {
        return this.dbaPais;
    }
    
    public void setDbaPais(String dbaPais) {
        this.dbaPais = dbaPais;
    }
    public String getDbaCiudad() {
        return this.dbaCiudad;
    }
    
    public void setDbaCiudad(String dbaCiudad) {
        this.dbaCiudad = dbaCiudad;
    }
    public String getDbaCodigoSwift() {
        return this.dbaCodigoSwift;
    }
    
    public void setDbaCodigoSwift(String dbaCodigoSwift) {
        this.dbaCodigoSwift = dbaCodigoSwift;
    }
    public String getDbaCodigoFed() {
        return this.dbaCodigoFed;
    }
    
    public void setDbaCodigoFed(String dbaCodigoFed) {
        this.dbaCodigoFed = dbaCodigoFed;
    }
    public String getDbaCodigoAba() {
        return this.dbaCodigoAba;
    }
    
    public void setDbaCodigoAba(String dbaCodigoAba) {
        this.dbaCodigoAba = dbaCodigoAba;
    }
    public String getDbaCuentaBce() {
        return this.dbaCuentaBce;
    }
    
    public void setDbaCuentaBce(String dbaCuentaBce) {
        this.dbaCuentaBce = dbaCuentaBce;
    }
    public Character getDbaIntercambioSwfit() {
        return this.dbaIntercambioSwfit;
    }
    
    public void setDbaIntercambioSwfit(Character dbaIntercambioSwfit) {
        this.dbaIntercambioSwfit = dbaIntercambioSwfit;
    }
    public Character getCbaEstado() {
        return this.cbaEstado;
    }
    
    public void setCbaEstado(Character cbaEstado) {
        this.cbaEstado = cbaEstado;
    }
    public String getDbaDireccion() {
        return this.dbaDireccion;
    }
    
    public void setDbaDireccion(String dbaDireccion) {
        this.dbaDireccion = dbaDireccion;
    }
    public String getCbaModifyUser() {
        return this.cbaModifyUser;
    }
    
    public void setCbaModifyUser(String cbaModifyUser) {
        this.cbaModifyUser = cbaModifyUser;
    }
    public String getFbaModifyDate() {
        return this.fbaModifyDate;
    }
    
    public void setFbaModifyDate(String fbaModifyDate) {
        this.fbaModifyDate = fbaModifyDate;
    }
    public String getHbaModifyTime() {
        return this.hbaModifyTime;
    }
    
    public void setHbaModifyTime(String hbaModifyTime) {
        this.hbaModifyTime = hbaModifyTime;
    }




}


