package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TmDownloadProfile generated by hbm2java
 */
public class TmDownloadProfile  implements java.io.Serializable {


     private long cdpprofileId;
     private String ddpprofileName;
     private String ddpdescription;
     private Long cdpversioId;
     private String hdpdownloadTime;
     private String fdpaplicDate;
     private String hdptoleranceDwnTime;
     private String cdpmodifyUser;
     private String fdpmodifyDate;
     private String hdpmodifyTime;

    public TmDownloadProfile() {
    }

	
    public TmDownloadProfile(long cdpprofileId, String ddpprofileName, String ddpdescription, String hdpdownloadTime, String fdpaplicDate) {
        this.cdpprofileId = cdpprofileId;
        this.ddpprofileName = ddpprofileName;
        this.ddpdescription = ddpdescription;
        this.hdpdownloadTime = hdpdownloadTime;
        this.fdpaplicDate = fdpaplicDate;
    }
    public TmDownloadProfile(long cdpprofileId, String ddpprofileName, String ddpdescription, Long cdpversioId, String hdpdownloadTime, String fdpaplicDate, String hdptoleranceDwnTime, String cdpmodifyUser, String fdpmodifyDate, String hdpmodifyTime) {
       this.cdpprofileId = cdpprofileId;
       this.ddpprofileName = ddpprofileName;
       this.ddpdescription = ddpdescription;
       this.cdpversioId = cdpversioId;
       this.hdpdownloadTime = hdpdownloadTime;
       this.fdpaplicDate = fdpaplicDate;
       this.hdptoleranceDwnTime = hdptoleranceDwnTime;
       this.cdpmodifyUser = cdpmodifyUser;
       this.fdpmodifyDate = fdpmodifyDate;
       this.hdpmodifyTime = hdpmodifyTime;
    }
   
    public long getCdpprofileId() {
        return this.cdpprofileId;
    }
    
    public void setCdpprofileId(long cdpprofileId) {
        this.cdpprofileId = cdpprofileId;
    }
    public String getDdpprofileName() {
        return this.ddpprofileName;
    }
    
    public void setDdpprofileName(String ddpprofileName) {
        this.ddpprofileName = ddpprofileName;
    }
    public String getDdpdescription() {
        return this.ddpdescription;
    }
    
    public void setDdpdescription(String ddpdescription) {
        this.ddpdescription = ddpdescription;
    }
    public Long getCdpversioId() {
        return this.cdpversioId;
    }
    
    public void setCdpversioId(Long cdpversioId) {
        this.cdpversioId = cdpversioId;
    }
    public String getHdpdownloadTime() {
        return this.hdpdownloadTime;
    }
    
    public void setHdpdownloadTime(String hdpdownloadTime) {
        this.hdpdownloadTime = hdpdownloadTime;
    }
    public String getFdpaplicDate() {
        return this.fdpaplicDate;
    }
    
    public void setFdpaplicDate(String fdpaplicDate) {
        this.fdpaplicDate = fdpaplicDate;
    }
    public String getHdptoleranceDwnTime() {
        return this.hdptoleranceDwnTime;
    }
    
    public void setHdptoleranceDwnTime(String hdptoleranceDwnTime) {
        this.hdptoleranceDwnTime = hdptoleranceDwnTime;
    }
    public String getCdpmodifyUser() {
        return this.cdpmodifyUser;
    }
    
    public void setCdpmodifyUser(String cdpmodifyUser) {
        this.cdpmodifyUser = cdpmodifyUser;
    }
    public String getFdpmodifyDate() {
        return this.fdpmodifyDate;
    }
    
    public void setFdpmodifyDate(String fdpmodifyDate) {
        this.fdpmodifyDate = fdpmodifyDate;
    }
    public String getHdpmodifyTime() {
        return this.hdpmodifyTime;
    }
    
    public void setHdpmodifyTime(String hdpmodifyTime) {
        this.hdpmodifyTime = hdpmodifyTime;
    }




}


