package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TmEmpresa generated by hbm2java
 */
public class TmEmpresa  implements java.io.Serializable {


     private String cemIdEmpresa;
     private String cemCodigoCliente;
     private String demNombre;
     private String demNombreCorto;
     private String cemDepartamento;
     private String cemCiudad;
     private String demDireccion;
     private String demTelefono;
     private String demTelefono2;
     private String demTelefono3;
     private String demFax;
     private String cemEstado;
     private String femFechaIngreso;
     private String cemAplicacionTarifa;
     private BigDecimal nemMontoComis;
     private String nemMonedaComis;
     private String cemMonCtaCargoComis;
     private String cemTipoCtaCargoComis;
     private String demTipoCtaCargoComis;
     private String nemCuentaCargoComis;
     private String demBeneficiarioSwift;
     private String cemIdEmpresaPadre;
     private Integer nemDiasRetencion;
     private String nemNumeroContrato;
     private String cemRubro;
     private String femFechaFundacion;
     private String femRegistroBanco;
     private String cemDepRegBanco;
     private String cemAgenRegBanco;
     private String cemModifyUser;
     private String femModifyDate;
     private String hemModifyTime;
     private Set taServicioxEmpresas = new HashSet(0);
     private Set taContactoEmpresas = new HashSet(0);
     private Set taFuncionarioEmpresas = new HashSet(0);

     /* Se agrega el campo RUC de la tabla Empresa*/
     private String cEmRUC;

    public TmEmpresa() {
    	   this.cemIdEmpresa = "";
           this.cemCodigoCliente = "";
           this.demNombre = "";
           this.demNombreCorto = "";
           this.cemDepartamento = "";
           this.cemCiudad = "";
           this.demDireccion = "";
           this.demTelefono = "";
           this.demTelefono2 = "";
           this.demTelefono3 = "";
           this.demFax = "";
           this.cemEstado = "";
           this.femFechaIngreso = "";
           this.cemAplicacionTarifa = "";
           this.nemMontoComis = new BigDecimal("0");
           this.nemMonedaComis = "";
           this.cemMonCtaCargoComis = "";
           this.cemTipoCtaCargoComis = "";
           this.demTipoCtaCargoComis = "";
           this.nemCuentaCargoComis = "";
           this.demBeneficiarioSwift = "";
           this.cemIdEmpresaPadre = "";
           this.nemDiasRetencion = 0;
           this.nemNumeroContrato = "";
           this.cemRubro = "";
           this.femFechaFundacion = "";
           this.femRegistroBanco = "";
           this.cemDepRegBanco = "";
           this.cemAgenRegBanco = "";
           this.cemModifyUser = "";
           this.femModifyDate = "";
           this.hemModifyTime = "";
           this.cEmRUC="";
    
    }

	
    public TmEmpresa(String cemIdEmpresa) {
        this.cemIdEmpresa = cemIdEmpresa;
    }
    public TmEmpresa(String cemIdEmpresa, String cemCodigoCliente, String demNombre, String demNombreCorto, String cemDepartamento, String cemCiudad, String demDireccion, String demTelefono, String demTelefono2, String demTelefono3, String demFax, String cemEstado, String femFechaIngreso, String cemAplicacionTarifa, BigDecimal nemMontoComis, String nemMonedaComis, String cemMonCtaCargoComis, String cemTipoCtaCargoComis, String demTipoCtaCargoComis, String nemCuentaCargoComis, String demBeneficiarioSwift, String cemIdEmpresaPadre, Integer nemDiasRetencion, String nemNumeroContrato, String cemRubro, String femFechaFundacion, String femRegistroBanco, String cemDepRegBanco, String cemAgenRegBanco, String cemModifyUser, String femModifyDate, String hemModifyTime, Set taServicioxEmpresas, Set taContactoEmpresas, Set taFuncionarioEmpresas, String cEmRUC) {
       this.cemIdEmpresa = cemIdEmpresa;
       this.cemCodigoCliente = cemCodigoCliente;
       this.demNombre = demNombre;
       this.demNombreCorto = demNombreCorto;
       this.cemDepartamento = cemDepartamento;
       this.cemCiudad = cemCiudad;
       this.demDireccion = demDireccion;
       this.demTelefono = demTelefono;
       this.demTelefono2 = demTelefono2;
       this.demTelefono3 = demTelefono3;
       this.demFax = demFax;
       this.cemEstado = cemEstado;
       this.femFechaIngreso = femFechaIngreso;
       this.cemAplicacionTarifa = cemAplicacionTarifa;
       this.nemMontoComis = nemMontoComis;
       this.nemMonedaComis = nemMonedaComis;
       this.cemMonCtaCargoComis = cemMonCtaCargoComis;
       this.cemTipoCtaCargoComis = cemTipoCtaCargoComis;
       this.demTipoCtaCargoComis = demTipoCtaCargoComis;
       this.nemCuentaCargoComis = nemCuentaCargoComis;
       this.demBeneficiarioSwift = demBeneficiarioSwift;
       this.cemIdEmpresaPadre = cemIdEmpresaPadre;
       this.nemDiasRetencion = nemDiasRetencion;
       this.nemNumeroContrato = nemNumeroContrato;
       this.cemRubro = cemRubro;
       this.femFechaFundacion = femFechaFundacion;
       this.femRegistroBanco = femRegistroBanco;
       this.cemDepRegBanco = cemDepRegBanco;
       this.cemAgenRegBanco = cemAgenRegBanco;
       this.cemModifyUser = cemModifyUser;
       this.femModifyDate = femModifyDate;
       this.hemModifyTime = hemModifyTime;
       this.taServicioxEmpresas = taServicioxEmpresas;
       this.taContactoEmpresas = taContactoEmpresas;
       this.taFuncionarioEmpresas = taFuncionarioEmpresas;
       this.cEmRUC= cEmRUC;
       
    }
   
    public String getCemIdEmpresa() {
        return this.cemIdEmpresa;
    }
    
    public void setCemIdEmpresa(String cemIdEmpresa) {
        this.cemIdEmpresa = cemIdEmpresa;
    }
    public String getCemCodigoCliente() {
        return this.cemCodigoCliente;
    }
    
    public void setCemCodigoCliente(String cemCodigoCliente) {
        this.cemCodigoCliente = cemCodigoCliente;
    }
    public String getDemNombre() {
    	if(this.demNombreCorto!=null){
        	if(this.demNombreCorto.length()>0){
        		return this.demNombreCorto;	
        	}else{
        		return this.demNombre;	
        	}    		
    	}else{
    		return this.demNombre;
    	}
    }
    
    public void setDemNombre(String demNombre) {
        this.demNombre = demNombre;
    }
    public String getDemNombreCorto() {
        return this.demNombreCorto;
    }
    
    public void setDemNombreCorto(String demNombreCorto) {
        this.demNombreCorto = demNombreCorto;
    }
    public String getCemDepartamento() {
        return this.cemDepartamento;
    }
    
    public void setCemDepartamento(String cemDepartamento) {
        this.cemDepartamento = cemDepartamento;
    }
    public String getCemCiudad() {
        return this.cemCiudad;
    }
    
    public void setCemCiudad(String cemCiudad) {
        this.cemCiudad = cemCiudad;
    }
    public String getDemDireccion() {
        return this.demDireccion;
    }
    
    public void setDemDireccion(String demDireccion) {
        this.demDireccion = demDireccion;
    }
    public String getDemTelefono() {
        return this.demTelefono;
    }
    
    public void setDemTelefono(String demTelefono) {
        this.demTelefono = demTelefono;
    }
    public String getDemTelefono2() {
        return this.demTelefono2;
    }
    
    public void setDemTelefono2(String demTelefono2) {
        this.demTelefono2 = demTelefono2;
    }
    public String getDemTelefono3() {
        return this.demTelefono3;
    }
    
    public void setDemTelefono3(String demTelefono3) {
        this.demTelefono3 = demTelefono3;
    }
    public String getDemFax() {
        return this.demFax;
    }
    
    public void setDemFax(String demFax) {
        this.demFax = demFax;
    }
    public String getCemEstado() {
        return this.cemEstado;
    }
    
    public void setCemEstado(String cemEstado) {
        this.cemEstado = cemEstado;
    }
    public String getFemFechaIngreso() {
        return this.femFechaIngreso;
    }
    
    public void setFemFechaIngreso(String femFechaIngreso) {
        this.femFechaIngreso = femFechaIngreso;
    }
    public String getCemAplicacionTarifa() {
        return this.cemAplicacionTarifa;
    }
    
    public void setCemAplicacionTarifa(String cemAplicacionTarifa) {
        this.cemAplicacionTarifa = cemAplicacionTarifa;
    }
    public BigDecimal getNemMontoComis() {
        return this.nemMontoComis;
    }
    
    public void setNemMontoComis(BigDecimal nemMontoComis) {
        this.nemMontoComis = nemMontoComis;
    }
    public String getNemMonedaComis() {
        return this.nemMonedaComis;
    }
    
    public void setNemMonedaComis(String nemMonedaComis) {
        this.nemMonedaComis = nemMonedaComis;
    }
    public String getCemMonCtaCargoComis() {
        return this.cemMonCtaCargoComis;
    }
    
    public void setCemMonCtaCargoComis(String cemMonCtaCargoComis) {
        this.cemMonCtaCargoComis = cemMonCtaCargoComis;
    }
    public String getCemTipoCtaCargoComis() {
        return this.cemTipoCtaCargoComis;
    }
    
    public void setCemTipoCtaCargoComis(String cemTipoCtaCargoComis) {
        this.cemTipoCtaCargoComis = cemTipoCtaCargoComis;
    }
    public String getDemTipoCtaCargoComis() {
        return this.demTipoCtaCargoComis;
    }
    
    public void setDemTipoCtaCargoComis(String demTipoCtaCargoComis) {
        this.demTipoCtaCargoComis = demTipoCtaCargoComis;
    }
    public String getNemCuentaCargoComis() {
        return this.nemCuentaCargoComis;
    }
    
    public void setNemCuentaCargoComis(String nemCuentaCargoComis) {
        this.nemCuentaCargoComis = nemCuentaCargoComis;
    }
    public String getDemBeneficiarioSwift() {
        return this.demBeneficiarioSwift;
    }
    
    public void setDemBeneficiarioSwift(String demBeneficiarioSwift) {
        this.demBeneficiarioSwift = demBeneficiarioSwift;
    }
    public String getCemIdEmpresaPadre() {
        return this.cemIdEmpresaPadre;
    }
    
    public void setCemIdEmpresaPadre(String cemIdEmpresaPadre) {
        this.cemIdEmpresaPadre = cemIdEmpresaPadre;
    }
    public Integer getNemDiasRetencion() {
        return this.nemDiasRetencion;
    }
    
    public void setNemDiasRetencion(Integer nemDiasRetencion) {
        this.nemDiasRetencion = nemDiasRetencion;
    }
    public String getNemNumeroContrato() {
        return this.nemNumeroContrato;
    }
    
    public void setNemNumeroContrato(String nemNumeroContrato) {
        this.nemNumeroContrato = nemNumeroContrato;
    }
    public String getCemRubro() {
        return this.cemRubro;
    }
    
    public void setCemRubro(String cemRubro) {
        this.cemRubro = cemRubro;
    }
    public String getFemFechaFundacion() {
        return this.femFechaFundacion;
    }
    
    public void setFemFechaFundacion(String femFechaFundacion) {
        this.femFechaFundacion = femFechaFundacion;
    }
    public String getFemRegistroBanco() {
        return this.femRegistroBanco;
    }
    
    public void setFemRegistroBanco(String femRegistroBanco) {
        this.femRegistroBanco = femRegistroBanco;
    }
    public String getCemDepRegBanco() {
        return this.cemDepRegBanco;
    }
    
    public void setCemDepRegBanco(String cemDepRegBanco) {
        this.cemDepRegBanco = cemDepRegBanco;
    }
    public String getCemAgenRegBanco() {
        return this.cemAgenRegBanco;
    }
    
    public void setCemAgenRegBanco(String cemAgenRegBanco) {
        this.cemAgenRegBanco = cemAgenRegBanco;
    }
    public String getCemModifyUser() {
        return this.cemModifyUser;
    }
    
    public void setCemModifyUser(String cemModifyUser) {
        this.cemModifyUser = cemModifyUser;
    }
    public String getFemModifyDate() {
        return this.femModifyDate;
    }
    
    public void setFemModifyDate(String femModifyDate) {
        this.femModifyDate = femModifyDate;
    }
    public String getHemModifyTime() {
        return this.hemModifyTime;
    }
    
    public void setHemModifyTime(String hemModifyTime) {
        this.hemModifyTime = hemModifyTime;
    }
    public Set getTaServicioxEmpresas() {
        return this.taServicioxEmpresas;
    }
    
    public void setTaServicioxEmpresas(Set taServicioxEmpresas) {
        this.taServicioxEmpresas = taServicioxEmpresas;
    }
    public Set getTaContactoEmpresas() {
        return this.taContactoEmpresas;
    }
    
    public void setTaContactoEmpresas(Set taContactoEmpresas) {
        this.taContactoEmpresas = taContactoEmpresas;
    }
    public Set getTaFuncionarioEmpresas() {
        return this.taFuncionarioEmpresas;
    }
    
    public void setTaFuncionarioEmpresas(Set taFuncionarioEmpresas) {
        this.taFuncionarioEmpresas = taFuncionarioEmpresas;
    }


    /**
     * //jwong 17/02/2009 codigo empresa - codigo cliente
     * @return the idEmpresaCodCliente
     */
    public String getIdEmpresaCodCliente() {
        return this.cemIdEmpresa + ";" + this.cemCodigoCliente;
    }
    public String getIdEmpresaCodClienteNombre() {
        return this.cemIdEmpresa + ";" + this.cemCodigoCliente + ";" + this.demNombre;
    }

    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return this.getDemNombre();
    }


	public String getcEmRUC() {
		return cEmRUC;
	}


	public void setcEmRUC(String cEmRUC) {
		this.cEmRUC = cEmRUC;
	}

}


