package com.hiper.cash.domain;

// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TmFormato generated by hbm2java
 */
public class TmFormato implements java.io.Serializable {

	private static final long serialVersionUID = -8655831096884080778L;
	private int cfidFormato;
	private String dfnombre;
	private String dfdescripcion;
	private String cftipo;
	private String dfseparador;
	private String cfmodifyUser;
	private String ffmodifyDate;
	private String hfmodifyTime;
	private List<TaDetalleFormato> taDetalleFormatos = new ArrayList<TaDetalleFormato>(
			0);

	public TmFormato() {
	}

	public TmFormato(int cfidFormato) {
		this.cfidFormato = cfidFormato;
	}

	public TmFormato(int cfidFormato, String dfnombre, String dfdescripcion,
			String cftipo, String dfseparador, String cfmodifyUser,
			String ffmodifyDate, String hfmodifyTime,
			List<TaDetalleFormato> taDetalleFormatos) {
		this.cfidFormato = cfidFormato;
		this.dfnombre = dfnombre;
		this.dfdescripcion = dfdescripcion;
		this.cftipo = cftipo;
		this.dfseparador = dfseparador;
		this.cfmodifyUser = cfmodifyUser;
		this.ffmodifyDate = ffmodifyDate;
		this.hfmodifyTime = hfmodifyTime;
		this.taDetalleFormatos = taDetalleFormatos;
	}

	public int getCfidFormato() {
		return this.cfidFormato;
	}

	public void setCfidFormato(int cfidFormato) {
		this.cfidFormato = cfidFormato;
	}

	public String getDfnombre() {
		return this.dfnombre;
	}

	public void setDfnombre(String dfnombre) {
		this.dfnombre = dfnombre;
	}

	public String getDfdescripcion() {
		return this.dfdescripcion;
	}

	public void setDfdescripcion(String dfdescripcion) {
		this.dfdescripcion = dfdescripcion;
	}

	public String getCftipo() {
		return this.cftipo;
	}

	public void setCftipo(String cftipo) {
		this.cftipo = cftipo;
	}

	public String getDfseparador() {
		return this.dfseparador;
	}

	public void setDfseparador(String dfseparador) {
		this.dfseparador = dfseparador;
	}

	public String getCfmodifyUser() {
		return this.cfmodifyUser;
	}

	public void setCfmodifyUser(String cfmodifyUser) {
		this.cfmodifyUser = cfmodifyUser;
	}

	public String getFfmodifyDate() {
		return this.ffmodifyDate;
	}

	public void setFfmodifyDate(String ffmodifyDate) {
		this.ffmodifyDate = ffmodifyDate;
	}

	public String getHfmodifyTime() {
		return this.hfmodifyTime;
	}

	public void setHfmodifyTime(String hfmodifyTime) {
		this.hfmodifyTime = hfmodifyTime;
	}

	public List<TaDetalleFormato> getTaDetalleFormatos() {
		return this.taDetalleFormatos;
	}

	public void setTaDetalleFormatos(List<TaDetalleFormato> taDetalleFormatos) {
		this.taDetalleFormatos = taDetalleFormatos;
	}

}
