package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmFuncionario generated by hbm2java
 */
public class TmFuncionario  implements java.io.Serializable {


     private String cfuIdFuncionario;
     private String dfuNombre;
     private String dfuTelefono;
     private String dfuEmail;
     private String cfuModifyUser;
     private String ffuModifyDate;
     private String hfuModifyTime;
     private Set taFuncionarioEmpresas = new HashSet(0);
     private Set taFuncionarioServicios = new HashSet(0);

    public TmFuncionario() {
    }

	
    public TmFuncionario(String cfuIdFuncionario) {
        this.cfuIdFuncionario = cfuIdFuncionario;
    }
    public TmFuncionario(String cfuIdFuncionario, String dfuNombre, String dfuTelefono, String dfuEmail, String cfuModifyUser, String ffuModifyDate, String hfuModifyTime, Set taFuncionarioEmpresas, Set taFuncionarioServicios) {
       this.cfuIdFuncionario = cfuIdFuncionario;
       this.dfuNombre = dfuNombre;
       this.dfuTelefono = dfuTelefono;
       this.dfuEmail = dfuEmail;
       this.cfuModifyUser = cfuModifyUser;
       this.ffuModifyDate = ffuModifyDate;
       this.hfuModifyTime = hfuModifyTime;
       this.taFuncionarioEmpresas = taFuncionarioEmpresas;
       this.taFuncionarioServicios = taFuncionarioServicios;
    }
   
    public String getCfuIdFuncionario() {
        return this.cfuIdFuncionario;
    }
    
    public void setCfuIdFuncionario(String cfuIdFuncionario) {
        this.cfuIdFuncionario = cfuIdFuncionario;
    }
    public String getDfuNombre() {
        return this.dfuNombre;
    }
    
    public void setDfuNombre(String dfuNombre) {
        this.dfuNombre = dfuNombre;
    }
    public String getDfuTelefono() {
        return this.dfuTelefono;
    }
    
    public void setDfuTelefono(String dfuTelefono) {
        this.dfuTelefono = dfuTelefono;
    }
    public String getDfuEmail() {
        return this.dfuEmail;
    }
    
    public void setDfuEmail(String dfuEmail) {
        this.dfuEmail = dfuEmail;
    }
    public String getCfuModifyUser() {
        return this.cfuModifyUser;
    }
    
    public void setCfuModifyUser(String cfuModifyUser) {
        this.cfuModifyUser = cfuModifyUser;
    }
    public String getFfuModifyDate() {
        return this.ffuModifyDate;
    }
    
    public void setFfuModifyDate(String ffuModifyDate) {
        this.ffuModifyDate = ffuModifyDate;
    }
    public String getHfuModifyTime() {
        return this.hfuModifyTime;
    }
    
    public void setHfuModifyTime(String hfuModifyTime) {
        this.hfuModifyTime = hfuModifyTime;
    }
    public Set getTaFuncionarioEmpresas() {
        return this.taFuncionarioEmpresas;
    }
    
    public void setTaFuncionarioEmpresas(Set taFuncionarioEmpresas) {
        this.taFuncionarioEmpresas = taFuncionarioEmpresas;
    }
    public Set getTaFuncionarioServicios() {
        return this.taFuncionarioServicios;
    }
    
    public void setTaFuncionarioServicios(Set taFuncionarioServicios) {
        this.taFuncionarioServicios = taFuncionarioServicios;
    }




}


