package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TmGroupCard generated by hbm2java
 */
public class TmGroupCard  implements java.io.Serializable {


     private String cgrGroupId;
     private TmAcquirer tmAcquirer;
     private String cgrAcquirerAlt;
     private String dgrDescripGroup;
     private String cgrCardVerify;
     private String cgrDateExpVerify;
     private BigDecimal ngrSaleLimAmount;
     private Byte ngrSaleLimTimes;
     private String cgrSaleLimAction;
     private BigDecimal ngrCashLimAmount;
     private Byte ngrCashLimTimes;
     private String cgrCashLimAction;
     private BigDecimal ngrGasLimAmount;
     private Byte ngrGasLimTimes;
     private String cgrGasLimAction;
     private BigDecimal ngrServLimAmount;
     private Byte ngrServLimTimes;
     private String cgrServLimAction;
     private String cgrVerifyCse;
     private String cgrFlagLocalCard;
     private String cgrCardDigitNum;
     private String cgrFlagMaskCard;
     private String cgrFlagPrintSign;
     private Character cgrState;
     private Character cgrTypeCard;
     private Character cgrReqDni;
     private Character cgrReqQuota;
     private Character cgrReqMoney;
     private Character cgrReqPin;
     private Character cgrLastNumber;
     private String cgrAplicacion;
     private String cgrModifyUser;
     private String fgrModifyDate;
     private String hgrModifyTime;
     private Set taActivityLimits = new HashSet(0);

    public TmGroupCard() {
    }

	
    public TmGroupCard(String cgrGroupId, TmAcquirer tmAcquirer, String dgrDescripGroup, String cgrFlagMaskCard, String cgrFlagPrintSign) {
        this.cgrGroupId = cgrGroupId;
        this.tmAcquirer = tmAcquirer;
        this.dgrDescripGroup = dgrDescripGroup;
        this.cgrFlagMaskCard = cgrFlagMaskCard;
        this.cgrFlagPrintSign = cgrFlagPrintSign;
    }
    public TmGroupCard(String cgrGroupId, TmAcquirer tmAcquirer, String cgrAcquirerAlt, String dgrDescripGroup, String cgrCardVerify, String cgrDateExpVerify, BigDecimal ngrSaleLimAmount, Byte ngrSaleLimTimes, String cgrSaleLimAction, BigDecimal ngrCashLimAmount, Byte ngrCashLimTimes, String cgrCashLimAction, BigDecimal ngrGasLimAmount, Byte ngrGasLimTimes, String cgrGasLimAction, BigDecimal ngrServLimAmount, Byte ngrServLimTimes, String cgrServLimAction, String cgrVerifyCse, String cgrFlagLocalCard, String cgrCardDigitNum, String cgrFlagMaskCard, String cgrFlagPrintSign, Character cgrState, Character cgrTypeCard, Character cgrReqDni, Character cgrReqQuota, Character cgrReqMoney, Character cgrReqPin, Character cgrLastNumber, String cgrAplicacion, String cgrModifyUser, String fgrModifyDate, String hgrModifyTime, Set taActivityLimits) {
       this.cgrGroupId = cgrGroupId;
       this.tmAcquirer = tmAcquirer;
       this.cgrAcquirerAlt = cgrAcquirerAlt;
       this.dgrDescripGroup = dgrDescripGroup;
       this.cgrCardVerify = cgrCardVerify;
       this.cgrDateExpVerify = cgrDateExpVerify;
       this.ngrSaleLimAmount = ngrSaleLimAmount;
       this.ngrSaleLimTimes = ngrSaleLimTimes;
       this.cgrSaleLimAction = cgrSaleLimAction;
       this.ngrCashLimAmount = ngrCashLimAmount;
       this.ngrCashLimTimes = ngrCashLimTimes;
       this.cgrCashLimAction = cgrCashLimAction;
       this.ngrGasLimAmount = ngrGasLimAmount;
       this.ngrGasLimTimes = ngrGasLimTimes;
       this.cgrGasLimAction = cgrGasLimAction;
       this.ngrServLimAmount = ngrServLimAmount;
       this.ngrServLimTimes = ngrServLimTimes;
       this.cgrServLimAction = cgrServLimAction;
       this.cgrVerifyCse = cgrVerifyCse;
       this.cgrFlagLocalCard = cgrFlagLocalCard;
       this.cgrCardDigitNum = cgrCardDigitNum;
       this.cgrFlagMaskCard = cgrFlagMaskCard;
       this.cgrFlagPrintSign = cgrFlagPrintSign;
       this.cgrState = cgrState;
       this.cgrTypeCard = cgrTypeCard;
       this.cgrReqDni = cgrReqDni;
       this.cgrReqQuota = cgrReqQuota;
       this.cgrReqMoney = cgrReqMoney;
       this.cgrReqPin = cgrReqPin;
       this.cgrLastNumber = cgrLastNumber;
       this.cgrAplicacion = cgrAplicacion;
       this.cgrModifyUser = cgrModifyUser;
       this.fgrModifyDate = fgrModifyDate;
       this.hgrModifyTime = hgrModifyTime;
       this.taActivityLimits = taActivityLimits;
    }
   
    public String getCgrGroupId() {
        return this.cgrGroupId;
    }
    
    public void setCgrGroupId(String cgrGroupId) {
        this.cgrGroupId = cgrGroupId;
    }
    public TmAcquirer getTmAcquirer() {
        return this.tmAcquirer;
    }
    
    public void setTmAcquirer(TmAcquirer tmAcquirer) {
        this.tmAcquirer = tmAcquirer;
    }
    public String getCgrAcquirerAlt() {
        return this.cgrAcquirerAlt;
    }
    
    public void setCgrAcquirerAlt(String cgrAcquirerAlt) {
        this.cgrAcquirerAlt = cgrAcquirerAlt;
    }
    public String getDgrDescripGroup() {
        return this.dgrDescripGroup;
    }
    
    public void setDgrDescripGroup(String dgrDescripGroup) {
        this.dgrDescripGroup = dgrDescripGroup;
    }
    public String getCgrCardVerify() {
        return this.cgrCardVerify;
    }
    
    public void setCgrCardVerify(String cgrCardVerify) {
        this.cgrCardVerify = cgrCardVerify;
    }
    public String getCgrDateExpVerify() {
        return this.cgrDateExpVerify;
    }
    
    public void setCgrDateExpVerify(String cgrDateExpVerify) {
        this.cgrDateExpVerify = cgrDateExpVerify;
    }
    public BigDecimal getNgrSaleLimAmount() {
        return this.ngrSaleLimAmount;
    }
    
    public void setNgrSaleLimAmount(BigDecimal ngrSaleLimAmount) {
        this.ngrSaleLimAmount = ngrSaleLimAmount;
    }
    public Byte getNgrSaleLimTimes() {
        return this.ngrSaleLimTimes;
    }
    
    public void setNgrSaleLimTimes(Byte ngrSaleLimTimes) {
        this.ngrSaleLimTimes = ngrSaleLimTimes;
    }
    public String getCgrSaleLimAction() {
        return this.cgrSaleLimAction;
    }
    
    public void setCgrSaleLimAction(String cgrSaleLimAction) {
        this.cgrSaleLimAction = cgrSaleLimAction;
    }
    public BigDecimal getNgrCashLimAmount() {
        return this.ngrCashLimAmount;
    }
    
    public void setNgrCashLimAmount(BigDecimal ngrCashLimAmount) {
        this.ngrCashLimAmount = ngrCashLimAmount;
    }
    public Byte getNgrCashLimTimes() {
        return this.ngrCashLimTimes;
    }
    
    public void setNgrCashLimTimes(Byte ngrCashLimTimes) {
        this.ngrCashLimTimes = ngrCashLimTimes;
    }
    public String getCgrCashLimAction() {
        return this.cgrCashLimAction;
    }
    
    public void setCgrCashLimAction(String cgrCashLimAction) {
        this.cgrCashLimAction = cgrCashLimAction;
    }
    public BigDecimal getNgrGasLimAmount() {
        return this.ngrGasLimAmount;
    }
    
    public void setNgrGasLimAmount(BigDecimal ngrGasLimAmount) {
        this.ngrGasLimAmount = ngrGasLimAmount;
    }
    public Byte getNgrGasLimTimes() {
        return this.ngrGasLimTimes;
    }
    
    public void setNgrGasLimTimes(Byte ngrGasLimTimes) {
        this.ngrGasLimTimes = ngrGasLimTimes;
    }
    public String getCgrGasLimAction() {
        return this.cgrGasLimAction;
    }
    
    public void setCgrGasLimAction(String cgrGasLimAction) {
        this.cgrGasLimAction = cgrGasLimAction;
    }
    public BigDecimal getNgrServLimAmount() {
        return this.ngrServLimAmount;
    }
    
    public void setNgrServLimAmount(BigDecimal ngrServLimAmount) {
        this.ngrServLimAmount = ngrServLimAmount;
    }
    public Byte getNgrServLimTimes() {
        return this.ngrServLimTimes;
    }
    
    public void setNgrServLimTimes(Byte ngrServLimTimes) {
        this.ngrServLimTimes = ngrServLimTimes;
    }
    public String getCgrServLimAction() {
        return this.cgrServLimAction;
    }
    
    public void setCgrServLimAction(String cgrServLimAction) {
        this.cgrServLimAction = cgrServLimAction;
    }
    public String getCgrVerifyCse() {
        return this.cgrVerifyCse;
    }
    
    public void setCgrVerifyCse(String cgrVerifyCse) {
        this.cgrVerifyCse = cgrVerifyCse;
    }
    public String getCgrFlagLocalCard() {
        return this.cgrFlagLocalCard;
    }
    
    public void setCgrFlagLocalCard(String cgrFlagLocalCard) {
        this.cgrFlagLocalCard = cgrFlagLocalCard;
    }
    public String getCgrCardDigitNum() {
        return this.cgrCardDigitNum;
    }
    
    public void setCgrCardDigitNum(String cgrCardDigitNum) {
        this.cgrCardDigitNum = cgrCardDigitNum;
    }
    public String getCgrFlagMaskCard() {
        return this.cgrFlagMaskCard;
    }
    
    public void setCgrFlagMaskCard(String cgrFlagMaskCard) {
        this.cgrFlagMaskCard = cgrFlagMaskCard;
    }
    public String getCgrFlagPrintSign() {
        return this.cgrFlagPrintSign;
    }
    
    public void setCgrFlagPrintSign(String cgrFlagPrintSign) {
        this.cgrFlagPrintSign = cgrFlagPrintSign;
    }
    public Character getCgrState() {
        return this.cgrState;
    }
    
    public void setCgrState(Character cgrState) {
        this.cgrState = cgrState;
    }
    public Character getCgrTypeCard() {
        return this.cgrTypeCard;
    }
    
    public void setCgrTypeCard(Character cgrTypeCard) {
        this.cgrTypeCard = cgrTypeCard;
    }
    public Character getCgrReqDni() {
        return this.cgrReqDni;
    }
    
    public void setCgrReqDni(Character cgrReqDni) {
        this.cgrReqDni = cgrReqDni;
    }
    public Character getCgrReqQuota() {
        return this.cgrReqQuota;
    }
    
    public void setCgrReqQuota(Character cgrReqQuota) {
        this.cgrReqQuota = cgrReqQuota;
    }
    public Character getCgrReqMoney() {
        return this.cgrReqMoney;
    }
    
    public void setCgrReqMoney(Character cgrReqMoney) {
        this.cgrReqMoney = cgrReqMoney;
    }
    public Character getCgrReqPin() {
        return this.cgrReqPin;
    }
    
    public void setCgrReqPin(Character cgrReqPin) {
        this.cgrReqPin = cgrReqPin;
    }
    public Character getCgrLastNumber() {
        return this.cgrLastNumber;
    }
    
    public void setCgrLastNumber(Character cgrLastNumber) {
        this.cgrLastNumber = cgrLastNumber;
    }
    public String getCgrAplicacion() {
        return this.cgrAplicacion;
    }
    
    public void setCgrAplicacion(String cgrAplicacion) {
        this.cgrAplicacion = cgrAplicacion;
    }
    public String getCgrModifyUser() {
        return this.cgrModifyUser;
    }
    
    public void setCgrModifyUser(String cgrModifyUser) {
        this.cgrModifyUser = cgrModifyUser;
    }
    public String getFgrModifyDate() {
        return this.fgrModifyDate;
    }
    
    public void setFgrModifyDate(String fgrModifyDate) {
        this.fgrModifyDate = fgrModifyDate;
    }
    public String getHgrModifyTime() {
        return this.hgrModifyTime;
    }
    
    public void setHgrModifyTime(String hgrModifyTime) {
        this.hgrModifyTime = hgrModifyTime;
    }
    public Set getTaActivityLimits() {
        return this.taActivityLimits;
    }
    
    public void setTaActivityLimits(Set taActivityLimits) {
        this.taActivityLimits = taActivityLimits;
    }




}


