package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmMerchantChain generated by hbm2java
 */
public class TmMerchantChain  implements java.io.Serializable {


     private long cmcchainId;
     private String dmcchainName;
     private String dmcdescription;
     private String dmcruc;
     private String cmcmodifyUser;
     private String fmcmodifyDate;
     private String hmcmodifyTime;
     private Character cmclogicalStatus;
     private Set tmMerchants = new HashSet(0);

    public TmMerchantChain() {
    }

	
    public TmMerchantChain(long cmcchainId, String dmcchainName) {
        this.cmcchainId = cmcchainId;
        this.dmcchainName = dmcchainName;
    }
    public TmMerchantChain(long cmcchainId, String dmcchainName, String dmcdescription, String dmcruc, String cmcmodifyUser, String fmcmodifyDate, String hmcmodifyTime, Character cmclogicalStatus, Set tmMerchants) {
       this.cmcchainId = cmcchainId;
       this.dmcchainName = dmcchainName;
       this.dmcdescription = dmcdescription;
       this.dmcruc = dmcruc;
       this.cmcmodifyUser = cmcmodifyUser;
       this.fmcmodifyDate = fmcmodifyDate;
       this.hmcmodifyTime = hmcmodifyTime;
       this.cmclogicalStatus = cmclogicalStatus;
       this.tmMerchants = tmMerchants;
    }
   
    public long getCmcchainId() {
        return this.cmcchainId;
    }
    
    public void setCmcchainId(long cmcchainId) {
        this.cmcchainId = cmcchainId;
    }
    public String getDmcchainName() {
        return this.dmcchainName;
    }
    
    public void setDmcchainName(String dmcchainName) {
        this.dmcchainName = dmcchainName;
    }
    public String getDmcdescription() {
        return this.dmcdescription;
    }
    
    public void setDmcdescription(String dmcdescription) {
        this.dmcdescription = dmcdescription;
    }
    public String getDmcruc() {
        return this.dmcruc;
    }
    
    public void setDmcruc(String dmcruc) {
        this.dmcruc = dmcruc;
    }
    public String getCmcmodifyUser() {
        return this.cmcmodifyUser;
    }
    
    public void setCmcmodifyUser(String cmcmodifyUser) {
        this.cmcmodifyUser = cmcmodifyUser;
    }
    public String getFmcmodifyDate() {
        return this.fmcmodifyDate;
    }
    
    public void setFmcmodifyDate(String fmcmodifyDate) {
        this.fmcmodifyDate = fmcmodifyDate;
    }
    public String getHmcmodifyTime() {
        return this.hmcmodifyTime;
    }
    
    public void setHmcmodifyTime(String hmcmodifyTime) {
        this.hmcmodifyTime = hmcmodifyTime;
    }
    public Character getCmclogicalStatus() {
        return this.cmclogicalStatus;
    }
    
    public void setCmclogicalStatus(Character cmclogicalStatus) {
        this.cmclogicalStatus = cmclogicalStatus;
    }
    public Set getTmMerchants() {
        return this.tmMerchants;
    }
    
    public void setTmMerchants(Set tmMerchants) {
        this.tmMerchants = tmMerchants;
    }




}


