package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TmMerchant generated by hbm2java
 */
public class TmMerchant  implements java.io.Serializable {


     private String cmrMerchantId;
     private TmMerchantProfile tmMerchantProfile;
     private TmMerchantChain tmMerchantChain;
     private String cmrStatus;
     private String dmrContactName;
     private String dmrMerchantName;
     private String dmrAddress;
     private String dmrPhone;
     private String cmrDepartCode;
     private String cmrProvinceCode;
     private String cmrDistrictCode;
     private String fmrContrSignDate;
     private String cmrTransSale;
     private String cmrTransCash;
     private String cmrTransGas;
     private String cmrTransService;
     private Byte nmrFreqSettle;
     private String cmrMcc;
     private Character cmrReqCashBack;
     private Character cmrTransPreAutorization;
     private Character cmrTransConfirmacion;
     private Character cmrTransSalePoints;
     private Character cmrTransPoints;
     private Character cmrTransPropina;
     private Character cmrTransPagoService;
     private Character cmrTransAnular;
     private Character cmrTransAnularPs;
     private Character cmrTransAnularSp;
     private Character cmrTransCierre;
     private String cmrRucCode;
     private String cmrAdministratorKey;
     private Character cmrAccessType;
     private Character cmrCloseType;
     private String cmrCloseTime;
     private Character cmrAccessTrx;
     private Character cmrCardWriter;
     private Character cmrPropina;
     private Character cmrMoneyMult;
     private Character cmrLastNumber;
     private Character cmrReqDni;
     private BigDecimal cmrLimitAmount;
     private BigDecimal cmrSaldoAmount;
     private String cmrVoidKey;
     private String cmrSettleKey;
     private String cmrPaymentKey;
     private String cmrDigitKey;
     private String cmrNetBin;
     private String cmrOperatorReq;
     private String cmrValOperator;
     private BigDecimal cmrLimitAmountDollar;
     private BigDecimal cmrSaldoAmountDollar;
     private String cmrModifyUser;
     private String fmrModifyDate;
     private String hmrModifyTime;
     private long cmrDownloadProfile;
     private Character cmrForceUpdate;
     private Character cmrLogicalStatus;
     private String cmrConfigKey;
     private Set tmTerminals = new HashSet(0);

    public TmMerchant() {
    }

	
    public TmMerchant(String cmrMerchantId, TmMerchantProfile tmMerchantProfile, TmMerchantChain tmMerchantChain, String cmrStatus, String dmrMerchantName, String cmrTransSale, String cmrTransCash, String cmrTransGas, String cmrTransService, long cmrDownloadProfile) {
        this.cmrMerchantId = cmrMerchantId;
        this.tmMerchantProfile = tmMerchantProfile;
        this.tmMerchantChain = tmMerchantChain;
        this.cmrStatus = cmrStatus;
        this.dmrMerchantName = dmrMerchantName;
        this.cmrTransSale = cmrTransSale;
        this.cmrTransCash = cmrTransCash;
        this.cmrTransGas = cmrTransGas;
        this.cmrTransService = cmrTransService;
        this.cmrDownloadProfile = cmrDownloadProfile;
    }
    public TmMerchant(String cmrMerchantId, TmMerchantProfile tmMerchantProfile, TmMerchantChain tmMerchantChain, String cmrStatus, String dmrContactName, String dmrMerchantName, String dmrAddress, String dmrPhone, String cmrDepartCode, String cmrProvinceCode, String cmrDistrictCode, String fmrContrSignDate, String cmrTransSale, String cmrTransCash, String cmrTransGas, String cmrTransService, Byte nmrFreqSettle, String cmrMcc, Character cmrReqCashBack, Character cmrTransPreAutorization, Character cmrTransConfirmacion, Character cmrTransSalePoints, Character cmrTransPoints, Character cmrTransPropina, Character cmrTransPagoService, Character cmrTransAnular, Character cmrTransAnularPs, Character cmrTransAnularSp, Character cmrTransCierre, String cmrRucCode, String cmrAdministratorKey, Character cmrAccessType, Character cmrCloseType, String cmrCloseTime, Character cmrAccessTrx, Character cmrCardWriter, Character cmrPropina, Character cmrMoneyMult, Character cmrLastNumber, Character cmrReqDni, BigDecimal cmrLimitAmount, BigDecimal cmrSaldoAmount, String cmrVoidKey, String cmrSettleKey, String cmrPaymentKey, String cmrDigitKey, String cmrNetBin, String cmrOperatorReq, String cmrValOperator, BigDecimal cmrLimitAmountDollar, BigDecimal cmrSaldoAmountDollar, String cmrModifyUser, String fmrModifyDate, String hmrModifyTime, long cmrDownloadProfile, Character cmrForceUpdate, Character cmrLogicalStatus, String cmrConfigKey, Set tmTerminals) {
       this.cmrMerchantId = cmrMerchantId;
       this.tmMerchantProfile = tmMerchantProfile;
       this.tmMerchantChain = tmMerchantChain;
       this.cmrStatus = cmrStatus;
       this.dmrContactName = dmrContactName;
       this.dmrMerchantName = dmrMerchantName;
       this.dmrAddress = dmrAddress;
       this.dmrPhone = dmrPhone;
       this.cmrDepartCode = cmrDepartCode;
       this.cmrProvinceCode = cmrProvinceCode;
       this.cmrDistrictCode = cmrDistrictCode;
       this.fmrContrSignDate = fmrContrSignDate;
       this.cmrTransSale = cmrTransSale;
       this.cmrTransCash = cmrTransCash;
       this.cmrTransGas = cmrTransGas;
       this.cmrTransService = cmrTransService;
       this.nmrFreqSettle = nmrFreqSettle;
       this.cmrMcc = cmrMcc;
       this.cmrReqCashBack = cmrReqCashBack;
       this.cmrTransPreAutorization = cmrTransPreAutorization;
       this.cmrTransConfirmacion = cmrTransConfirmacion;
       this.cmrTransSalePoints = cmrTransSalePoints;
       this.cmrTransPoints = cmrTransPoints;
       this.cmrTransPropina = cmrTransPropina;
       this.cmrTransPagoService = cmrTransPagoService;
       this.cmrTransAnular = cmrTransAnular;
       this.cmrTransAnularPs = cmrTransAnularPs;
       this.cmrTransAnularSp = cmrTransAnularSp;
       this.cmrTransCierre = cmrTransCierre;
       this.cmrRucCode = cmrRucCode;
       this.cmrAdministratorKey = cmrAdministratorKey;
       this.cmrAccessType = cmrAccessType;
       this.cmrCloseType = cmrCloseType;
       this.cmrCloseTime = cmrCloseTime;
       this.cmrAccessTrx = cmrAccessTrx;
       this.cmrCardWriter = cmrCardWriter;
       this.cmrPropina = cmrPropina;
       this.cmrMoneyMult = cmrMoneyMult;
       this.cmrLastNumber = cmrLastNumber;
       this.cmrReqDni = cmrReqDni;
       this.cmrLimitAmount = cmrLimitAmount;
       this.cmrSaldoAmount = cmrSaldoAmount;
       this.cmrVoidKey = cmrVoidKey;
       this.cmrSettleKey = cmrSettleKey;
       this.cmrPaymentKey = cmrPaymentKey;
       this.cmrDigitKey = cmrDigitKey;
       this.cmrNetBin = cmrNetBin;
       this.cmrOperatorReq = cmrOperatorReq;
       this.cmrValOperator = cmrValOperator;
       this.cmrLimitAmountDollar = cmrLimitAmountDollar;
       this.cmrSaldoAmountDollar = cmrSaldoAmountDollar;
       this.cmrModifyUser = cmrModifyUser;
       this.fmrModifyDate = fmrModifyDate;
       this.hmrModifyTime = hmrModifyTime;
       this.cmrDownloadProfile = cmrDownloadProfile;
       this.cmrForceUpdate = cmrForceUpdate;
       this.cmrLogicalStatus = cmrLogicalStatus;
       this.cmrConfigKey = cmrConfigKey;
       this.tmTerminals = tmTerminals;
    }
   
    public String getCmrMerchantId() {
        return this.cmrMerchantId;
    }
    
    public void setCmrMerchantId(String cmrMerchantId) {
        this.cmrMerchantId = cmrMerchantId;
    }
    public TmMerchantProfile getTmMerchantProfile() {
        return this.tmMerchantProfile;
    }
    
    public void setTmMerchantProfile(TmMerchantProfile tmMerchantProfile) {
        this.tmMerchantProfile = tmMerchantProfile;
    }
    public TmMerchantChain getTmMerchantChain() {
        return this.tmMerchantChain;
    }
    
    public void setTmMerchantChain(TmMerchantChain tmMerchantChain) {
        this.tmMerchantChain = tmMerchantChain;
    }
    public String getCmrStatus() {
        return this.cmrStatus;
    }
    
    public void setCmrStatus(String cmrStatus) {
        this.cmrStatus = cmrStatus;
    }
    public String getDmrContactName() {
        return this.dmrContactName;
    }
    
    public void setDmrContactName(String dmrContactName) {
        this.dmrContactName = dmrContactName;
    }
    public String getDmrMerchantName() {
        return this.dmrMerchantName;
    }
    
    public void setDmrMerchantName(String dmrMerchantName) {
        this.dmrMerchantName = dmrMerchantName;
    }
    public String getDmrAddress() {
        return this.dmrAddress;
    }
    
    public void setDmrAddress(String dmrAddress) {
        this.dmrAddress = dmrAddress;
    }
    public String getDmrPhone() {
        return this.dmrPhone;
    }
    
    public void setDmrPhone(String dmrPhone) {
        this.dmrPhone = dmrPhone;
    }
    public String getCmrDepartCode() {
        return this.cmrDepartCode;
    }
    
    public void setCmrDepartCode(String cmrDepartCode) {
        this.cmrDepartCode = cmrDepartCode;
    }
    public String getCmrProvinceCode() {
        return this.cmrProvinceCode;
    }
    
    public void setCmrProvinceCode(String cmrProvinceCode) {
        this.cmrProvinceCode = cmrProvinceCode;
    }
    public String getCmrDistrictCode() {
        return this.cmrDistrictCode;
    }
    
    public void setCmrDistrictCode(String cmrDistrictCode) {
        this.cmrDistrictCode = cmrDistrictCode;
    }
    public String getFmrContrSignDate() {
        return this.fmrContrSignDate;
    }
    
    public void setFmrContrSignDate(String fmrContrSignDate) {
        this.fmrContrSignDate = fmrContrSignDate;
    }
    public String getCmrTransSale() {
        return this.cmrTransSale;
    }
    
    public void setCmrTransSale(String cmrTransSale) {
        this.cmrTransSale = cmrTransSale;
    }
    public String getCmrTransCash() {
        return this.cmrTransCash;
    }
    
    public void setCmrTransCash(String cmrTransCash) {
        this.cmrTransCash = cmrTransCash;
    }
    public String getCmrTransGas() {
        return this.cmrTransGas;
    }
    
    public void setCmrTransGas(String cmrTransGas) {
        this.cmrTransGas = cmrTransGas;
    }
    public String getCmrTransService() {
        return this.cmrTransService;
    }
    
    public void setCmrTransService(String cmrTransService) {
        this.cmrTransService = cmrTransService;
    }
    public Byte getNmrFreqSettle() {
        return this.nmrFreqSettle;
    }
    
    public void setNmrFreqSettle(Byte nmrFreqSettle) {
        this.nmrFreqSettle = nmrFreqSettle;
    }
    public String getCmrMcc() {
        return this.cmrMcc;
    }
    
    public void setCmrMcc(String cmrMcc) {
        this.cmrMcc = cmrMcc;
    }
    public Character getCmrReqCashBack() {
        return this.cmrReqCashBack;
    }
    
    public void setCmrReqCashBack(Character cmrReqCashBack) {
        this.cmrReqCashBack = cmrReqCashBack;
    }
    public Character getCmrTransPreAutorization() {
        return this.cmrTransPreAutorization;
    }
    
    public void setCmrTransPreAutorization(Character cmrTransPreAutorization) {
        this.cmrTransPreAutorization = cmrTransPreAutorization;
    }
    public Character getCmrTransConfirmacion() {
        return this.cmrTransConfirmacion;
    }
    
    public void setCmrTransConfirmacion(Character cmrTransConfirmacion) {
        this.cmrTransConfirmacion = cmrTransConfirmacion;
    }
    public Character getCmrTransSalePoints() {
        return this.cmrTransSalePoints;
    }
    
    public void setCmrTransSalePoints(Character cmrTransSalePoints) {
        this.cmrTransSalePoints = cmrTransSalePoints;
    }
    public Character getCmrTransPoints() {
        return this.cmrTransPoints;
    }
    
    public void setCmrTransPoints(Character cmrTransPoints) {
        this.cmrTransPoints = cmrTransPoints;
    }
    public Character getCmrTransPropina() {
        return this.cmrTransPropina;
    }
    
    public void setCmrTransPropina(Character cmrTransPropina) {
        this.cmrTransPropina = cmrTransPropina;
    }
    public Character getCmrTransPagoService() {
        return this.cmrTransPagoService;
    }
    
    public void setCmrTransPagoService(Character cmrTransPagoService) {
        this.cmrTransPagoService = cmrTransPagoService;
    }
    public Character getCmrTransAnular() {
        return this.cmrTransAnular;
    }
    
    public void setCmrTransAnular(Character cmrTransAnular) {
        this.cmrTransAnular = cmrTransAnular;
    }
    public Character getCmrTransAnularPs() {
        return this.cmrTransAnularPs;
    }
    
    public void setCmrTransAnularPs(Character cmrTransAnularPs) {
        this.cmrTransAnularPs = cmrTransAnularPs;
    }
    public Character getCmrTransAnularSp() {
        return this.cmrTransAnularSp;
    }
    
    public void setCmrTransAnularSp(Character cmrTransAnularSp) {
        this.cmrTransAnularSp = cmrTransAnularSp;
    }
    public Character getCmrTransCierre() {
        return this.cmrTransCierre;
    }
    
    public void setCmrTransCierre(Character cmrTransCierre) {
        this.cmrTransCierre = cmrTransCierre;
    }
    public String getCmrRucCode() {
        return this.cmrRucCode;
    }
    
    public void setCmrRucCode(String cmrRucCode) {
        this.cmrRucCode = cmrRucCode;
    }
    public String getCmrAdministratorKey() {
        return this.cmrAdministratorKey;
    }
    
    public void setCmrAdministratorKey(String cmrAdministratorKey) {
        this.cmrAdministratorKey = cmrAdministratorKey;
    }
    public Character getCmrAccessType() {
        return this.cmrAccessType;
    }
    
    public void setCmrAccessType(Character cmrAccessType) {
        this.cmrAccessType = cmrAccessType;
    }
    public Character getCmrCloseType() {
        return this.cmrCloseType;
    }
    
    public void setCmrCloseType(Character cmrCloseType) {
        this.cmrCloseType = cmrCloseType;
    }
    public String getCmrCloseTime() {
        return this.cmrCloseTime;
    }
    
    public void setCmrCloseTime(String cmrCloseTime) {
        this.cmrCloseTime = cmrCloseTime;
    }
    public Character getCmrAccessTrx() {
        return this.cmrAccessTrx;
    }
    
    public void setCmrAccessTrx(Character cmrAccessTrx) {
        this.cmrAccessTrx = cmrAccessTrx;
    }
    public Character getCmrCardWriter() {
        return this.cmrCardWriter;
    }
    
    public void setCmrCardWriter(Character cmrCardWriter) {
        this.cmrCardWriter = cmrCardWriter;
    }
    public Character getCmrPropina() {
        return this.cmrPropina;
    }
    
    public void setCmrPropina(Character cmrPropina) {
        this.cmrPropina = cmrPropina;
    }
    public Character getCmrMoneyMult() {
        return this.cmrMoneyMult;
    }
    
    public void setCmrMoneyMult(Character cmrMoneyMult) {
        this.cmrMoneyMult = cmrMoneyMult;
    }
    public Character getCmrLastNumber() {
        return this.cmrLastNumber;
    }
    
    public void setCmrLastNumber(Character cmrLastNumber) {
        this.cmrLastNumber = cmrLastNumber;
    }
    public Character getCmrReqDni() {
        return this.cmrReqDni;
    }
    
    public void setCmrReqDni(Character cmrReqDni) {
        this.cmrReqDni = cmrReqDni;
    }
    public BigDecimal getCmrLimitAmount() {
        return this.cmrLimitAmount;
    }
    
    public void setCmrLimitAmount(BigDecimal cmrLimitAmount) {
        this.cmrLimitAmount = cmrLimitAmount;
    }
    public BigDecimal getCmrSaldoAmount() {
        return this.cmrSaldoAmount;
    }
    
    public void setCmrSaldoAmount(BigDecimal cmrSaldoAmount) {
        this.cmrSaldoAmount = cmrSaldoAmount;
    }
    public String getCmrVoidKey() {
        return this.cmrVoidKey;
    }
    
    public void setCmrVoidKey(String cmrVoidKey) {
        this.cmrVoidKey = cmrVoidKey;
    }
    public String getCmrSettleKey() {
        return this.cmrSettleKey;
    }
    
    public void setCmrSettleKey(String cmrSettleKey) {
        this.cmrSettleKey = cmrSettleKey;
    }
    public String getCmrPaymentKey() {
        return this.cmrPaymentKey;
    }
    
    public void setCmrPaymentKey(String cmrPaymentKey) {
        this.cmrPaymentKey = cmrPaymentKey;
    }
    public String getCmrDigitKey() {
        return this.cmrDigitKey;
    }
    
    public void setCmrDigitKey(String cmrDigitKey) {
        this.cmrDigitKey = cmrDigitKey;
    }
    public String getCmrNetBin() {
        return this.cmrNetBin;
    }
    
    public void setCmrNetBin(String cmrNetBin) {
        this.cmrNetBin = cmrNetBin;
    }
    public String getCmrOperatorReq() {
        return this.cmrOperatorReq;
    }
    
    public void setCmrOperatorReq(String cmrOperatorReq) {
        this.cmrOperatorReq = cmrOperatorReq;
    }
    public String getCmrValOperator() {
        return this.cmrValOperator;
    }
    
    public void setCmrValOperator(String cmrValOperator) {
        this.cmrValOperator = cmrValOperator;
    }
    public BigDecimal getCmrLimitAmountDollar() {
        return this.cmrLimitAmountDollar;
    }
    
    public void setCmrLimitAmountDollar(BigDecimal cmrLimitAmountDollar) {
        this.cmrLimitAmountDollar = cmrLimitAmountDollar;
    }
    public BigDecimal getCmrSaldoAmountDollar() {
        return this.cmrSaldoAmountDollar;
    }
    
    public void setCmrSaldoAmountDollar(BigDecimal cmrSaldoAmountDollar) {
        this.cmrSaldoAmountDollar = cmrSaldoAmountDollar;
    }
    public String getCmrModifyUser() {
        return this.cmrModifyUser;
    }
    
    public void setCmrModifyUser(String cmrModifyUser) {
        this.cmrModifyUser = cmrModifyUser;
    }
    public String getFmrModifyDate() {
        return this.fmrModifyDate;
    }
    
    public void setFmrModifyDate(String fmrModifyDate) {
        this.fmrModifyDate = fmrModifyDate;
    }
    public String getHmrModifyTime() {
        return this.hmrModifyTime;
    }
    
    public void setHmrModifyTime(String hmrModifyTime) {
        this.hmrModifyTime = hmrModifyTime;
    }
    public long getCmrDownloadProfile() {
        return this.cmrDownloadProfile;
    }
    
    public void setCmrDownloadProfile(long cmrDownloadProfile) {
        this.cmrDownloadProfile = cmrDownloadProfile;
    }
    public Character getCmrForceUpdate() {
        return this.cmrForceUpdate;
    }
    
    public void setCmrForceUpdate(Character cmrForceUpdate) {
        this.cmrForceUpdate = cmrForceUpdate;
    }
    public Character getCmrLogicalStatus() {
        return this.cmrLogicalStatus;
    }
    
    public void setCmrLogicalStatus(Character cmrLogicalStatus) {
        this.cmrLogicalStatus = cmrLogicalStatus;
    }
    public String getCmrConfigKey() {
        return this.cmrConfigKey;
    }
    
    public void setCmrConfigKey(String cmrConfigKey) {
        this.cmrConfigKey = cmrConfigKey;
    }
    public Set getTmTerminals() {
        return this.tmTerminals;
    }
    
    public void setTmTerminals(Set tmTerminals) {
        this.tmTerminals = tmTerminals;
    }




}


