package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmMerchantProfile generated by hbm2java
 */
public class TmMerchantProfile  implements java.io.Serializable {


     private String cmpprofileId;
     private String cmpModifyUser;
     private String fmpModifyDate;
     private String hmpModifyTime;
     private Set taMerchantProfileApplications = new HashSet(0);
     private Set tmMerchants = new HashSet(0);
     private Set taFloorLimits = new HashSet(0);

    public TmMerchantProfile() {
    }

	
    public TmMerchantProfile(String cmpprofileId) {
        this.cmpprofileId = cmpprofileId;
    }
    public TmMerchantProfile(String cmpprofileId, String cmpModifyUser, String fmpModifyDate, String hmpModifyTime, Set taMerchantProfileApplications, Set tmMerchants, Set taFloorLimits) {
       this.cmpprofileId = cmpprofileId;
       this.cmpModifyUser = cmpModifyUser;
       this.fmpModifyDate = fmpModifyDate;
       this.hmpModifyTime = hmpModifyTime;
       this.taMerchantProfileApplications = taMerchantProfileApplications;
       this.tmMerchants = tmMerchants;
       this.taFloorLimits = taFloorLimits;
    }
   
    public String getCmpprofileId() {
        return this.cmpprofileId;
    }
    
    public void setCmpprofileId(String cmpprofileId) {
        this.cmpprofileId = cmpprofileId;
    }
    public String getCmpModifyUser() {
        return this.cmpModifyUser;
    }
    
    public void setCmpModifyUser(String cmpModifyUser) {
        this.cmpModifyUser = cmpModifyUser;
    }
    public String getFmpModifyDate() {
        return this.fmpModifyDate;
    }
    
    public void setFmpModifyDate(String fmpModifyDate) {
        this.fmpModifyDate = fmpModifyDate;
    }
    public String getHmpModifyTime() {
        return this.hmpModifyTime;
    }
    
    public void setHmpModifyTime(String hmpModifyTime) {
        this.hmpModifyTime = hmpModifyTime;
    }
    public Set getTaMerchantProfileApplications() {
        return this.taMerchantProfileApplications;
    }
    
    public void setTaMerchantProfileApplications(Set taMerchantProfileApplications) {
        this.taMerchantProfileApplications = taMerchantProfileApplications;
    }
    public Set getTmMerchants() {
        return this.tmMerchants;
    }
    
    public void setTmMerchants(Set tmMerchants) {
        this.tmMerchants = tmMerchants;
    }
    public Set getTaFloorLimits() {
        return this.taFloorLimits;
    }
    
    public void setTaFloorLimits(Set taFloorLimits) {
        this.taFloorLimits = taFloorLimits;
    }




}


