package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmServicio generated by hbm2java
 */
public class TmServicio  implements java.io.Serializable {


     private String csrIdServicio;
     private String dsrDescripcion;
     private String csrTipo;
     private Character csrFlagInformacion;
     private String csrModifyUser;
     private String fsrModifyDate;
     private String hsrModifyTime;
     private String csrServicioPadre;
     private Character csrFlagVisible;
     private Set taServicioxEmpresas = new HashSet(0);
     private Set taServicioOpcions = new HashSet(0);

    public TmServicio() {
    }

	
    public TmServicio(String csrIdServicio, String dsrDescripcion) {
        this.csrIdServicio = csrIdServicio;
        this.dsrDescripcion = dsrDescripcion;
    }
    public TmServicio(String csrIdServicio, String dsrDescripcion, String csrTipo, Character csrFlagInformacion, String csrModifyUser, String fsrModifyDate, String hsrModifyTime, String csrServicioPadre, Character csrFlagVisible, Set taServicioxEmpresas, Set taServicioOpcions) {
       this.csrIdServicio = csrIdServicio;
       this.dsrDescripcion = dsrDescripcion;
       this.csrTipo = csrTipo;
       this.csrFlagInformacion = csrFlagInformacion;
       this.csrModifyUser = csrModifyUser;
       this.fsrModifyDate = fsrModifyDate;
       this.hsrModifyTime = hsrModifyTime;
       this.csrServicioPadre = csrServicioPadre;
       this.csrFlagVisible = csrFlagVisible;
       this.taServicioxEmpresas = taServicioxEmpresas;
       this.taServicioOpcions = taServicioOpcions;
    }
   
    public String getCsrIdServicio() {
        return this.csrIdServicio;
    }
    
    public void setCsrIdServicio(String csrIdServicio) {
        this.csrIdServicio = csrIdServicio;
    }
    public String getDsrDescripcion() {
        return this.dsrDescripcion;
    }
    
    public void setDsrDescripcion(String dsrDescripcion) {
        this.dsrDescripcion = dsrDescripcion;
    }
    public String getCsrTipo() {
        return this.csrTipo;
    }
    
    public void setCsrTipo(String csrTipo) {
        this.csrTipo = csrTipo;
    }
    public Character getCsrFlagInformacion() {
        return this.csrFlagInformacion;
    }
    
    public void setCsrFlagInformacion(Character csrFlagInformacion) {
        this.csrFlagInformacion = csrFlagInformacion;
    }
    public String getCsrModifyUser() {
        return this.csrModifyUser;
    }
    
    public void setCsrModifyUser(String csrModifyUser) {
        this.csrModifyUser = csrModifyUser;
    }
    public String getFsrModifyDate() {
        return this.fsrModifyDate;
    }
    
    public void setFsrModifyDate(String fsrModifyDate) {
        this.fsrModifyDate = fsrModifyDate;
    }
    public String getHsrModifyTime() {
        return this.hsrModifyTime;
    }
    
    public void setHsrModifyTime(String hsrModifyTime) {
        this.hsrModifyTime = hsrModifyTime;
    }
    public String getCsrServicioPadre() {
        return this.csrServicioPadre;
    }
    
    public void setCsrServicioPadre(String csrServicioPadre) {
        this.csrServicioPadre = csrServicioPadre;
    }
    public Character getCsrFlagVisible() {
        return this.csrFlagVisible;
    }
    
    public void setCsrFlagVisible(Character csrFlagVisible) {
        this.csrFlagVisible = csrFlagVisible;
    }
    public Set getTaServicioxEmpresas() {
        return this.taServicioxEmpresas;
    }
    
    public void setTaServicioxEmpresas(Set taServicioxEmpresas) {
        this.taServicioxEmpresas = taServicioxEmpresas;
    }
    public Set getTaServicioOpcions() {
        return this.taServicioOpcions;
    }
    
    public void setTaServicioOpcions(Set taServicioOpcions) {
        this.taServicioOpcions = taServicioOpcions;
    }


    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return  this.getDsrDescripcion();
    }


}


