package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TmSoporte generated by hbm2java
 */
public class TmSoporte  implements java.io.Serializable {


     private int csoId;
     private String dsoNombre;
     private String nsoTelefono;
     private String nsoAnexo;
     private String nsoMovil;
     private String dsoEmail;

    public TmSoporte() {
    }

	
    public TmSoporte(int csoId) {
        this.csoId = csoId;
    }
    public TmSoporte(int csoId, String dsoNombre, String nsoTelefono, String nsoAnexo, String nsoMovil, String dsoEmail) {
       this.csoId = csoId;
       this.dsoNombre = dsoNombre;
       this.nsoTelefono = nsoTelefono;
       this.nsoAnexo = nsoAnexo;
       this.nsoMovil = nsoMovil;
       this.dsoEmail = dsoEmail;
    }
   
    public int getCsoId() {
        return this.csoId;
    }
    
    public void setCsoId(int csoId) {
        this.csoId = csoId;
    }
    public String getDsoNombre() {
        return this.dsoNombre;
    }
    
    public void setDsoNombre(String dsoNombre) {
        this.dsoNombre = dsoNombre;
    }
    public String getNsoTelefono() {
        return this.nsoTelefono;
    }
    
    public void setNsoTelefono(String nsoTelefono) {
        this.nsoTelefono = nsoTelefono;
    }
    public String getNsoAnexo() {
        return this.nsoAnexo;
    }
    
    public void setNsoAnexo(String nsoAnexo) {
        this.nsoAnexo = nsoAnexo;
    }
    public String getNsoMovil() {
        return this.nsoMovil;
    }
    
    public void setNsoMovil(String nsoMovil) {
        this.nsoMovil = nsoMovil;
    }
    public String getDsoEmail() {
        return this.dsoEmail;
    }
    
    public void setDsoEmail(String dsoEmail) {
        this.dsoEmail = dsoEmail;
    }




}


