package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TmTerminalId generated by hbm2java
 */
public class TmTerminalId  implements java.io.Serializable {


     private String ctrMerchantId;
     private String ctrTerminalNum;

    public TmTerminalId() {
    }

    public TmTerminalId(String ctrMerchantId, String ctrTerminalNum) {
       this.ctrMerchantId = ctrMerchantId;
       this.ctrTerminalNum = ctrTerminalNum;
    }
   
    public String getCtrMerchantId() {
        return this.ctrMerchantId;
    }
    
    public void setCtrMerchantId(String ctrMerchantId) {
        this.ctrMerchantId = ctrMerchantId;
    }
    public String getCtrTerminalNum() {
        return this.ctrTerminalNum;
    }
    
    public void setCtrTerminalNum(String ctrTerminalNum) {
        this.ctrTerminalNum = ctrTerminalNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmTerminalId) ) return false;
		 TmTerminalId castOther = ( TmTerminalId ) other; 
         
		 return ( (this.getCtrMerchantId()==castOther.getCtrMerchantId()) || ( this.getCtrMerchantId()!=null && castOther.getCtrMerchantId()!=null && this.getCtrMerchantId().equals(castOther.getCtrMerchantId()) ) )
 && ( (this.getCtrTerminalNum()==castOther.getCtrTerminalNum()) || ( this.getCtrTerminalNum()!=null && castOther.getCtrTerminalNum()!=null && this.getCtrTerminalNum().equals(castOther.getCtrTerminalNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCtrMerchantId() == null ? 0 : this.getCtrMerchantId().hashCode() );
         result = 37 * result + ( getCtrTerminalNum() == null ? 0 : this.getCtrTerminalNum().hashCode() );
         return result;
   }   


}


