package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TmTerminal generated by hbm2java
 */
public class TmTerminal  implements java.io.Serializable {


     private TmTerminalId id;
     private TmMerchant tmMerchant;
     private String ctrStatus;
     private String ctrType;
     private String dtrTerminalSn;
     private String ntrSwversion;
     private String ctrWorkingKey;
     private String ftrGenWkdate;
     private String dtrAddress;
     private String dtrDescription;
     private String ctrSeqNumber;
     private String ctrTypeWork;
     private String ctrModel;
     private Character ctrConnect;
     private Character ctrMultMerchant;
     private Character ctrStatusLogin;
     private String ctrTraceNumber;
     private String ctrLoteNumber;
     private String ctrAplicacion;
     private String ctrHfr1;
     private String ctrHfr2;
     private String ctrHfr3;
     private String ctrTrl1;
     private String ctrTrl2;
     private String ctrFtr1;
     private String ctrFtr2;
     private String ctrFtr3;
     private String ctrCodBar;
     private String ctrCodVer;
     private String ctrCodTarj;
     private String ctrDobleImp;
     private String ctrImpPago;
     private String ctrImpCuota;
     private String ctrImpDeuda;
     private String ctrClave;
     private String ctrNumMasterKey;
     private String ntrNroHopper;
     private String ctrCodMoneda1;
     private String ntrNroMoneda1;
     private String ctrCodMoneda2;
     private String ntrNroMoneda2;
     private String ctrCodMoneda3;
     private String ntrNroMoneda3;
     private String ctrCodMoneda4;
     private String ntrNroMoneda4;
     private String ctrAplicacionDest;
     private String ctrBatchNumber;
     private String ntrLongitudTrama;
     private String ctrModifyUser;
     private String ftrModifyDate;
     private String htrModifyTime;
     private String ftrLastEchoDate;
     private String htrLastEchoTime;
     private String ftrLastTrxFinDate;
     private String htrLastTrxFinTime;
     private String ftrLastTrxAdmDate;
     private String htrLastTrxAdmTime;
     private Long ctrFilesVersion;
     private Character ctrDownloadState;
     private String ntrDownloadAttempts;
     private String ftrLastDownloadDate;
     private String htrLastDownloadTime;
     private Character ctrTerminalStatus;
     private Character ctrPrinterStatus;
     private Character ctrHopper1status;
     private Character ctrHopper2status;
     private Character ctrHopper3status;
     private Character ctrHopper4status;
     private Character ctrForceUpdate;
     private BigDecimal ctrSaldoAmount;
     private BigDecimal ctrSaldoAmountDollar;
     private Character ctrMode;
     private String ctrStatusChangeReason;
     private String ftrCreationDate;
     private String htrCreationTime;
     private Character ctrLogicalStatus;
     private String ctrMultMerchantId;
     private Set taTerminalApplications = new HashSet(0);

    public TmTerminal() {
    }

	
    public TmTerminal(TmTerminalId id, TmMerchant tmMerchant, String ctrStatus, String ctrType) {
        this.id = id;
        this.tmMerchant = tmMerchant;
        this.ctrStatus = ctrStatus;
        this.ctrType = ctrType;
    }
    public TmTerminal(TmTerminalId id, TmMerchant tmMerchant, String ctrStatus, String ctrType, String dtrTerminalSn, String ntrSwversion, String ctrWorkingKey, String ftrGenWkdate, String dtrAddress, String dtrDescription, String ctrSeqNumber, String ctrTypeWork, String ctrModel, Character ctrConnect, Character ctrMultMerchant, Character ctrStatusLogin, String ctrTraceNumber, String ctrLoteNumber, String ctrAplicacion, String ctrHfr1, String ctrHfr2, String ctrHfr3, String ctrTrl1, String ctrTrl2, String ctrFtr1, String ctrFtr2, String ctrFtr3, String ctrCodBar, String ctrCodVer, String ctrCodTarj, String ctrDobleImp, String ctrImpPago, String ctrImpCuota, String ctrImpDeuda, String ctrClave, String ctrNumMasterKey, String ntrNroHopper, String ctrCodMoneda1, String ntrNroMoneda1, String ctrCodMoneda2, String ntrNroMoneda2, String ctrCodMoneda3, String ntrNroMoneda3, String ctrCodMoneda4, String ntrNroMoneda4, String ctrAplicacionDest, String ctrBatchNumber, String ntrLongitudTrama, String ctrModifyUser, String ftrModifyDate, String htrModifyTime, String ftrLastEchoDate, String htrLastEchoTime, String ftrLastTrxFinDate, String htrLastTrxFinTime, String ftrLastTrxAdmDate, String htrLastTrxAdmTime, Long ctrFilesVersion, Character ctrDownloadState, String ntrDownloadAttempts, String ftrLastDownloadDate, String htrLastDownloadTime, Character ctrTerminalStatus, Character ctrPrinterStatus, Character ctrHopper1status, Character ctrHopper2status, Character ctrHopper3status, Character ctrHopper4status, Character ctrForceUpdate, BigDecimal ctrSaldoAmount, BigDecimal ctrSaldoAmountDollar, Character ctrMode, String ctrStatusChangeReason, String ftrCreationDate, String htrCreationTime, Character ctrLogicalStatus, String ctrMultMerchantId, Set taTerminalApplications) {
       this.id = id;
       this.tmMerchant = tmMerchant;
       this.ctrStatus = ctrStatus;
       this.ctrType = ctrType;
       this.dtrTerminalSn = dtrTerminalSn;
       this.ntrSwversion = ntrSwversion;
       this.ctrWorkingKey = ctrWorkingKey;
       this.ftrGenWkdate = ftrGenWkdate;
       this.dtrAddress = dtrAddress;
       this.dtrDescription = dtrDescription;
       this.ctrSeqNumber = ctrSeqNumber;
       this.ctrTypeWork = ctrTypeWork;
       this.ctrModel = ctrModel;
       this.ctrConnect = ctrConnect;
       this.ctrMultMerchant = ctrMultMerchant;
       this.ctrStatusLogin = ctrStatusLogin;
       this.ctrTraceNumber = ctrTraceNumber;
       this.ctrLoteNumber = ctrLoteNumber;
       this.ctrAplicacion = ctrAplicacion;
       this.ctrHfr1 = ctrHfr1;
       this.ctrHfr2 = ctrHfr2;
       this.ctrHfr3 = ctrHfr3;
       this.ctrTrl1 = ctrTrl1;
       this.ctrTrl2 = ctrTrl2;
       this.ctrFtr1 = ctrFtr1;
       this.ctrFtr2 = ctrFtr2;
       this.ctrFtr3 = ctrFtr3;
       this.ctrCodBar = ctrCodBar;
       this.ctrCodVer = ctrCodVer;
       this.ctrCodTarj = ctrCodTarj;
       this.ctrDobleImp = ctrDobleImp;
       this.ctrImpPago = ctrImpPago;
       this.ctrImpCuota = ctrImpCuota;
       this.ctrImpDeuda = ctrImpDeuda;
       this.ctrClave = ctrClave;
       this.ctrNumMasterKey = ctrNumMasterKey;
       this.ntrNroHopper = ntrNroHopper;
       this.ctrCodMoneda1 = ctrCodMoneda1;
       this.ntrNroMoneda1 = ntrNroMoneda1;
       this.ctrCodMoneda2 = ctrCodMoneda2;
       this.ntrNroMoneda2 = ntrNroMoneda2;
       this.ctrCodMoneda3 = ctrCodMoneda3;
       this.ntrNroMoneda3 = ntrNroMoneda3;
       this.ctrCodMoneda4 = ctrCodMoneda4;
       this.ntrNroMoneda4 = ntrNroMoneda4;
       this.ctrAplicacionDest = ctrAplicacionDest;
       this.ctrBatchNumber = ctrBatchNumber;
       this.ntrLongitudTrama = ntrLongitudTrama;
       this.ctrModifyUser = ctrModifyUser;
       this.ftrModifyDate = ftrModifyDate;
       this.htrModifyTime = htrModifyTime;
       this.ftrLastEchoDate = ftrLastEchoDate;
       this.htrLastEchoTime = htrLastEchoTime;
       this.ftrLastTrxFinDate = ftrLastTrxFinDate;
       this.htrLastTrxFinTime = htrLastTrxFinTime;
       this.ftrLastTrxAdmDate = ftrLastTrxAdmDate;
       this.htrLastTrxAdmTime = htrLastTrxAdmTime;
       this.ctrFilesVersion = ctrFilesVersion;
       this.ctrDownloadState = ctrDownloadState;
       this.ntrDownloadAttempts = ntrDownloadAttempts;
       this.ftrLastDownloadDate = ftrLastDownloadDate;
       this.htrLastDownloadTime = htrLastDownloadTime;
       this.ctrTerminalStatus = ctrTerminalStatus;
       this.ctrPrinterStatus = ctrPrinterStatus;
       this.ctrHopper1status = ctrHopper1status;
       this.ctrHopper2status = ctrHopper2status;
       this.ctrHopper3status = ctrHopper3status;
       this.ctrHopper4status = ctrHopper4status;
       this.ctrForceUpdate = ctrForceUpdate;
       this.ctrSaldoAmount = ctrSaldoAmount;
       this.ctrSaldoAmountDollar = ctrSaldoAmountDollar;
       this.ctrMode = ctrMode;
       this.ctrStatusChangeReason = ctrStatusChangeReason;
       this.ftrCreationDate = ftrCreationDate;
       this.htrCreationTime = htrCreationTime;
       this.ctrLogicalStatus = ctrLogicalStatus;
       this.ctrMultMerchantId = ctrMultMerchantId;
       this.taTerminalApplications = taTerminalApplications;
    }
   
    public TmTerminalId getId() {
        return this.id;
    }
    
    public void setId(TmTerminalId id) {
        this.id = id;
    }
    public TmMerchant getTmMerchant() {
        return this.tmMerchant;
    }
    
    public void setTmMerchant(TmMerchant tmMerchant) {
        this.tmMerchant = tmMerchant;
    }
    public String getCtrStatus() {
        return this.ctrStatus;
    }
    
    public void setCtrStatus(String ctrStatus) {
        this.ctrStatus = ctrStatus;
    }
    public String getCtrType() {
        return this.ctrType;
    }
    
    public void setCtrType(String ctrType) {
        this.ctrType = ctrType;
    }
    public String getDtrTerminalSn() {
        return this.dtrTerminalSn;
    }
    
    public void setDtrTerminalSn(String dtrTerminalSn) {
        this.dtrTerminalSn = dtrTerminalSn;
    }
    public String getNtrSwversion() {
        return this.ntrSwversion;
    }
    
    public void setNtrSwversion(String ntrSwversion) {
        this.ntrSwversion = ntrSwversion;
    }
    public String getCtrWorkingKey() {
        return this.ctrWorkingKey;
    }
    
    public void setCtrWorkingKey(String ctrWorkingKey) {
        this.ctrWorkingKey = ctrWorkingKey;
    }
    public String getFtrGenWkdate() {
        return this.ftrGenWkdate;
    }
    
    public void setFtrGenWkdate(String ftrGenWkdate) {
        this.ftrGenWkdate = ftrGenWkdate;
    }
    public String getDtrAddress() {
        return this.dtrAddress;
    }
    
    public void setDtrAddress(String dtrAddress) {
        this.dtrAddress = dtrAddress;
    }
    public String getDtrDescription() {
        return this.dtrDescription;
    }
    
    public void setDtrDescription(String dtrDescription) {
        this.dtrDescription = dtrDescription;
    }
    public String getCtrSeqNumber() {
        return this.ctrSeqNumber;
    }
    
    public void setCtrSeqNumber(String ctrSeqNumber) {
        this.ctrSeqNumber = ctrSeqNumber;
    }
    public String getCtrTypeWork() {
        return this.ctrTypeWork;
    }
    
    public void setCtrTypeWork(String ctrTypeWork) {
        this.ctrTypeWork = ctrTypeWork;
    }
    public String getCtrModel() {
        return this.ctrModel;
    }
    
    public void setCtrModel(String ctrModel) {
        this.ctrModel = ctrModel;
    }
    public Character getCtrConnect() {
        return this.ctrConnect;
    }
    
    public void setCtrConnect(Character ctrConnect) {
        this.ctrConnect = ctrConnect;
    }
    public Character getCtrMultMerchant() {
        return this.ctrMultMerchant;
    }
    
    public void setCtrMultMerchant(Character ctrMultMerchant) {
        this.ctrMultMerchant = ctrMultMerchant;
    }
    public Character getCtrStatusLogin() {
        return this.ctrStatusLogin;
    }
    
    public void setCtrStatusLogin(Character ctrStatusLogin) {
        this.ctrStatusLogin = ctrStatusLogin;
    }
    public String getCtrTraceNumber() {
        return this.ctrTraceNumber;
    }
    
    public void setCtrTraceNumber(String ctrTraceNumber) {
        this.ctrTraceNumber = ctrTraceNumber;
    }
    public String getCtrLoteNumber() {
        return this.ctrLoteNumber;
    }
    
    public void setCtrLoteNumber(String ctrLoteNumber) {
        this.ctrLoteNumber = ctrLoteNumber;
    }
    public String getCtrAplicacion() {
        return this.ctrAplicacion;
    }
    
    public void setCtrAplicacion(String ctrAplicacion) {
        this.ctrAplicacion = ctrAplicacion;
    }
    public String getCtrHfr1() {
        return this.ctrHfr1;
    }
    
    public void setCtrHfr1(String ctrHfr1) {
        this.ctrHfr1 = ctrHfr1;
    }
    public String getCtrHfr2() {
        return this.ctrHfr2;
    }
    
    public void setCtrHfr2(String ctrHfr2) {
        this.ctrHfr2 = ctrHfr2;
    }
    public String getCtrHfr3() {
        return this.ctrHfr3;
    }
    
    public void setCtrHfr3(String ctrHfr3) {
        this.ctrHfr3 = ctrHfr3;
    }
    public String getCtrTrl1() {
        return this.ctrTrl1;
    }
    
    public void setCtrTrl1(String ctrTrl1) {
        this.ctrTrl1 = ctrTrl1;
    }
    public String getCtrTrl2() {
        return this.ctrTrl2;
    }
    
    public void setCtrTrl2(String ctrTrl2) {
        this.ctrTrl2 = ctrTrl2;
    }
    public String getCtrFtr1() {
        return this.ctrFtr1;
    }
    
    public void setCtrFtr1(String ctrFtr1) {
        this.ctrFtr1 = ctrFtr1;
    }
    public String getCtrFtr2() {
        return this.ctrFtr2;
    }
    
    public void setCtrFtr2(String ctrFtr2) {
        this.ctrFtr2 = ctrFtr2;
    }
    public String getCtrFtr3() {
        return this.ctrFtr3;
    }
    
    public void setCtrFtr3(String ctrFtr3) {
        this.ctrFtr3 = ctrFtr3;
    }
    public String getCtrCodBar() {
        return this.ctrCodBar;
    }
    
    public void setCtrCodBar(String ctrCodBar) {
        this.ctrCodBar = ctrCodBar;
    }
    public String getCtrCodVer() {
        return this.ctrCodVer;
    }
    
    public void setCtrCodVer(String ctrCodVer) {
        this.ctrCodVer = ctrCodVer;
    }
    public String getCtrCodTarj() {
        return this.ctrCodTarj;
    }
    
    public void setCtrCodTarj(String ctrCodTarj) {
        this.ctrCodTarj = ctrCodTarj;
    }
    public String getCtrDobleImp() {
        return this.ctrDobleImp;
    }
    
    public void setCtrDobleImp(String ctrDobleImp) {
        this.ctrDobleImp = ctrDobleImp;
    }
    public String getCtrImpPago() {
        return this.ctrImpPago;
    }
    
    public void setCtrImpPago(String ctrImpPago) {
        this.ctrImpPago = ctrImpPago;
    }
    public String getCtrImpCuota() {
        return this.ctrImpCuota;
    }
    
    public void setCtrImpCuota(String ctrImpCuota) {
        this.ctrImpCuota = ctrImpCuota;
    }
    public String getCtrImpDeuda() {
        return this.ctrImpDeuda;
    }
    
    public void setCtrImpDeuda(String ctrImpDeuda) {
        this.ctrImpDeuda = ctrImpDeuda;
    }
    public String getCtrClave() {
        return this.ctrClave;
    }
    
    public void setCtrClave(String ctrClave) {
        this.ctrClave = ctrClave;
    }
    public String getCtrNumMasterKey() {
        return this.ctrNumMasterKey;
    }
    
    public void setCtrNumMasterKey(String ctrNumMasterKey) {
        this.ctrNumMasterKey = ctrNumMasterKey;
    }
    public String getNtrNroHopper() {
        return this.ntrNroHopper;
    }
    
    public void setNtrNroHopper(String ntrNroHopper) {
        this.ntrNroHopper = ntrNroHopper;
    }
    public String getCtrCodMoneda1() {
        return this.ctrCodMoneda1;
    }
    
    public void setCtrCodMoneda1(String ctrCodMoneda1) {
        this.ctrCodMoneda1 = ctrCodMoneda1;
    }
    public String getNtrNroMoneda1() {
        return this.ntrNroMoneda1;
    }
    
    public void setNtrNroMoneda1(String ntrNroMoneda1) {
        this.ntrNroMoneda1 = ntrNroMoneda1;
    }
    public String getCtrCodMoneda2() {
        return this.ctrCodMoneda2;
    }
    
    public void setCtrCodMoneda2(String ctrCodMoneda2) {
        this.ctrCodMoneda2 = ctrCodMoneda2;
    }
    public String getNtrNroMoneda2() {
        return this.ntrNroMoneda2;
    }
    
    public void setNtrNroMoneda2(String ntrNroMoneda2) {
        this.ntrNroMoneda2 = ntrNroMoneda2;
    }
    public String getCtrCodMoneda3() {
        return this.ctrCodMoneda3;
    }
    
    public void setCtrCodMoneda3(String ctrCodMoneda3) {
        this.ctrCodMoneda3 = ctrCodMoneda3;
    }
    public String getNtrNroMoneda3() {
        return this.ntrNroMoneda3;
    }
    
    public void setNtrNroMoneda3(String ntrNroMoneda3) {
        this.ntrNroMoneda3 = ntrNroMoneda3;
    }
    public String getCtrCodMoneda4() {
        return this.ctrCodMoneda4;
    }
    
    public void setCtrCodMoneda4(String ctrCodMoneda4) {
        this.ctrCodMoneda4 = ctrCodMoneda4;
    }
    public String getNtrNroMoneda4() {
        return this.ntrNroMoneda4;
    }
    
    public void setNtrNroMoneda4(String ntrNroMoneda4) {
        this.ntrNroMoneda4 = ntrNroMoneda4;
    }
    public String getCtrAplicacionDest() {
        return this.ctrAplicacionDest;
    }
    
    public void setCtrAplicacionDest(String ctrAplicacionDest) {
        this.ctrAplicacionDest = ctrAplicacionDest;
    }
    public String getCtrBatchNumber() {
        return this.ctrBatchNumber;
    }
    
    public void setCtrBatchNumber(String ctrBatchNumber) {
        this.ctrBatchNumber = ctrBatchNumber;
    }
    public String getNtrLongitudTrama() {
        return this.ntrLongitudTrama;
    }
    
    public void setNtrLongitudTrama(String ntrLongitudTrama) {
        this.ntrLongitudTrama = ntrLongitudTrama;
    }
    public String getCtrModifyUser() {
        return this.ctrModifyUser;
    }
    
    public void setCtrModifyUser(String ctrModifyUser) {
        this.ctrModifyUser = ctrModifyUser;
    }
    public String getFtrModifyDate() {
        return this.ftrModifyDate;
    }
    
    public void setFtrModifyDate(String ftrModifyDate) {
        this.ftrModifyDate = ftrModifyDate;
    }
    public String getHtrModifyTime() {
        return this.htrModifyTime;
    }
    
    public void setHtrModifyTime(String htrModifyTime) {
        this.htrModifyTime = htrModifyTime;
    }
    public String getFtrLastEchoDate() {
        return this.ftrLastEchoDate;
    }
    
    public void setFtrLastEchoDate(String ftrLastEchoDate) {
        this.ftrLastEchoDate = ftrLastEchoDate;
    }
    public String getHtrLastEchoTime() {
        return this.htrLastEchoTime;
    }
    
    public void setHtrLastEchoTime(String htrLastEchoTime) {
        this.htrLastEchoTime = htrLastEchoTime;
    }
    public String getFtrLastTrxFinDate() {
        return this.ftrLastTrxFinDate;
    }
    
    public void setFtrLastTrxFinDate(String ftrLastTrxFinDate) {
        this.ftrLastTrxFinDate = ftrLastTrxFinDate;
    }
    public String getHtrLastTrxFinTime() {
        return this.htrLastTrxFinTime;
    }
    
    public void setHtrLastTrxFinTime(String htrLastTrxFinTime) {
        this.htrLastTrxFinTime = htrLastTrxFinTime;
    }
    public String getFtrLastTrxAdmDate() {
        return this.ftrLastTrxAdmDate;
    }
    
    public void setFtrLastTrxAdmDate(String ftrLastTrxAdmDate) {
        this.ftrLastTrxAdmDate = ftrLastTrxAdmDate;
    }
    public String getHtrLastTrxAdmTime() {
        return this.htrLastTrxAdmTime;
    }
    
    public void setHtrLastTrxAdmTime(String htrLastTrxAdmTime) {
        this.htrLastTrxAdmTime = htrLastTrxAdmTime;
    }
    public Long getCtrFilesVersion() {
        return this.ctrFilesVersion;
    }
    
    public void setCtrFilesVersion(Long ctrFilesVersion) {
        this.ctrFilesVersion = ctrFilesVersion;
    }
    public Character getCtrDownloadState() {
        return this.ctrDownloadState;
    }
    
    public void setCtrDownloadState(Character ctrDownloadState) {
        this.ctrDownloadState = ctrDownloadState;
    }
    public String getNtrDownloadAttempts() {
        return this.ntrDownloadAttempts;
    }
    
    public void setNtrDownloadAttempts(String ntrDownloadAttempts) {
        this.ntrDownloadAttempts = ntrDownloadAttempts;
    }
    public String getFtrLastDownloadDate() {
        return this.ftrLastDownloadDate;
    }
    
    public void setFtrLastDownloadDate(String ftrLastDownloadDate) {
        this.ftrLastDownloadDate = ftrLastDownloadDate;
    }
    public String getHtrLastDownloadTime() {
        return this.htrLastDownloadTime;
    }
    
    public void setHtrLastDownloadTime(String htrLastDownloadTime) {
        this.htrLastDownloadTime = htrLastDownloadTime;
    }
    public Character getCtrTerminalStatus() {
        return this.ctrTerminalStatus;
    }
    
    public void setCtrTerminalStatus(Character ctrTerminalStatus) {
        this.ctrTerminalStatus = ctrTerminalStatus;
    }
    public Character getCtrPrinterStatus() {
        return this.ctrPrinterStatus;
    }
    
    public void setCtrPrinterStatus(Character ctrPrinterStatus) {
        this.ctrPrinterStatus = ctrPrinterStatus;
    }
    public Character getCtrHopper1status() {
        return this.ctrHopper1status;
    }
    
    public void setCtrHopper1status(Character ctrHopper1status) {
        this.ctrHopper1status = ctrHopper1status;
    }
    public Character getCtrHopper2status() {
        return this.ctrHopper2status;
    }
    
    public void setCtrHopper2status(Character ctrHopper2status) {
        this.ctrHopper2status = ctrHopper2status;
    }
    public Character getCtrHopper3status() {
        return this.ctrHopper3status;
    }
    
    public void setCtrHopper3status(Character ctrHopper3status) {
        this.ctrHopper3status = ctrHopper3status;
    }
    public Character getCtrHopper4status() {
        return this.ctrHopper4status;
    }
    
    public void setCtrHopper4status(Character ctrHopper4status) {
        this.ctrHopper4status = ctrHopper4status;
    }
    public Character getCtrForceUpdate() {
        return this.ctrForceUpdate;
    }
    
    public void setCtrForceUpdate(Character ctrForceUpdate) {
        this.ctrForceUpdate = ctrForceUpdate;
    }
    public BigDecimal getCtrSaldoAmount() {
        return this.ctrSaldoAmount;
    }
    
    public void setCtrSaldoAmount(BigDecimal ctrSaldoAmount) {
        this.ctrSaldoAmount = ctrSaldoAmount;
    }
    public BigDecimal getCtrSaldoAmountDollar() {
        return this.ctrSaldoAmountDollar;
    }
    
    public void setCtrSaldoAmountDollar(BigDecimal ctrSaldoAmountDollar) {
        this.ctrSaldoAmountDollar = ctrSaldoAmountDollar;
    }
    public Character getCtrMode() {
        return this.ctrMode;
    }
    
    public void setCtrMode(Character ctrMode) {
        this.ctrMode = ctrMode;
    }
    public String getCtrStatusChangeReason() {
        return this.ctrStatusChangeReason;
    }
    
    public void setCtrStatusChangeReason(String ctrStatusChangeReason) {
        this.ctrStatusChangeReason = ctrStatusChangeReason;
    }
    public String getFtrCreationDate() {
        return this.ftrCreationDate;
    }
    
    public void setFtrCreationDate(String ftrCreationDate) {
        this.ftrCreationDate = ftrCreationDate;
    }
    public String getHtrCreationTime() {
        return this.htrCreationTime;
    }
    
    public void setHtrCreationTime(String htrCreationTime) {
        this.htrCreationTime = htrCreationTime;
    }
    public Character getCtrLogicalStatus() {
        return this.ctrLogicalStatus;
    }
    
    public void setCtrLogicalStatus(Character ctrLogicalStatus) {
        this.ctrLogicalStatus = ctrLogicalStatus;
    }
    public String getCtrMultMerchantId() {
        return this.ctrMultMerchantId;
    }
    
    public void setCtrMultMerchantId(String ctrMultMerchantId) {
        this.ctrMultMerchantId = ctrMultMerchantId;
    }
    public Set getTaTerminalApplications() {
        return this.taTerminalApplications;
    }
    
    public void setTaTerminalApplications(Set taTerminalApplications) {
        this.taTerminalApplications = taTerminalApplications;
    }




}


