package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmTipoPago generated by hbm2java
 */
public class TmTipoPago  implements java.io.Serializable {


     private String ctpaIdTipoPago;
     private String dtpaDescripcion;
     private char ctpaModoProceso;
     private char ctpaEstado;
     private Character ctpaFlagReqBanco; 
     private String ctpaModifyUser;
     private String ftpaModifyDate;
     private String htpaModifyTime;
     private Character ctpaFlagMostrarVentanilla;
     private Set taTipoPagoServicios = new HashSet(0);

    public TmTipoPago() {
    }

	
    public TmTipoPago(String ctpaIdTipoPago, char ctpaModoProceso, char ctpaEstado) {
        this.ctpaIdTipoPago = ctpaIdTipoPago;
        this.ctpaModoProceso = ctpaModoProceso;
        this.ctpaEstado = ctpaEstado;
    }
    public TmTipoPago(String ctpaIdTipoPago, String dtpaDescripcion, char ctpaModoProceso, char ctpaEstado, Character ctpaFlagReqBanco, String ctpaModifyUser, String ftpaModifyDate, String htpaModifyTime, Character ctpaFlagMostrarVentanilla, Set taTipoPagoServicios) {
       this.ctpaIdTipoPago = ctpaIdTipoPago;
       this.dtpaDescripcion = dtpaDescripcion;
       this.ctpaModoProceso = ctpaModoProceso;
       this.ctpaEstado = ctpaEstado;
       this.ctpaFlagReqBanco = ctpaFlagReqBanco;
       this.ctpaModifyUser = ctpaModifyUser;
       this.ftpaModifyDate = ftpaModifyDate;
       this.htpaModifyTime = htpaModifyTime;
       this.ctpaFlagMostrarVentanilla = ctpaFlagMostrarVentanilla;
       this.taTipoPagoServicios = taTipoPagoServicios;
    }
   
    public String getCtpaIdTipoPago() {
        return this.ctpaIdTipoPago;
    }
    
    public void setCtpaIdTipoPago(String ctpaIdTipoPago) {
        this.ctpaIdTipoPago = ctpaIdTipoPago;
    }
    public String getDtpaDescripcion() {
        return this.dtpaDescripcion;
    }
    
    public void setDtpaDescripcion(String dtpaDescripcion) {
        this.dtpaDescripcion = dtpaDescripcion;
    }
    public char getCtpaModoProceso() {
        return this.ctpaModoProceso;
    }
    
    public void setCtpaModoProceso(char ctpaModoProceso) {
        this.ctpaModoProceso = ctpaModoProceso;
    }
    public char getCtpaEstado() {
        return this.ctpaEstado;
    }
    
    public void setCtpaEstado(char ctpaEstado) {
        this.ctpaEstado = ctpaEstado;
    }
    public Character getCtpaFlagReqBanco() {
        return this.ctpaFlagReqBanco;
    }
    
    public void setCtpaFlagReqBanco(Character ctpaFlagReqBanco) {
        this.ctpaFlagReqBanco = ctpaFlagReqBanco;
    }
    public String getCtpaModifyUser() {
        return this.ctpaModifyUser;
    }
    
    public void setCtpaModifyUser(String ctpaModifyUser) {
        this.ctpaModifyUser = ctpaModifyUser;
    }
    public String getFtpaModifyDate() {
        return this.ftpaModifyDate;
    }
    
    public void setFtpaModifyDate(String ftpaModifyDate) {
        this.ftpaModifyDate = ftpaModifyDate;
    }
    public String getHtpaModifyTime() {
        return this.htpaModifyTime;
    }
    
    public void setHtpaModifyTime(String htpaModifyTime) {
        this.htpaModifyTime = htpaModifyTime;
    }
    public Character getCtpaFlagMostrarVentanilla() {
        return this.ctpaFlagMostrarVentanilla;
    }
    
    public void setCtpaFlagMostrarVentanilla(Character ctpaFlagMostrarVentanilla) {
        this.ctpaFlagMostrarVentanilla = ctpaFlagMostrarVentanilla;
    }
    public Set getTaTipoPagoServicios() {
        return this.taTipoPagoServicios;
    }
    
    public void setTaTipoPagoServicios(Set taTipoPagoServicios) {
        this.taTipoPagoServicios = taTipoPagoServicios;
    }




}


