package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TmTransactionType generated by hbm2java
 */
public class TmTransactionType  implements java.io.Serializable {


     private TmTransactionTypeId id;
     private String dtttransactionName;
     private Character ctttransGroup;
     private String cttmerchantVal;
     private String cttterminalVal;
     private String cttfloorLimitVal;
     private String cttactivityLimitVal;
     private String cttmerchantBalanceVal;
     private String cttsaveLog;
     private String ctttransType;
     private String ctttransRoute;
     private String cttrequiredFieldsReq;
     private String cttrequiredFieldsResp;
     private String cttconverterType;
     private String cttmodifyUser;
     private String fttmodifyDate;
     private String httmodifyTime;
     private String cttarchivo;
     private String cttwithoutCost;
     private Set taActivityLimits = new HashSet(0);
     private Set taFloorLimits = new HashSet(0);

    public TmTransactionType() {
    }

	
    public TmTransactionType(TmTransactionTypeId id) {
        this.id = id;
    }
    public TmTransactionType(TmTransactionTypeId id, String dtttransactionName, Character ctttransGroup, String cttmerchantVal, String cttterminalVal, String cttfloorLimitVal, String cttactivityLimitVal, String cttmerchantBalanceVal, String cttsaveLog, String ctttransType, String ctttransRoute, String cttrequiredFieldsReq, String cttrequiredFieldsResp, String cttconverterType, String cttmodifyUser, String fttmodifyDate, String httmodifyTime, String cttarchivo, String cttwithoutCost, Set taActivityLimits, Set taFloorLimits) {
       this.id = id;
       this.dtttransactionName = dtttransactionName;
       this.ctttransGroup = ctttransGroup;
       this.cttmerchantVal = cttmerchantVal;
       this.cttterminalVal = cttterminalVal;
       this.cttfloorLimitVal = cttfloorLimitVal;
       this.cttactivityLimitVal = cttactivityLimitVal;
       this.cttmerchantBalanceVal = cttmerchantBalanceVal;
       this.cttsaveLog = cttsaveLog;
       this.ctttransType = ctttransType;
       this.ctttransRoute = ctttransRoute;
       this.cttrequiredFieldsReq = cttrequiredFieldsReq;
       this.cttrequiredFieldsResp = cttrequiredFieldsResp;
       this.cttconverterType = cttconverterType;
       this.cttmodifyUser = cttmodifyUser;
       this.fttmodifyDate = fttmodifyDate;
       this.httmodifyTime = httmodifyTime;
       this.cttarchivo = cttarchivo;
       this.cttwithoutCost = cttwithoutCost;
       this.taActivityLimits = taActivityLimits;
       this.taFloorLimits = taFloorLimits;
    }
   
    public TmTransactionTypeId getId() {
        return this.id;
    }
    
    public void setId(TmTransactionTypeId id) {
        this.id = id;
    }
    public String getDtttransactionName() {
        return this.dtttransactionName;
    }
    
    public void setDtttransactionName(String dtttransactionName) {
        this.dtttransactionName = dtttransactionName;
    }
    public Character getCtttransGroup() {
        return this.ctttransGroup;
    }
    
    public void setCtttransGroup(Character ctttransGroup) {
        this.ctttransGroup = ctttransGroup;
    }
    public String getCttmerchantVal() {
        return this.cttmerchantVal;
    }
    
    public void setCttmerchantVal(String cttmerchantVal) {
        this.cttmerchantVal = cttmerchantVal;
    }
    public String getCttterminalVal() {
        return this.cttterminalVal;
    }
    
    public void setCttterminalVal(String cttterminalVal) {
        this.cttterminalVal = cttterminalVal;
    }
    public String getCttfloorLimitVal() {
        return this.cttfloorLimitVal;
    }
    
    public void setCttfloorLimitVal(String cttfloorLimitVal) {
        this.cttfloorLimitVal = cttfloorLimitVal;
    }
    public String getCttactivityLimitVal() {
        return this.cttactivityLimitVal;
    }
    
    public void setCttactivityLimitVal(String cttactivityLimitVal) {
        this.cttactivityLimitVal = cttactivityLimitVal;
    }
    public String getCttmerchantBalanceVal() {
        return this.cttmerchantBalanceVal;
    }
    
    public void setCttmerchantBalanceVal(String cttmerchantBalanceVal) {
        this.cttmerchantBalanceVal = cttmerchantBalanceVal;
    }
    public String getCttsaveLog() {
        return this.cttsaveLog;
    }
    
    public void setCttsaveLog(String cttsaveLog) {
        this.cttsaveLog = cttsaveLog;
    }
    public String getCtttransType() {
        return this.ctttransType;
    }
    
    public void setCtttransType(String ctttransType) {
        this.ctttransType = ctttransType;
    }
    public String getCtttransRoute() {
        return this.ctttransRoute;
    }
    
    public void setCtttransRoute(String ctttransRoute) {
        this.ctttransRoute = ctttransRoute;
    }
    public String getCttrequiredFieldsReq() {
        return this.cttrequiredFieldsReq;
    }
    
    public void setCttrequiredFieldsReq(String cttrequiredFieldsReq) {
        this.cttrequiredFieldsReq = cttrequiredFieldsReq;
    }
    public String getCttrequiredFieldsResp() {
        return this.cttrequiredFieldsResp;
    }
    
    public void setCttrequiredFieldsResp(String cttrequiredFieldsResp) {
        this.cttrequiredFieldsResp = cttrequiredFieldsResp;
    }
    public String getCttconverterType() {
        return this.cttconverterType;
    }
    
    public void setCttconverterType(String cttconverterType) {
        this.cttconverterType = cttconverterType;
    }
    public String getCttmodifyUser() {
        return this.cttmodifyUser;
    }
    
    public void setCttmodifyUser(String cttmodifyUser) {
        this.cttmodifyUser = cttmodifyUser;
    }
    public String getFttmodifyDate() {
        return this.fttmodifyDate;
    }
    
    public void setFttmodifyDate(String fttmodifyDate) {
        this.fttmodifyDate = fttmodifyDate;
    }
    public String getHttmodifyTime() {
        return this.httmodifyTime;
    }
    
    public void setHttmodifyTime(String httmodifyTime) {
        this.httmodifyTime = httmodifyTime;
    }
    public String getCttarchivo() {
        return this.cttarchivo;
    }
    
    public void setCttarchivo(String cttarchivo) {
        this.cttarchivo = cttarchivo;
    }
    public String getCttwithoutCost() {
        return this.cttwithoutCost;
    }
    
    public void setCttwithoutCost(String cttwithoutCost) {
        this.cttwithoutCost = cttwithoutCost;
    }
    public Set getTaActivityLimits() {
        return this.taActivityLimits;
    }
    
    public void setTaActivityLimits(Set taActivityLimits) {
        this.taActivityLimits = taActivityLimits;
    }
    public Set getTaFloorLimits() {
        return this.taFloorLimits;
    }
    
    public void setTaFloorLimits(Set taFloorLimits) {
        this.taFloorLimits = taFloorLimits;
    }




}


