package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpAlarmaLog generated by hbm2java
 */
public class TpAlarmaLog  implements java.io.Serializable {


     private TpAlarmaLogId id;
     private String hora;
     private String codError;
     private String valorCritico;
     private String numTerminal;
     private String codAgencia;
     private String estadoAlarma;
     private String estadoEnvio;
     private String descripcion;
     private String fechaAtencion;
     private String horaAtencion;

    public TpAlarmaLog() {
    }

	
    public TpAlarmaLog(TpAlarmaLogId id, String hora, String numTerminal, String codAgencia) {
        this.id = id;
        this.hora = hora;
        this.numTerminal = numTerminal;
        this.codAgencia = codAgencia;
    }
    public TpAlarmaLog(TpAlarmaLogId id, String hora, String codError, String valorCritico, String numTerminal, String codAgencia, String estadoAlarma, String estadoEnvio, String descripcion, String fechaAtencion, String horaAtencion) {
       this.id = id;
       this.hora = hora;
       this.codError = codError;
       this.valorCritico = valorCritico;
       this.numTerminal = numTerminal;
       this.codAgencia = codAgencia;
       this.estadoAlarma = estadoAlarma;
       this.estadoEnvio = estadoEnvio;
       this.descripcion = descripcion;
       this.fechaAtencion = fechaAtencion;
       this.horaAtencion = horaAtencion;
    }
   
    public TpAlarmaLogId getId() {
        return this.id;
    }
    
    public void setId(TpAlarmaLogId id) {
        this.id = id;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getCodError() {
        return this.codError;
    }
    
    public void setCodError(String codError) {
        this.codError = codError;
    }
    public String getValorCritico() {
        return this.valorCritico;
    }
    
    public void setValorCritico(String valorCritico) {
        this.valorCritico = valorCritico;
    }
    public String getNumTerminal() {
        return this.numTerminal;
    }
    
    public void setNumTerminal(String numTerminal) {
        this.numTerminal = numTerminal;
    }
    public String getCodAgencia() {
        return this.codAgencia;
    }
    
    public void setCodAgencia(String codAgencia) {
        this.codAgencia = codAgencia;
    }
    public String getEstadoAlarma() {
        return this.estadoAlarma;
    }
    
    public void setEstadoAlarma(String estadoAlarma) {
        this.estadoAlarma = estadoAlarma;
    }
    public String getEstadoEnvio() {
        return this.estadoEnvio;
    }
    
    public void setEstadoEnvio(String estadoEnvio) {
        this.estadoEnvio = estadoEnvio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(String fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public String getHoraAtencion() {
        return this.horaAtencion;
    }
    
    public void setHoraAtencion(String horaAtencion) {
        this.horaAtencion = horaAtencion;
    }




}


