package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpAlarmaLogId generated by hbm2java
 */
public class TpAlarmaLogId  implements java.io.Serializable {


     private String fecha;
     private String secuencia;
     private String codigo;

    public TpAlarmaLogId() {
    }

    public TpAlarmaLogId(String fecha, String secuencia, String codigo) {
       this.fecha = fecha;
       this.secuencia = secuencia;
       this.codigo = codigo;
    }
   
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(String secuencia) {
        this.secuencia = secuencia;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TpAlarmaLogId) ) return false;
		 TpAlarmaLogId castOther = ( TpAlarmaLogId ) other; 
         
		 return ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getSecuencia()==castOther.getSecuencia()) || ( this.getSecuencia()!=null && castOther.getSecuencia()!=null && this.getSecuencia().equals(castOther.getSecuencia()) ) )
 && ( (this.getCodigo()==castOther.getCodigo()) || ( this.getCodigo()!=null && castOther.getCodigo()!=null && this.getCodigo().equals(castOther.getCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getSecuencia() == null ? 0 : this.getSecuencia().hashCode() );
         result = 37 * result + ( getCodigo() == null ? 0 : this.getCodigo().hashCode() );
         return result;
   }   


}


