package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpDetalleCobroSinBd generated by hbm2java
 */
public class TpDetalleCobroSinBd  implements java.io.Serializable {


     private TpDetalleCobroSinBdId id;
     private TaServicioxEmpresa taServicioxEmpresa;

    public TpDetalleCobroSinBd() {
    }

    public TpDetalleCobroSinBd(TpDetalleCobroSinBdId id, TaServicioxEmpresa taServicioxEmpresa) {
       this.id = id;
       this.taServicioxEmpresa = taServicioxEmpresa;
    }
   
    public TpDetalleCobroSinBdId getId() {
        return this.id;
    }
    
    public void setId(TpDetalleCobroSinBdId id) {
        this.id = id;
    }
    public TaServicioxEmpresa getTaServicioxEmpresa() {
        return this.taServicioxEmpresa;
    }
    
    public void setTaServicioxEmpresa(TaServicioxEmpresa taServicioxEmpresa) {
        this.taServicioxEmpresa = taServicioxEmpresa;
    }




}


