package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpDetalleCobroSinBdId generated by hbm2java
 */
public class TpDetalleCobroSinBdId  implements java.io.Serializable {


     private long cdcoIdServicioEmpresa;
     private long cdcoIdDetalleCobro;

    public TpDetalleCobroSinBdId() {
    }

    public TpDetalleCobroSinBdId(long cdcoIdServicioEmpresa, long cdcoIdDetalleCobro) {
       this.cdcoIdServicioEmpresa = cdcoIdServicioEmpresa;
       this.cdcoIdDetalleCobro = cdcoIdDetalleCobro;
    }
   
    public long getCdcoIdServicioEmpresa() {
        return this.cdcoIdServicioEmpresa;
    }
    
    public void setCdcoIdServicioEmpresa(long cdcoIdServicioEmpresa) {
        this.cdcoIdServicioEmpresa = cdcoIdServicioEmpresa;
    }
    public long getCdcoIdDetalleCobro() {
        return this.cdcoIdDetalleCobro;
    }
    
    public void setCdcoIdDetalleCobro(long cdcoIdDetalleCobro) {
        this.cdcoIdDetalleCobro = cdcoIdDetalleCobro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TpDetalleCobroSinBdId) ) return false;
		 TpDetalleCobroSinBdId castOther = ( TpDetalleCobroSinBdId ) other; 
         
		 return (this.getCdcoIdServicioEmpresa()==castOther.getCdcoIdServicioEmpresa())
 && (this.getCdcoIdDetalleCobro()==castOther.getCdcoIdDetalleCobro());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCdcoIdServicioEmpresa();
         result = 37 * result + (int) this.getCdcoIdDetalleCobro();
         return result;
   }   


}


