package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TpDetalleOrden generated by hbm2java
 */
public class TpDetalleOrden  implements java.io.Serializable {
	private static final long serialVersionUID = -7248670025472415428L;
	private TpDetalleOrdenId id;
     private TpDetalleOrdenIdRep idRep;
     private TaOrden taOrden;    
     private String ndodocumento;
     private String cdocodDocumento;
     private String ddocomprobante;
     private String ddocontrapartida;
     private String ddonomContrapartida;
     private String cdocodBanco;
     private String ddonombre;
     private String ddodireccion;
     private String ddociudad;
     private String ddolocalidad;
     private String ndonumeroCuenta;
     private String ddotipoCuenta;
     private BigDecimal ndomonto;
     private String cdomoneda;
     private String ddotelefono;
     private String ddoemail;
     private String ddodescripcion;
     private char cdoestado;
     private String ddotipoPago;
     private String ddotipoDocumento;
     private String fdofechaProceso;
     private String hdohoraProceso;
     private String ndonumCuentaAbono;
     private String ndonumCuentaCargo;
     private String ddoreferencia;
     private String ddoreferenciaAdicional;
     private String ndonumCuentaAbonoCci;
     private String ddobancoBenef;
     private String cdotipoDocBenef;
     private String ndonumDocBenef;
     private String ddonombreBenef;
     private String ddoapePatBenef;
     private String ddoapeMatBenef;
     private String ddodireccionBenef;
     private String ddotlfBenef;
     private String fdofechaVenc;
     private BigDecimal ndomontoAbonado;
     private String cdomonedaMontoAbonado;
     private BigDecimal ndomontoDescuento;
     private String cdomonedaMontoDescuento;
     private BigDecimal ndomontoMora;
     private String cdomonedaMontoMora;
     private BigDecimal ndomontoComEmpresa;
     private String cdomonedaMontoComEmpresa;
     private BigDecimal ndomontoComCliente;
     private String cdomonedaMontoComCliente;
     private String ddoadicional1;
     private String ddoadicional2;
     private String ddoadicional3;
     private String ddoadicional4;
     private String ddoadicional5;
     private String ddoadicional6;
     private String ddoadicional7;
     private String ddoadicional8;
     private String ddoadicional9;
     private String ddoadicional10;
     private Long cdoidOrdenRef;
     private Long cdoidDetalleOrdenRef;
     private String ndonumPlanilla;
     private BigDecimal ndomontoLetra;
     private String ndocodAceptante;
     private String ndoidVentanilla;
     private String ndoidPago;
     private String ndonumCheque;
     private Character cdoflagMismoCliente;
     private BigDecimal ndoitf;
     private String cdomonedaItf;
     private BigDecimal ndoportes;
     private String cdomonedaPortes;
     private BigDecimal ndoprotesto;
     private String cdomonedaProtesto;
     private String cdocodigoRptaIbs;
     private BigDecimal ndomontoCliComisionChg;
     private BigDecimal ndomontoEmpComisionChg;
     private BigDecimal ndomontoVentanilla;
     private String cdoidAgencia;

          //Adicionales
     private String idEntidad;//Codigo EntidadEmpresa
     private String idServicioEntidad;//Codigo Servicio Entidad
     private String idTipo;//Codigo Tipo de Entidad
     private String descTipoCuenta;
     private String descTipoPago;
     private String descTipo;
     private String descTipoMoneda;
     private String idTipoDocumento;

     //jwong 11/05/2009 nuevo campo para manejo de pago proveedor
     private String flag_isproveedor; //valores SI o NO
     
     private long cdoidItemDetalle;

    public TpDetalleOrden() {
    }

	
    public TpDetalleOrden(TpDetalleOrdenId id, TaOrden taOrden , long cdoidItemDetalle, char cdoestado) {
        this.id = id;
        this.taOrden = taOrden;
        this.cdoidItemDetalle = cdoidItemDetalle;
        this.cdoestado = cdoestado;
    }
    public TpDetalleOrden(TpDetalleOrdenId id, TaOrden taOrden, long cdoidItemDetalle, String ndodocumento, String cdocodDocumento, String ddocomprobante, String ddocontrapartida, String ddonomContrapartida, String cdocodBanco, String ddonombre, String ddodireccion, String ddociudad, String ddolocalidad, String ndonumeroCuenta, String ddotipoCuenta, BigDecimal ndomonto, String cdomoneda, String ddotelefono, String ddoemail, String ddodescripcion, char cdoestado, String ddotipoPago, String ddotipoDocumento, String fdofechaProceso, String hdohoraProceso, String ndonumCuentaAbono, String ndonumCuentaCargo, String ddoreferencia, String ddoreferenciaAdicional, String ndonumCuentaAbonoCci, String ddobancoBenef, String cdotipoDocBenef, String ndonumDocBenef, String ddonombreBenef, String ddoapePatBenef, String ddoapeMatBenef, String ddodireccionBenef, String ddotlfBenef, String fdofechaVenc, BigDecimal ndomontoAbonado, String cdomonedaMontoAbonado, BigDecimal ndomontoDescuento, String cdomonedaMontoDescuento, BigDecimal ndomontoMora, String cdomonedaMontoMora, BigDecimal ndomontoComEmpresa, String cdomonedaMontoComEmpresa, BigDecimal ndomontoComCliente, String cdomonedaMontoComCliente, String ddoadicional1, String ddoadicional2, String ddoadicional3, String ddoadicional4, String ddoadicional5, String ddoadicional6, String ddoadicional7, String ddoadicional8, String ddoadicional9, String ddoadicional10, Long cdoidOrdenRef, Long cdoidDetalleOrdenRef, String ndonumPlanilla, BigDecimal ndomontoLetra, String ndocodAceptante, String ndoidVentanilla, String ndoidPago, String ndonumCheque, Character cdoflagMismoCliente, BigDecimal ndoitf,
            String cdomonedaItf, BigDecimal ndoportes, String cdomonedaPortes, BigDecimal ndoprotesto, String cdomonedaProtesto, String cdocodigoRptaIbs,
            BigDecimal ndomontoCliComisionChg,BigDecimal ndomontoEmpComisionChg,BigDecimal ndomontoVentanilla,String cdoidAgencia) {
       this.id = id;
       this.taOrden = taOrden;
       this.cdoidItemDetalle = cdoidItemDetalle;
       this.ndodocumento = ndodocumento;
       this.cdocodDocumento = cdocodDocumento;
       this.ddocomprobante = ddocomprobante;
       this.ddocontrapartida = ddocontrapartida;
       this.ddonomContrapartida = ddonomContrapartida;
       this.cdocodBanco = cdocodBanco;
       this.ddonombre = ddonombre;
       this.ddodireccion = ddodireccion;
       this.ddociudad = ddociudad;
       this.ddolocalidad = ddolocalidad;
       this.ndonumeroCuenta = ndonumeroCuenta;
       this.ddotipoCuenta = ddotipoCuenta;
       this.ndomonto = ndomonto;
       this.cdomoneda = cdomoneda;
       this.ddotelefono = ddotelefono;
       this.ddoemail = ddoemail;
       this.ddodescripcion = ddodescripcion;
       this.cdoestado = cdoestado;
       this.ddotipoPago = ddotipoPago;
       this.ddotipoDocumento = ddotipoDocumento;
       this.fdofechaProceso = fdofechaProceso;
       this.hdohoraProceso = hdohoraProceso;
       this.ndonumCuentaAbono = ndonumCuentaAbono;
       this.ndonumCuentaCargo = ndonumCuentaCargo;
       this.ddoreferencia = ddoreferencia;
       this.ddoreferenciaAdicional = ddoreferenciaAdicional;
       this.ndonumCuentaAbonoCci = ndonumCuentaAbonoCci;
       this.ddobancoBenef = ddobancoBenef;
       this.cdotipoDocBenef = cdotipoDocBenef;
       this.ndonumDocBenef = ndonumDocBenef;
       this.ddonombreBenef = ddonombreBenef;
       this.ddoapePatBenef = ddoapePatBenef;
       this.ddoapeMatBenef = ddoapeMatBenef;
       this.ddodireccionBenef = ddodireccionBenef;
       this.ddotlfBenef = ddotlfBenef;
       this.fdofechaVenc = fdofechaVenc;
       this.ndomontoAbonado = ndomontoAbonado;
       this.cdomonedaMontoAbonado = cdomonedaMontoAbonado;
       this.ndomontoDescuento = ndomontoDescuento;
       this.cdomonedaMontoDescuento = cdomonedaMontoDescuento;
       this.ndomontoMora = ndomontoMora;
       this.cdomonedaMontoMora = cdomonedaMontoMora;
       this.ndomontoComEmpresa = ndomontoComEmpresa;
       this.cdomonedaMontoComEmpresa = cdomonedaMontoComEmpresa;
       this.ndomontoComCliente = ndomontoComCliente;
       this.cdomonedaMontoComCliente = cdomonedaMontoComCliente;
       this.ddoadicional1 = ddoadicional1;
       this.ddoadicional2 = ddoadicional2;
       this.ddoadicional3 = ddoadicional3;
       this.ddoadicional4 = ddoadicional4;
       this.ddoadicional5 = ddoadicional5;
       this.ddoadicional6 = ddoadicional6;
       this.ddoadicional7 = ddoadicional7;
       this.ddoadicional8 = ddoadicional8;
       this.ddoadicional9 = ddoadicional9;
       this.ddoadicional10 = ddoadicional10;
       this.cdoidOrdenRef = cdoidOrdenRef;
       this.cdoidDetalleOrdenRef = cdoidDetalleOrdenRef;
       this.ndonumPlanilla = ndonumPlanilla;
       this.ndomontoLetra = ndomontoLetra;
       this.ndocodAceptante = ndocodAceptante;
       this.ndoidVentanilla = ndoidVentanilla;
       this.ndoidPago = ndoidPago;
       this.ndonumCheque = ndonumCheque;
       this.cdoflagMismoCliente = cdoflagMismoCliente;
       this.ndoitf = ndoitf;
       this.cdomonedaItf = cdomonedaItf;
       this.ndoportes = ndoportes;
       this.cdomonedaPortes = cdomonedaPortes;
       this.ndoprotesto = ndoprotesto;
       this.cdomonedaProtesto = cdomonedaProtesto;
       this.cdocodigoRptaIbs = cdocodigoRptaIbs;
       this.ndomontoCliComisionChg = ndomontoCliComisionChg;
       this.ndomontoEmpComisionChg = ndomontoEmpComisionChg;
       this.ndomontoVentanilla = ndomontoVentanilla;
       this.cdoidAgencia = cdoidAgencia;

    }
   
    public TpDetalleOrdenId getId() {
        return this.id;
    }
    
    public void setId(TpDetalleOrdenId id) {
        this.id = id;
    }       
    
    public TpDetalleOrdenIdRep getIdRep() {
		return idRep;
	}

	public void setIdRep(TpDetalleOrdenIdRep idRep) {
		this.idRep = idRep;
	}


	public TaOrden getTaOrden() {
        return this.taOrden;
    }
    
    public void setTaOrden(TaOrden taOrden) {
        this.taOrden = taOrden;
    }
//    public long getCdoidItemDetalle() {
//        return this.cdoidItemDetalle;
//    }
//
//    public void setCdoidItemDetalle(long cdoidItemDetalle) {
//        this.cdoidItemDetalle = cdoidItemDetalle;
//    }
    public String getNdodocumento() {
        return this.ndodocumento;
    }
    
    public void setNdodocumento(String ndodocumento) {
        this.ndodocumento = ndodocumento;
    }
    public String getCdocodDocumento() {
        return this.cdocodDocumento;
    }
    
    public void setCdocodDocumento(String cdocodDocumento) {
        this.cdocodDocumento = cdocodDocumento;
    }
    public String getDdocomprobante() {
        return this.ddocomprobante;
    }
    
    public void setDdocomprobante(String ddocomprobante) {
        this.ddocomprobante = ddocomprobante;
    }
    public String getDdocontrapartida() {
        return this.ddocontrapartida;
    }
    
    public void setDdocontrapartida(String ddocontrapartida) {
        this.ddocontrapartida = ddocontrapartida;
    }
    public String getDdonomContrapartida() {
        return this.ddonomContrapartida;
    }
    
    public void setDdonomContrapartida(String ddonomContrapartida) {
        this.ddonomContrapartida = ddonomContrapartida;
    }
    public String getCdocodBanco() {
        return this.cdocodBanco;
    }
    
    public void setCdocodBanco(String cdocodBanco) {
        this.cdocodBanco = cdocodBanco;
    }
    public String getDdonombre() {
        return this.ddonombre;
    }
    
    public void setDdonombre(String ddonombre) {
        this.ddonombre = ddonombre;
    }
    public String getDdodireccion() {
        return this.ddodireccion;
    }
    
    public void setDdodireccion(String ddodireccion) {
        this.ddodireccion = ddodireccion;
    }
    public String getDdociudad() {
        return this.ddociudad;
    }
    
    public void setDdociudad(String ddociudad) {
        this.ddociudad = ddociudad;
    }
    public String getDdolocalidad() {
        return this.ddolocalidad;
    }
    
    public void setDdolocalidad(String ddolocalidad) {
        this.ddolocalidad = ddolocalidad;
    }
    public String getNdonumeroCuenta() {
        return this.ndonumeroCuenta;
    }
    
    public void setNdonumeroCuenta(String ndonumeroCuenta) {
        this.ndonumeroCuenta = ndonumeroCuenta;
    }
    public String getDdotipoCuenta() {
        return this.ddotipoCuenta;
    }
    
    public void setDdotipoCuenta(String ddotipoCuenta) {
        this.ddotipoCuenta = ddotipoCuenta;
    }
    public BigDecimal getNdomonto() {
        return this.ndomonto;
    }
    
    public void setNdomonto(BigDecimal ndomonto) {
        this.ndomonto = ndomonto;
    }
    public String getCdomoneda() {
        return this.cdomoneda;
    }
    
    public void setCdomoneda(String cdomoneda) {
        this.cdomoneda = cdomoneda;
    }
    public String getDdotelefono() {
        return this.ddotelefono;
    }
    
    public void setDdotelefono(String ddotelefono) {
        this.ddotelefono = ddotelefono;
    }
    public String getDdoemail() {
        return this.ddoemail;
    }
    
    public void setDdoemail(String ddoemail) {
        this.ddoemail = ddoemail;
    }
    public String getDdodescripcion() {
        return this.ddodescripcion;
    }
    
    public void setDdodescripcion(String ddodescripcion) {
        this.ddodescripcion = ddodescripcion;
    }
    public char getCdoestado() {
        return this.cdoestado;
    }
    
    public void setCdoestado(char cdoestado) {
        this.cdoestado = cdoestado;
    }
    public String getDdotipoPago() {
        return this.ddotipoPago;
    }
    
    public void setDdotipoPago(String ddotipoPago) {    	    	
        this.ddotipoPago = ddotipoPago;
    }
    public String getDdotipoDocumento() {
        return this.ddotipoDocumento;
    }
    
    public void setDdotipoDocumento(String ddotipoDocumento) {
        this.ddotipoDocumento = ddotipoDocumento;
    }
    public String getFdofechaProceso() {
        return this.fdofechaProceso;
    }
    
    public void setFdofechaProceso(String fdofechaProceso) {
        this.fdofechaProceso = fdofechaProceso;
    }
    public String getHdohoraProceso() {
        return this.hdohoraProceso;
    }
    
    public void setHdohoraProceso(String hdohoraProceso) {
        this.hdohoraProceso = hdohoraProceso;
    }
    public String getNdonumCuentaAbono() {
        return this.ndonumCuentaAbono;
    }
    
    public void setNdonumCuentaAbono(String ndonumCuentaAbono) {
        this.ndonumCuentaAbono = ndonumCuentaAbono;
    }
    public String getNdonumCuentaCargo() {
        return this.ndonumCuentaCargo;
    }
    
    public void setNdonumCuentaCargo(String ndonumCuentaCargo) {
        this.ndonumCuentaCargo = ndonumCuentaCargo;
    }
    public String getDdoreferencia() {
        return this.ddoreferencia;
    }
    
    public void setDdoreferencia(String ddoreferencia) {
        this.ddoreferencia = ddoreferencia;
    }
    public String getDdoreferenciaAdicional() {
        return this.ddoreferenciaAdicional;
    }
    
    public void setDdoreferenciaAdicional(String ddoreferenciaAdicional) {
        this.ddoreferenciaAdicional = ddoreferenciaAdicional;
    }
    public String getNdonumCuentaAbonoCci() {
        return this.ndonumCuentaAbonoCci;
    }
    
    public void setNdonumCuentaAbonoCci(String ndonumCuentaAbonoCci) {
        this.ndonumCuentaAbonoCci = ndonumCuentaAbonoCci;
    }
    public String getDdobancoBenef() {
        return this.ddobancoBenef;
    }
    
    public void setDdobancoBenef(String ddobancoBenef) {
        this.ddobancoBenef = ddobancoBenef;
    }
    public String getCdotipoDocBenef() {
        return this.cdotipoDocBenef;
    }
    
    public void setCdotipoDocBenef(String cdotipoDocBenef) {
        this.cdotipoDocBenef = cdotipoDocBenef;
    }
    public String getNdonumDocBenef() {
        return this.ndonumDocBenef;
    }
    
    public void setNdonumDocBenef(String ndonumDocBenef) {
        this.ndonumDocBenef = ndonumDocBenef;
    }
    public String getDdonombreBenef() {
        return this.ddonombreBenef;
    }
    
    public void setDdonombreBenef(String ddonombreBenef) {
        this.ddonombreBenef = ddonombreBenef;
    }
    public String getDdoapePatBenef() {
        return this.ddoapePatBenef;
    }
    
    public void setDdoapePatBenef(String ddoapePatBenef) {
        this.ddoapePatBenef = ddoapePatBenef;
    }
    public String getDdoapeMatBenef() {
        return this.ddoapeMatBenef;
    }
    
    public void setDdoapeMatBenef(String ddoapeMatBenef) {
        this.ddoapeMatBenef = ddoapeMatBenef;
    }
    public String getDdodireccionBenef() {
        return this.ddodireccionBenef;
    }
    
    public void setDdodireccionBenef(String ddodireccionBenef) {
        this.ddodireccionBenef = ddodireccionBenef;
    }
    public String getDdotlfBenef() {
        return this.ddotlfBenef;
    }
    
    public void setDdotlfBenef(String ddotlfBenef) {
        this.ddotlfBenef = ddotlfBenef;
    }
    public String getFdofechaVenc() {
        return this.fdofechaVenc;
    }
    
    public void setFdofechaVenc(String fdofechaVenc) {
        this.fdofechaVenc = fdofechaVenc;
    }
    public BigDecimal getNdomontoAbonado() {
        return this.ndomontoAbonado;
    }
    
    public void setNdomontoAbonado(BigDecimal ndomontoAbonado) {
        this.ndomontoAbonado = ndomontoAbonado;
    }
    public String getCdomonedaMontoAbonado() {
        return this.cdomonedaMontoAbonado;
    }
    
    public void setCdomonedaMontoAbonado(String cdomonedaMontoAbonado) {
        this.cdomonedaMontoAbonado = cdomonedaMontoAbonado;
    }
    public BigDecimal getNdomontoDescuento() {
        return this.ndomontoDescuento;
    }
    
    public void setNdomontoDescuento(BigDecimal ndomontoDescuento) {
        this.ndomontoDescuento = ndomontoDescuento;
    }
    public String getCdomonedaMontoDescuento() {
        return this.cdomonedaMontoDescuento;
    }
    
    public void setCdomonedaMontoDescuento(String cdomonedaMontoDescuento) {
        this.cdomonedaMontoDescuento = cdomonedaMontoDescuento;
    }
    public BigDecimal getNdomontoMora() {
        return this.ndomontoMora;
    }
    
    public void setNdomontoMora(BigDecimal ndomontoMora) {
        this.ndomontoMora = ndomontoMora;
    }
    public String getCdomonedaMontoMora() {
        return this.cdomonedaMontoMora;
    }
    
    public void setCdomonedaMontoMora(String cdomonedaMontoMora) {
        this.cdomonedaMontoMora = cdomonedaMontoMora;
    }
    public BigDecimal getNdomontoComEmpresa() {
        return this.ndomontoComEmpresa;
    }
    
    public void setNdomontoComEmpresa(BigDecimal ndomontoComEmpresa) {
        this.ndomontoComEmpresa = ndomontoComEmpresa;
    }
    public String getCdomonedaMontoComEmpresa() {
        return this.cdomonedaMontoComEmpresa;
    }
    
    public void setCdomonedaMontoComEmpresa(String cdomonedaMontoComEmpresa) {
        this.cdomonedaMontoComEmpresa = cdomonedaMontoComEmpresa;
    }
    public BigDecimal getNdomontoComCliente() {
        return this.ndomontoComCliente;
    }
    
    public void setNdomontoComCliente(BigDecimal ndomontoComCliente) {
        this.ndomontoComCliente = ndomontoComCliente;
    }
    public String getCdomonedaMontoComCliente() {
        return this.cdomonedaMontoComCliente;
    }
    
    public void setCdomonedaMontoComCliente(String cdomonedaMontoComCliente) {
        this.cdomonedaMontoComCliente = cdomonedaMontoComCliente;
    }
    public String getDdoadicional1() {
        return this.ddoadicional1;
    }
    
    public void setDdoadicional1(String ddoadicional1) {
        this.ddoadicional1 = ddoadicional1;
    }
    public String getDdoadicional2() {
        return this.ddoadicional2;
    }
    
    public void setDdoadicional2(String ddoadicional2) {
        this.ddoadicional2 = ddoadicional2;
    }
    public String getDdoadicional3() {
        return this.ddoadicional3;
    }
    
    public void setDdoadicional3(String ddoadicional3) {
        this.ddoadicional3 = ddoadicional3;
    }
    public String getDdoadicional4() {
        return this.ddoadicional4;
    }
    
    public void setDdoadicional4(String ddoadicional4) {
        this.ddoadicional4 = ddoadicional4;
    }
    public String getDdoadicional5() {
        return this.ddoadicional5;
    }
    
    public void setDdoadicional5(String ddoadicional5) {
        this.ddoadicional5 = ddoadicional5;
    }
    public String getDdoadicional6() {
        return this.ddoadicional6;
    }
    
    public void setDdoadicional6(String ddoadicional6) {
        this.ddoadicional6 = ddoadicional6;
    }
    public String getDdoadicional7() {
        return this.ddoadicional7;
    }
    
    public void setDdoadicional7(String ddoadicional7) {
        this.ddoadicional7 = ddoadicional7;
    }
    public String getDdoadicional8() {
        return this.ddoadicional8;
    }
    
    public void setDdoadicional8(String ddoadicional8) {
        this.ddoadicional8 = ddoadicional8;
    }
    public String getDdoadicional9() {
        return this.ddoadicional9;
    }
    
    public void setDdoadicional9(String ddoadicional9) {
        this.ddoadicional9 = ddoadicional9;
    }
    public String getDdoadicional10() {
        return this.ddoadicional10;
    }
    
    public void setDdoadicional10(String ddoadicional10) {
        this.ddoadicional10 = ddoadicional10;
    }
    public Long getCdoidOrdenRef() {
        return this.cdoidOrdenRef;
    }
    
    public void setCdoidOrdenRef(Long cdoidOrdenRef) {
        this.cdoidOrdenRef = cdoidOrdenRef;
    }
    public Long getCdoidDetalleOrdenRef() {
        return this.cdoidDetalleOrdenRef;
    }
    
    public void setCdoidDetalleOrdenRef(Long cdoidDetalleOrdenRef) {
        this.cdoidDetalleOrdenRef = cdoidDetalleOrdenRef;
    }
    public String getNdonumPlanilla() {
        return this.ndonumPlanilla;
    }
    
    public void setNdonumPlanilla(String ndonumPlanilla) {
        this.ndonumPlanilla = ndonumPlanilla;
    }
    public BigDecimal getNdomontoLetra() {
        return this.ndomontoLetra;
    }
    
    public void setNdomontoLetra(BigDecimal ndomontoLetra) {
        this.ndomontoLetra = ndomontoLetra;
    }
    public String getNdocodAceptante() {
        return this.ndocodAceptante;
    }
    
    public void setNdocodAceptante(String ndocodAceptante) {
        this.ndocodAceptante = ndocodAceptante;
    }
    public String getNdoidVentanilla() {
        return this.ndoidVentanilla;
    }
    
    public void setNdoidVentanilla(String ndoidVentanilla) {
        this.ndoidVentanilla = ndoidVentanilla;
    }
    public String getNdoidPago() {
        return this.ndoidPago;
    }
    
    public void setNdoidPago(String ndoidPago) {
        this.ndoidPago = ndoidPago;
    }
    public String getNdonumCheque() {
        return this.ndonumCheque;
    }
    
    public void setNdonumCheque(String ndonumCheque) {
        this.ndonumCheque = ndonumCheque;
    }
    public Character getCdoflagMismoCliente() {
        return this.cdoflagMismoCliente;
    }
    
    public void setCdoflagMismoCliente(Character cdoflagMismoCliente) {
        this.cdoflagMismoCliente = cdoflagMismoCliente;
    }
    public BigDecimal getNdoitf() {
        return this.ndoitf;
    }
    
    public void setNdoitf(BigDecimal ndoitf) {
        this.ndoitf = ndoitf;
    }
    public String getCdomonedaItf() {
        return this.cdomonedaItf;
    }
    
    public void setCdomonedaItf(String cdomonedaItf) {
        this.cdomonedaItf = cdomonedaItf;
    }
    public BigDecimal getNdoportes() {
        return this.ndoportes;
    }
    
    public void setNdoportes(BigDecimal ndoportes) {
        this.ndoportes = ndoportes;
    }
    public String getCdomonedaPortes() {
        return this.cdomonedaPortes;
    }
    
    public void setCdomonedaPortes(String cdomonedaPortes) {
        this.cdomonedaPortes = cdomonedaPortes;
    }
    public BigDecimal getNdoprotesto() {
        return this.ndoprotesto;
    }
    
    public void setNdoprotesto(BigDecimal ndoprotesto) {
        this.ndoprotesto = ndoprotesto;
    }
    public String getCdomonedaProtesto() {
        return this.cdomonedaProtesto;
    }
    
    public void setCdomonedaProtesto(String cdomonedaProtesto) {
        this.cdomonedaProtesto = cdomonedaProtesto;
    }
    public String getCdocodigoRptaIbs() {
        return this.cdocodigoRptaIbs;
    }
    
    public void setCdocodigoRptaIbs(String cdocodigoRptaIbs) {
        this.cdocodigoRptaIbs = cdocodigoRptaIbs;
    }

    public String getIdEntidad() {
        return idEntidad;
    }

    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }

    public String getIdServicioEntidad() {
        return idServicioEntidad;
    }

    public void setIdServicioEntidad(String idServicioEntidad) {
        this.idServicioEntidad = idServicioEntidad;
    }

    public String getIdTipo() {
        return idTipo;
    }

    public void setIdTipo(String idTipo) {
        this.idTipo = idTipo;
    }

    public String getDescTipoCuenta() {
        return descTipoCuenta;
    }

    public void setDescTipoCuenta(String descTipoCuenta) {
        this.descTipoCuenta = descTipoCuenta;
    }

    public String getDescTipoPago() {
        return descTipoPago;
    }

    public void setDescTipoPago(String descTipoPago) {
        this.descTipoPago = descTipoPago;
    }

    public String getDescTipo() {
        return descTipo;
    }

    public void setDescTipo(String descTipo) {
        this.descTipo = descTipo;
    }

    public String getDescTipoMoneda() {
        return descTipoMoneda;
    }

    public void setDescTipoMoneda(String descTipoMoneda) {
        this.descTipoMoneda = descTipoMoneda;
    }

    public String getIdTipoDocumento() {
        return idTipoDocumento;
    }

    public void setIdTipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    public String getFlag_isproveedor() {
        return flag_isproveedor;
    }

    public void setFlag_isproveedor(String flag_isproveedor) {
        this.flag_isproveedor = flag_isproveedor;
    }

    public BigDecimal getNdomontoCliComisionChg() {
        return ndomontoCliComisionChg;
    }

    public void setNdomontoCliComisionChg(BigDecimal ndomontoCliComisionChg) {
        this.ndomontoCliComisionChg = ndomontoCliComisionChg;
    }

    public BigDecimal getNdomontoEmpComisionChg() {
        return ndomontoEmpComisionChg;
    }

    public void setNdomontoEmpComisionChg(BigDecimal ndomontoEmpComisionChg) {
        this.ndomontoEmpComisionChg = ndomontoEmpComisionChg;
    }

    public BigDecimal getNdomontoVentanilla() {
        return ndomontoVentanilla;
    }

    public void setNdomontoVentanilla(BigDecimal ndomontoVentanilla) {
        this.ndomontoVentanilla = ndomontoVentanilla;
    }

    public String getCdoidAgencia() {
        return cdoidAgencia;
    }

    public void setCdoidAgencia(String cdoidAgencia) {
        this.cdoidAgencia = cdoidAgencia;
    }

    public void setCdoidItemDetalle(long cdoidItemDetalle) {
		this.cdoidItemDetalle = cdoidItemDetalle;
	}
    
    public long getCdoidItemDetalle() {
		return cdoidItemDetalle;
	}
}


