package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpDetalleBuzonId generated by hbm2java
 */
public class TpDetalleBuzonId  implements java.io.Serializable {


     private long cdbuIdEnvio;
     private long cdbuIdDetalleBuzon;

    public TpDetalleBuzonId() {
    }

    public TpDetalleBuzonId(long cdbuIdEnvio, long cdbuIdDetalleBuzon) {
       this.cdbuIdEnvio = cdbuIdEnvio;
       this.cdbuIdDetalleBuzon = cdbuIdDetalleBuzon;
    }
   
    public long getCdbuIdEnvio() {
        return this.cdbuIdEnvio;
    }
    
    public void setCdbuIdEnvio(long cdbuIdEnvio) {
        this.cdbuIdEnvio = cdbuIdEnvio;
    }
    public long getCdbuIdDetalleBuzon() {
        return this.cdbuIdDetalleBuzon;
    }
    
    public void setCdbuIdDetalleBuzon(long cdbuIdDetalleBuzon) {
        this.cdbuIdDetalleBuzon = cdbuIdDetalleBuzon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TpDetalleBuzonId) ) return false;
		 TpDetalleBuzonId castOther = ( TpDetalleBuzonId ) other; 
         
		 return (this.getCdbuIdEnvio()==castOther.getCdbuIdEnvio())
 && (this.getCdbuIdDetalleBuzon()==castOther.getCdbuIdDetalleBuzon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCdbuIdEnvio();
         result = 37 * result + (int) this.getCdbuIdDetalleBuzon();
         return result;
   }   


}


