package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TpDetalleOrdenId generated by hbm2java
 */
public class TpDetalleOrdenId  implements java.io.Serializable {


     protected long cdoidOrden;
     protected long cdoidServicioEmpresa;
     protected long cdoidDetalleOrden;

    public TpDetalleOrdenId() {
    }

    public TpDetalleOrdenId(long cdoidOrden, long cdoidServicioEmpresa, long cdoidDetalleOrden) {
       this.cdoidOrden = cdoidOrden;
       this.cdoidServicioEmpresa = cdoidServicioEmpresa;
       this.cdoidDetalleOrden = cdoidDetalleOrden;
    }
   
    public long getCdoidOrden() {
        return this.cdoidOrden;
    }
    
    public void setCdoidOrden(long cdoidOrden) {
        this.cdoidOrden = cdoidOrden;
    }
    public long getCdoidServicioEmpresa() {
        return this.cdoidServicioEmpresa;
    }
    
    public void setCdoidServicioEmpresa(long cdoidServicioEmpresa) {
        this.cdoidServicioEmpresa = cdoidServicioEmpresa;
    }
    public long getCdoidDetalleOrden() {
        return this.cdoidDetalleOrden;
    }
    
    public void setCdoidDetalleOrden(long cdoidDetalleOrden) {
        this.cdoidDetalleOrden = cdoidDetalleOrden;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TpDetalleOrdenId) ) return false;
		 TpDetalleOrdenId castOther = ( TpDetalleOrdenId ) other; 
         
		 return (this.getCdoidOrden()==castOther.getCdoidOrden())
 && (this.getCdoidServicioEmpresa()==castOther.getCdoidServicioEmpresa())
 && (this.getCdoidDetalleOrden()==castOther.getCdoidDetalleOrden());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCdoidOrden();
         result = 37 * result + (int) this.getCdoidServicioEmpresa();
         result = 37 * result + (int) this.getCdoidDetalleOrden();
         return result;
   }   


}


