package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TxBatchId generated by hbm2java
 */
public class TxBatchId  implements java.io.Serializable {


     private String cbtMerchantId;
     private String cbtTerminalNum;
     private String cbtBatchId;
     private String cbtAplicacion;

    public TxBatchId() {
    }

    public TxBatchId(String cbtMerchantId, String cbtTerminalNum, String cbtBatchId, String cbtAplicacion) {
       this.cbtMerchantId = cbtMerchantId;
       this.cbtTerminalNum = cbtTerminalNum;
       this.cbtBatchId = cbtBatchId;
       this.cbtAplicacion = cbtAplicacion;
    }
   
    public String getCbtMerchantId() {
        return this.cbtMerchantId;
    }
    
    public void setCbtMerchantId(String cbtMerchantId) {
        this.cbtMerchantId = cbtMerchantId;
    }
    public String getCbtTerminalNum() {
        return this.cbtTerminalNum;
    }
    
    public void setCbtTerminalNum(String cbtTerminalNum) {
        this.cbtTerminalNum = cbtTerminalNum;
    }
    public String getCbtBatchId() {
        return this.cbtBatchId;
    }
    
    public void setCbtBatchId(String cbtBatchId) {
        this.cbtBatchId = cbtBatchId;
    }
    public String getCbtAplicacion() {
        return this.cbtAplicacion;
    }
    
    public void setCbtAplicacion(String cbtAplicacion) {
        this.cbtAplicacion = cbtAplicacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TxBatchId) ) return false;
		 TxBatchId castOther = ( TxBatchId ) other; 
         
		 return ( (this.getCbtMerchantId()==castOther.getCbtMerchantId()) || ( this.getCbtMerchantId()!=null && castOther.getCbtMerchantId()!=null && this.getCbtMerchantId().equals(castOther.getCbtMerchantId()) ) )
 && ( (this.getCbtTerminalNum()==castOther.getCbtTerminalNum()) || ( this.getCbtTerminalNum()!=null && castOther.getCbtTerminalNum()!=null && this.getCbtTerminalNum().equals(castOther.getCbtTerminalNum()) ) )
 && ( (this.getCbtBatchId()==castOther.getCbtBatchId()) || ( this.getCbtBatchId()!=null && castOther.getCbtBatchId()!=null && this.getCbtBatchId().equals(castOther.getCbtBatchId()) ) )
 && ( (this.getCbtAplicacion()==castOther.getCbtAplicacion()) || ( this.getCbtAplicacion()!=null && castOther.getCbtAplicacion()!=null && this.getCbtAplicacion().equals(castOther.getCbtAplicacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCbtMerchantId() == null ? 0 : this.getCbtMerchantId().hashCode() );
         result = 37 * result + ( getCbtTerminalNum() == null ? 0 : this.getCbtTerminalNum().hashCode() );
         result = 37 * result + ( getCbtBatchId() == null ? 0 : this.getCbtBatchId().hashCode() );
         result = 37 * result + ( getCbtAplicacion() == null ? 0 : this.getCbtAplicacion().hashCode() );
         return result;
   }   


}


