package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TxBatch generated by hbm2java
 */
public class TxBatch  implements java.io.Serializable {


     private TxBatchId id;
     private String cbtStatus;
     private String cbtSettleId;
     private String fbtCreationDate;
     private String hbtCreationHour;
     private short nbtTxnNumber;
     private BigDecimal nbtTotalAmount;
     private short nbtVoidTxnNum;
     private BigDecimal nbtVoidTotAmount;
     private String cbtModifyUser;
     private String cbtModifyDate;
     private String cbtModifyTime;

    public TxBatch() {
    }

	
    public TxBatch(TxBatchId id, String cbtStatus, String cbtSettleId, String fbtCreationDate, String hbtCreationHour, short nbtTxnNumber, BigDecimal nbtTotalAmount, short nbtVoidTxnNum, BigDecimal nbtVoidTotAmount) {
        this.id = id;
        this.cbtStatus = cbtStatus;
        this.cbtSettleId = cbtSettleId;
        this.fbtCreationDate = fbtCreationDate;
        this.hbtCreationHour = hbtCreationHour;
        this.nbtTxnNumber = nbtTxnNumber;
        this.nbtTotalAmount = nbtTotalAmount;
        this.nbtVoidTxnNum = nbtVoidTxnNum;
        this.nbtVoidTotAmount = nbtVoidTotAmount;
    }
    public TxBatch(TxBatchId id, String cbtStatus, String cbtSettleId, String fbtCreationDate, String hbtCreationHour, short nbtTxnNumber, BigDecimal nbtTotalAmount, short nbtVoidTxnNum, BigDecimal nbtVoidTotAmount, String cbtModifyUser, String cbtModifyDate, String cbtModifyTime) {
       this.id = id;
       this.cbtStatus = cbtStatus;
       this.cbtSettleId = cbtSettleId;
       this.fbtCreationDate = fbtCreationDate;
       this.hbtCreationHour = hbtCreationHour;
       this.nbtTxnNumber = nbtTxnNumber;
       this.nbtTotalAmount = nbtTotalAmount;
       this.nbtVoidTxnNum = nbtVoidTxnNum;
       this.nbtVoidTotAmount = nbtVoidTotAmount;
       this.cbtModifyUser = cbtModifyUser;
       this.cbtModifyDate = cbtModifyDate;
       this.cbtModifyTime = cbtModifyTime;
    }
   
    public TxBatchId getId() {
        return this.id;
    }
    
    public void setId(TxBatchId id) {
        this.id = id;
    }
    public String getCbtStatus() {
        return this.cbtStatus;
    }
    
    public void setCbtStatus(String cbtStatus) {
        this.cbtStatus = cbtStatus;
    }
    public String getCbtSettleId() {
        return this.cbtSettleId;
    }
    
    public void setCbtSettleId(String cbtSettleId) {
        this.cbtSettleId = cbtSettleId;
    }
    public String getFbtCreationDate() {
        return this.fbtCreationDate;
    }
    
    public void setFbtCreationDate(String fbtCreationDate) {
        this.fbtCreationDate = fbtCreationDate;
    }
    public String getHbtCreationHour() {
        return this.hbtCreationHour;
    }
    
    public void setHbtCreationHour(String hbtCreationHour) {
        this.hbtCreationHour = hbtCreationHour;
    }
    public short getNbtTxnNumber() {
        return this.nbtTxnNumber;
    }
    
    public void setNbtTxnNumber(short nbtTxnNumber) {
        this.nbtTxnNumber = nbtTxnNumber;
    }
    public BigDecimal getNbtTotalAmount() {
        return this.nbtTotalAmount;
    }
    
    public void setNbtTotalAmount(BigDecimal nbtTotalAmount) {
        this.nbtTotalAmount = nbtTotalAmount;
    }
    public short getNbtVoidTxnNum() {
        return this.nbtVoidTxnNum;
    }
    
    public void setNbtVoidTxnNum(short nbtVoidTxnNum) {
        this.nbtVoidTxnNum = nbtVoidTxnNum;
    }
    public BigDecimal getNbtVoidTotAmount() {
        return this.nbtVoidTotAmount;
    }
    
    public void setNbtVoidTotAmount(BigDecimal nbtVoidTotAmount) {
        this.nbtVoidTotAmount = nbtVoidTotAmount;
    }
    public String getCbtModifyUser() {
        return this.cbtModifyUser;
    }
    
    public void setCbtModifyUser(String cbtModifyUser) {
        this.cbtModifyUser = cbtModifyUser;
    }
    public String getCbtModifyDate() {
        return this.cbtModifyDate;
    }
    
    public void setCbtModifyDate(String cbtModifyDate) {
        this.cbtModifyDate = cbtModifyDate;
    }
    public String getCbtModifyTime() {
        return this.cbtModifyTime;
    }
    
    public void setCbtModifyTime(String cbtModifyTime) {
        this.cbtModifyTime = cbtModifyTime;
    }




}


