package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TxListFieldDetail generated by hbm2java
 */
public class TxListFieldDetail  implements java.io.Serializable {


     private TxListFieldDetailId id;
     private String clfdmodifyUser;
     private String flfdmodifyDate;
     private String hlfdmodifyTime;

    public TxListFieldDetail() {
    }

	
    public TxListFieldDetail(TxListFieldDetailId id) {
        this.id = id;
    }
    public TxListFieldDetail(TxListFieldDetailId id, String clfdmodifyUser, String flfdmodifyDate, String hlfdmodifyTime) {
       this.id = id;
       this.clfdmodifyUser = clfdmodifyUser;
       this.flfdmodifyDate = flfdmodifyDate;
       this.hlfdmodifyTime = hlfdmodifyTime;
    }
   
    public TxListFieldDetailId getId() {
        return this.id;
    }
    
    public void setId(TxListFieldDetailId id) {
        this.id = id;
    }
    public String getClfdmodifyUser() {
        return this.clfdmodifyUser;
    }
    
    public void setClfdmodifyUser(String clfdmodifyUser) {
        this.clfdmodifyUser = clfdmodifyUser;
    }
    public String getFlfdmodifyDate() {
        return this.flfdmodifyDate;
    }
    
    public void setFlfdmodifyDate(String flfdmodifyDate) {
        this.flfdmodifyDate = flfdmodifyDate;
    }
    public String getHlfdmodifyTime() {
        return this.hlfdmodifyTime;
    }
    
    public void setHlfdmodifyTime(String hlfdmodifyTime) {
        this.hlfdmodifyTime = hlfdmodifyTime;
    }




}


