package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TxListFieldId generated by hbm2java
 */
public class TxListFieldId  implements java.io.Serializable {


     private String dlfFieldName;
     private String clfCode;
     private String clfRelativeCode;

    public TxListFieldId() {
    }

    public TxListFieldId(String dlfFieldName, String clfCode, String clfRelativeCode) {
       this.dlfFieldName = dlfFieldName;
       this.clfCode = clfCode;
       this.clfRelativeCode = clfRelativeCode;
    }
   
    public String getDlfFieldName() {
        return this.dlfFieldName;
    }
    
    public void setDlfFieldName(String dlfFieldName) {
        this.dlfFieldName = dlfFieldName;
    }
    public String getClfCode() {
        return this.clfCode;
    }
    
    public void setClfCode(String clfCode) {
        this.clfCode = clfCode;
    }
    public String getClfRelativeCode() {
        return this.clfRelativeCode;
    }
    
    public void setClfRelativeCode(String clfRelativeCode) {
        this.clfRelativeCode = clfRelativeCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TxListFieldId) ) return false;
		 TxListFieldId castOther = ( TxListFieldId ) other; 
         
		 return ( (this.getDlfFieldName()==castOther.getDlfFieldName()) || ( this.getDlfFieldName()!=null && castOther.getDlfFieldName()!=null && this.getDlfFieldName().equals(castOther.getDlfFieldName()) ) )
 && ( (this.getClfCode()==castOther.getClfCode()) || ( this.getClfCode()!=null && castOther.getClfCode()!=null && this.getClfCode().equals(castOther.getClfCode()) ) )
 && ( (this.getClfRelativeCode()==castOther.getClfRelativeCode()) || ( this.getClfRelativeCode()!=null && castOther.getClfRelativeCode()!=null && this.getClfRelativeCode().equals(castOther.getClfRelativeCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDlfFieldName() == null ? 0 : this.getDlfFieldName().hashCode() );
         result = 37 * result + ( getClfCode() == null ? 0 : this.getClfCode().hashCode() );
         result = 37 * result + ( getClfRelativeCode() == null ? 0 : this.getClfRelativeCode().hashCode() );
         return result;
   }   


}


