package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TxResult generated by hbm2java
 */
public class TxResult  implements java.io.Serializable {
	private static final long serialVersionUID = 2721360619026070584L;
	private TxResultId id;
     private String drsDescription;
     private String drsLongDescript;
     private String crsTipoMensajes;

    public TxResult() {
    	
    }

	
    public TxResult(TxResultId id) {
        this.id = id;
    }
    
    public TxResult(TxResultId id, String drsDescription, String drsLongDescript) {
       this.id = id;
       this.drsDescription = drsDescription;
       this.drsLongDescript = drsLongDescript;
    }
   
    public TxResultId getId() {
        return this.id;
    }
    
    public void setId(TxResultId id) {
        this.id = id;
    }
    public String getDrsDescription() {
        return this.drsDescription;
    }
    
    public void setDrsDescription(String drsDescription) {
        this.drsDescription = drsDescription;
    }
    public String getDrsLongDescript() {
        return this.drsLongDescript;
    }
    
    public void setDrsLongDescript(String drsLongDescript) {
        this.drsLongDescript = drsLongDescript;
    }        

    public String getCrsTipoMensajes() {
		return crsTipoMensajes;
	}

	public void setCrsTipoMensajes(String crsTipoMensajes) {
		this.crsTipoMensajes = crsTipoMensajes;
	}

	@Override
    public String toString() {
    	return this.drsDescription;
    }


}


