package com.hiper.cash.domain;
// Generated 03/08/2009 06:16:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TxResultId generated by hbm2java
 */
public class TxResultId  implements java.io.Serializable {


     private String crsResultId;
     private String crsResultExt;

    public TxResultId() {
    }

    public TxResultId(String crsResultId, String crsResultExt) {
       this.crsResultId = crsResultId;
       this.crsResultExt = crsResultExt;
    }
   
    public String getCrsResultId() {
        return this.crsResultId;
    }
    
    public void setCrsResultId(String crsResultId) {
        this.crsResultId = crsResultId;
    }
    public String getCrsResultExt() {
        return this.crsResultExt;
    }
    
    public void setCrsResultExt(String crsResultExt) {
        this.crsResultExt = crsResultExt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TxResultId) ) return false;
		 TxResultId castOther = ( TxResultId ) other; 
         
		 return ( (this.getCrsResultId()==castOther.getCrsResultId()) || ( this.getCrsResultId()!=null && castOther.getCrsResultId()!=null && this.getCrsResultId().equals(castOther.getCrsResultId()) ) )
 && ( (this.getCrsResultExt()==castOther.getCrsResultExt()) || ( this.getCrsResultExt()!=null && castOther.getCrsResultExt()!=null && this.getCrsResultExt().equals(castOther.getCrsResultExt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCrsResultId() == null ? 0 : this.getCrsResultId().hashCode() );
         result = 37 * result + ( getCrsResultExt() == null ? 0 : this.getCrsResultExt().hashCode() );
         return result;
   }   


}


